AzureAD/microsoft-authentication-library-common-for-objc

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m

The mapping between MSID error and MSALError is here: 
https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/244
Mapping between MSID error and ADAL error will be added later.

Add unified way to create NSError

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/IdentityCore.xcodeproj/xcshareddata/xcschemes/IdentityCore iOS.xcscheme
IdentityCore/src/cache/MSIDToken.h
IdentityCore/src/cache/MSIDToken.m
IdentityCore/src/cache/MSIDUserInformation.h
IdentityCore/src/cache/MSIDUserInformation.m
IdentityCore/src/cache/serializers/MSIDKeyedArchiverSerializer.m
IdentityCore/tests/MSIDKeyedArchiverSerializerTests.m
IdentityCore/tests/MSIDTokenTests.m

Final version. Added new properties to MSIDToken:
- resource
- authority
- clientId
- scopes
Ignore *accessTokenType* when map to/from MSIDToken.  Seems that *accessTokenType* always has "Bearer" type, moreover, we parse it and store in cache in ADAL, but never use. Please correct me if I missed something.
In case if *ADTokenCacheItem* has both AT&RT we map it to *MSIDToken* with type *MSIDTokenTypeRefreshToken* and we ignore value of AT. If we need to get MSIDToken with type *MSIDTokenTypeAccessToken*, RT in *ADTokenCacheItem* should be nil. Added tests that cover this logic.

Implement MSIDKeyedArchiverSerializer

---

IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m

ADAL will return http headers in error object. Therefore we need to add a field in common core to store it.

Add http headers field to MSIDError

---

IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m

MSIDHTTPResponseCodeKey is added for storing http response code in error object.

add MSIDHTTPResponseCodeKey to MSIDError

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/MSIDOAuth2Constants.h
IdentityCore/src/MSIDOAuth2Constants.m
IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
IdentityCore/src/cache/accessor/MSIDSharedTokenCache.h
IdentityCore/src/cache/accessor/MSIDSharedTokenCache.m
IdentityCore/src/cache/key/MSIDLegacyTokenCacheKey.h
IdentityCore/src/cache/key/MSIDLegacyTokenCacheKey.m
IdentityCore/src/cache/token/MSIDTokenCacheItem.m
IdentityCore/src/oauth2/token/MSIDLegacySingleResourceToken.h
IdentityCore/src/oauth2/token/MSIDLegacySingleResourceToken.m
IdentityCore/src/oauth2/token/MSIDTokenType.h
IdentityCore/src/oauth2/token/MSIDTokenType.m
IdentityCore/src/telemetry/MSIDTelemetryCacheEvent.m
IdentityCore/tests/MSIDLegacySingleResourceTokenTests.m
IdentityCore/tests/MSIDTokenCacheItemTests.m
IdentityCore/tests/MSIDTokenTypeTests.m
IdentityCore/tests/integration/MSIDLegacyTokenCacheIntegrationTests.m
IdentityCore/tests/integration/MSIDLegacyTokenIntegrationTests.m
IdentityCore/tests/integration/MSIDSharedTokenCacheIntegrationTests.m
IdentityCore/tests/util/MSIDTestCacheDataSource.h
IdentityCore/tests/util/MSIDTestCacheDataSource.m
IdentityCore/tests/util/cache/MSIDTestCacheAccessor.m

Because ADFS tokens can also be multi resource, it was misleading to call single resource tokens "ADFS tokens". So, I renamed it across the project and also added ability to get single resource tokens for an account as we might need it.

Renamed ADFS token to legacy single resource token

---

IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.m
IdentityCore/src/oauth2/aad_v1/MSIDAADV1TokenResponse.m
IdentityCore/src/oauth2/aad_v2/MSIDAADV2TokenResponse.m
IdentityCore/tests/MSIDTokenResponseHandlerTests.m

We still have a valid case where clientInfo is not returned (broker), so we shouldn't be requiring clientInfo for that case for now

Don't require client info for V1 response

---

IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m

Fix a bug where we didn't add telemetry event for cache deletion in MSIDLegacyTokenCacheAccessor.

Add cache delete event to MSIDLegacyTokenCacheAccessor

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/cache/mac/MSIDMacTokenCache.m
IdentityCore/src/telemetry/MSIDTelemetry.m
IdentityCore/src/telemetry/MSIDTelemetryBaseEvent.m
IdentityCore/src/telemetry/MSIDTelemetryEventStrings.h
IdentityCore/src/telemetry/MSIDTelemetryPiiOiiRules.h
IdentityCore/src/telemetry/MSIDTelemetryPiiOiiRules.m
IdentityCore/src/util/NSString+MSIDTelemetryExtensions.m
IdentityCore/tests/MSIDTelemetryCacheEventTests.m
IdentityCore/tests/MSIDTelemetryExtensionsTests.m
IdentityCore/tests/MSIDTelemetryTests.m
IdentityCore/tests/integration/MSIDTelemetryIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDWipeDataTelemetryTests.m

Bug fixed:
- Pii filtering not working because some functions expect Telemetry prefix (like "Microsoft.ADAL." while the argument we pass in doesn't have it. 
Since there is no clear clue on when to use `TELEMETRY_KEY()` to add prefix and when not to use, it could be error-prone and cause confusion. Now we simply not use prefix in common core at all. Only we finally dispatch the events in ADAL/MSAL to developers, we add the prefix.
- Pii filtering is added for defaultParameters. Previously we forgot to filter for that.
Besides,
- Oii rules are added. If a property is Oii, it won't be hashed and will only be returned if PiiEnabled is true.
- UTs added.
The corresponding ADAL PR is [here](https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1193).

Telemetry Fix and Oii Rules

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj

Project file was messed up after webview merging. Here is a correct one.
ADAL update
https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1213
MSAL update
https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/283

Project file clean up

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/oauth2/MSIDWebviewFactory.h
IdentityCore/src/oauth2/MSIDWebviewFactory.m
IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
IdentityCore/src/webview/MSIDWebviewAuthorization.h
IdentityCore/src/webview/MSIDWebviewAuthorization.m
IdentityCore/src/webview/embeddedWebview/MSIDAADOAuthEmbeddedWebviewController.h
IdentityCore/src/webview/embeddedWebview/MSIDAADOAuthEmbeddedWebviewController.m
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.h
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
IdentityCore/src/webview/embeddedWebview/ui/MSIDWebviewUIController.h
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
IdentityCore/tests/MSIDOAuth2EmbeddedWebviewControllerTests.m
IdentityCore/tests/MSIDWebviewAuthorizationTests.m

Because we still haven't added WKWebView support to ADAL, we shouldn't force WebKit dependency on the first ADAL release

Don't force ADAL to have WebKit dependency

---

IdentityCore/src/util/NSURL+MSIDExtensions.h
IdentityCore/src/util/NSURL+MSIDExtensions.m
IdentityCore/tests/MSIDURLExtensionsTests.m

Found that ADFSv4 authority validation is broken, because it uses msidIsEquivalentAuthority method, but expects authorities to be equal even if path is not the same. 
* Added a new method with more appropriate name to be used in ADFS authority validation.
* Added tests for both of the methods

Added msid equivalent authority host method that checks only host

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
IdentityCore/src/webview/systemWebview/MSIDSFAuthenticationSession.m

- Add telemetry to embedded webview
- Move telemetry MSIDSFAuthenticationSession.m to only start when everything is valid.

Webview telemetry

---

IdentityCore/src/cache/MSIDMacTokenCache.m

Found a couple of issues:
* self.cache actually modified _cache sometimes, so it's unsafe to use self.cache in reading scenarios (replaced with _cache)
* clear cache didn't have any synchronization
* Data could be modified in setItem while serialization is in progress when serialize/deserialize routines are in use, so returned data was invalid at the time of return, which caused data integrity issues.

Fixed mac cache synchronization issues

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/network/MSIDHttpRequest.m
IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m
IdentityCore/src/network/request/MSIDAADAuthorityValidationRequest.h
IdentityCore/src/network/request/MSIDAADAuthorityValidationRequest.m
IdentityCore/src/network/request/MSIDAADAuthorizationCodeGrantRequest.m
IdentityCore/src/network/request/MSIDAADAuthorizationCodeRequest.h
IdentityCore/src/network/request/MSIDAADAuthorizationCodeRequest.m
IdentityCore/src/network/request/MSIDAADRefreshTokenGrantRequest.m
IdentityCore/src/network/request/MSIDAADV1AuthorizationCodeRequest.h
IdentityCore/src/network/request/MSIDAADV1AuthorizationCodeRequest.m
IdentityCore/src/network/request/MSIDAADV1RefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDAADV1RefreshTokenGrantRequest.m
IdentityCore/src/network/request/MSIDAuthorizationCodeGrantRequest.h
IdentityCore/src/network/request/MSIDAuthorizationCodeGrantRequest.m
IdentityCore/src/network/request/MSIDRefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDRefreshTokenGrantRequest.m
IdentityCore/src/network/request/MSIDTokenRequest.h
IdentityCore/src/network/request/MSIDTokenRequest.m
IdentityCore/src/network/request_serializer/MSIDUrlRequestSerializer.m
IdentityCore/src/network/response_serializer/MSIDAADResponseSerializer.m
IdentityCore/src/util/NSURL+MSIDExtensions.m
IdentityCore/tests/MSIDUrlRequestSerializerTests.m
IdentityCore/tests/util/network/MSIDTestURLResponse.m

- Add `MSIDAADAuthorityValidationRequest`
- Pass context to network request (for #178)
- Fix a bug in `MSIDAADResponseSerializer.m` which causes nil result for json parsing
- Fix a bug in function `msidAddParameters` which throws the existing parameters away
- Stop setting Content-length for Post network request as it is set automatically

Changes for Network Integration

---

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
IdentityCore/src/oauth2/MSIDWebviewFactory.m
IdentityCore/src/oauth2/aad_v2/MSIDAADV2IdTokenClaims.m
IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m
IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m

Main change here is for default accessor not to save tokens to legacy format. Because legacy cache can already read from default format, it's unnecessary. 
+ Also optimized getRefreshTokenByLegacyUserId to look by environment aliases and not by each alias separately for better performance
Accompanying ADAL PR to update submodule: https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1263
This PR goes to 1.0.0 release branch and this one merges 1.0.0 to dev: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/203

Added token cache optimizations

---

IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
IdentityCore/src/oauth2/aad_v2/MSIDAADV2WebviewFactory.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDPKeyAuthHandler.m
IdentityCore/tests/MSIDAADV1WebviewFactoryTests.m
IdentityCore/tests/MSIDAADWebviewFactoryTests.m

PKeyAuth handler no longer creates url components to append version check and decoding.
Move scopes addition logic from AAD base webview factory to V2 specific.

PKeyAuth handling and scopes handling fix

---

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/validation/MSIDAadAuthorityCache.m
IdentityCore/src/validation/MSIDAadAuthorityResolver.m
IdentityCore/tests/automation/MSIDTestAutomationConfiguration.m
IdentityCore/tests/integration/MSIDAuthorityIntegrationTests.m

* Always use composed OIDC endpoint for AAD resolver (as opposed to resolved)
* Don't use preferred_cache alias for MSAL default accessor
I'm still adding some more tests for those changes.

Changed cached environment in default accessor and removed dependency on openid config endpoint for AAD resolver

---

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
IdentityCore/src/oauth2/account/MSIDAccount.m
IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDWipeDataTelemetryTests.m

1. Reverted the change of not saving under preferred_cache in default accessor for consistency with ADAL
2. Removed refresh token existence check for accounts lookup, because we never remove refresh tokens without accounts for MSAL
3. Changed isEqual method to avoid returning duplicate accounts in case we have accounts in legacy cache without uid.utid
4. Added integration tests for those scenarios

Account lookup fixes

---

IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDCertificateChooser.m

The CBA chooser crashes because it shouldn't nil out the caller in the callback.
I.e., it calls the following with the caller being `_panel` and callback being `sheetDidEnd:returnCode:contextInfo:`:
```
[_panel beginSheetForWindow:_window
modalDelegate:self
didEndSelector:@selector(sheetDidEnd:returnCode:contextInfo:)	                  
contextInfo:NULL
identities:identities
message:message];
```
(line 57).
However, `_panel`is nil out right in the callback `sheetDidEnd:returnCode:contextInfo:` (at line 90).
XCode Instruments showed that, `@selector(_okClicked:)` was sent to a deallocated `_panel`, which means even after/during the callback, system is still doing something to `_panel`. So we shouldn't nil it out.
(Tested on macOS 0.11, 10.12, 10.13 and 10.14)
Besides, we forgot to update …

Fix Certificate Choose Crash

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

Did some testing together with JK to catch "timeout error" and "not connected to network error" for embedded webview. 
We find that our embedded webview didn't catch them as we only listen to `didFailNavigation` but not `didFailProvisionalNavigation`. Those errors are sent to `didFailProvisionalNavigation` but not `didFailNavigation`.
However, there is no clear documentation telling the difference between them and what errors could be sent to which. I added that delegate but later removed it in my original PR. Seems we do need it.
We want to make sure we only fail the auth flow only necessary. E.g., we don't want to fail due to page javascript error, picture not being able to load, etc.
Apple support ticket has been created to have a better understanding of what error could be sent to …

Catch more errors for embedded web view

---

IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m

WKWebView caching update, applies to both iOS and macOS.
For session cookies, WKWebView’s caching is per process pool. This process pool is created per configuration.
Thus, in order for us to have our SDK treat session as per app launch, we should either have WKProcessPool  or configuration static.
Having config static makes sense as this config really shouldn't change per app launch.
If one wants to change this, they will have to use passed in webview.

Update embedded webview to share process pool

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
IdentityCore/src/oauth2/b2c/MSIDB2CIdTokenClaims.h
IdentityCore/src/oauth2/b2c/MSIDB2CIdTokenClaims.m
IdentityCore/src/oauth2/b2c/MSIDB2COauth2Factory.h
IdentityCore/src/oauth2/b2c/MSIDB2COauth2Factory.m
IdentityCore/src/oauth2/b2c/MSIDB2CTokenResponse.h
IdentityCore/src/oauth2/b2c/MSIDB2CTokenResponse.m
IdentityCore/tests/MSIDAADV2Oauth2FactoryTests.m
IdentityCore/tests/MSIDB2COauth2FactoryTests.m
IdentityCore/tests/integration/MSIDCacheSchemaValidationTests.m
IdentityCore/tests/util/MSIDTestIdTokenUtil.m

Since we're applying more and more B2C specific fixes (e.g. fallback logic when tenantId is not present in the id_token), I separated B2C specific token creation logic, which derives from AAD v2. 
This also fixes B2C access token lookups when tenantId not returned in the id_token.

Separate B2C logic from AAD v2

---

IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
IdentityCore/src/network/request_configurator/MSIDAADRequestConfigurator.m
IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.h
IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m
IdentityCore/src/oauth2/aad_v1/MSIDAADV1Oauth2Factory.m
IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
IdentityCore/src/oauth2/account/MSIDAccount.m
IdentityCore/src/oauth2/b2c/MSIDB2COauth2Factory.m
IdentityCore/src/oauth2/token/MSIDBaseToken.m
IdentityCore/src/oauth2/token/MSIDLegacyAccessToken.m
IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
IdentityCore/src/validation/MSIDAADAuthority.m
IdentityCore/src/validation/MSIDADFSAuthority.m
IdentityCore/src/validation/MSIDAuthority+Internal.h
IdentityCore/src/validation/MSIDAuthority.h
IdentityCore/src/validation/MSIDAuthorityFactory.h
IdentityCore/src/validation/MSIDAuthorityFactory.m
IdentityCore/src/validation/MSIDB2CAuthority.m
IdentityCore/tests/MSIDAadAuthorityCacheTests.m
IdentityCore/tests/MSIDIntuneMAMResourcesCacheTests.m
IdentityCore/tests/integration/MSIDAuthorityIntegrationTests.m
IdentityCore/tests/integration/MSIDCacheSchemaValidationTests.m
IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDWipeDataTelemetryTests.m
IdentityCore/tests/util/NSString+MSIDTestUtil.m

- move MSIDAuthority initializer to internal class to prevent external SDKs from calling MSIDAuthority initializers directly
- change instance methods of MSIDAuthorityFactory to class methods. There seems no good reason to have this as instance methods. Furthermore, there doesn't seem a need to have multiple factory classes of this kind.

Authority factory revisited

---

IdentityCore/src/MSIDOAuth2Constants.h
IdentityCore/src/MSIDOAuth2Constants.m
IdentityCore/src/network/request/MSIDAADAuthorizationCodeGrantRequest.h
IdentityCore/src/network/request/MSIDAADAuthorizationCodeGrantRequest.m
IdentityCore/src/network/request/MSIDAADRefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDAADRefreshTokenGrantRequest.m

Include enrollmentID in token request by refresh token or by auth code, if the authority is not ADFS

Send enrollmentID in acquireToken requests

---

CODEOWNERS

This will include everyone on AppleIdentity to be reviewers of all commits,
This will also include CppIdentity for util and cache changes.

add codeowners to repo

---

IdentityCore/src/MSIDDefaultErrorConverter.m
IdentityCore/src/MSIDErrorConverting.h
IdentityCore/src/util/NSError+MSIDExtensions.h
IdentityCore/src/util/NSError+MSIDExtensions.m
IdentityCore/tests/MSIDErrorTests.m

Allows getting OAuth errors without knowing under which string key they are stored in `userInfo` dictionary.

NSError + OAuth 

---

IdentityCore/src/cache/key/MSIDAppMetadataCacheKey.m
IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m
IdentityCore/tests/MSIDAADOauth2FactoryTests.m
IdentityCore/tests/integration/MSIDCacheSchemaValidationTests.m

*Added schema validation tests for Foci
*Save familyId as blank string instead of nil for non foci clients.

added schema validation tests for FOCI

---

IdentityCore/src/IdentityCore.pch

Allows broker to use msid with the right define "AD_BROKER 1"

Add aadoverride check to the .pch

---

IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.h
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
IdentityCore/src/requests/sdk/adal/MSIDLegacyTokenResponseValidator.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenResponseValidator.m

We will need it in the broker, so we can validate MSIDTokenResult before returning back to the calling app.

Make validateTokenResult public method

---

IdentityCore/src/oauth2/aad_base/MSIDAADIdTokenClaimsFactory.m
IdentityCore/tests/MSIDAADIdTokenClaimsFactoryTests.m

ADAL PR: https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1357

 ID token factory now also checks upn and unique_name claim to determine version

---

IdentityCore/src/oauth2/account/MSIDAccountIdentifier.h
IdentityCore/src/oauth2/account/MSIDAccountIdentifier.m
IdentityCore/src/requests/sdk/adal/MSIDLegacyTokenResponseValidator.m

This is necessary to handle MSIDLegacyIdentifierTypeUniqueNonDisplayableId correctly for ADAL and broker. For MSIDLegacyIdentifierTypeUniqueNonDisplayableId cases, we should verify the result against this unique ID, but not use it for cache lookups. This, it makes sense to add a separate property for it.

Added local account id into account identifier

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/configuration/webview/MSIDWebviewConfiguration.h
IdentityCore/src/network/request/MSIDAADAuthorizationCodeGrantRequest.h
IdentityCore/src/network/request/MSIDAADAuthorizationCodeGrantRequest.m
IdentityCore/src/network/request/MSIDAADRefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDAADRefreshTokenGrantRequest.m
IdentityCore/src/network/request/MSIDAADV1RefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDAADV1RefreshTokenGrantRequest.m
IdentityCore/src/network/request/MSIDAuthorizationCodeGrantRequest.h
IdentityCore/src/network/request/MSIDAuthorizationCodeGrantRequest.m
IdentityCore/src/network/request/MSIDRefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDRefreshTokenGrantRequest.m
IdentityCore/src/oauth2/MSIDOauth2Factory.m
IdentityCore/src/oauth2/MSIDWebviewFactory.m
IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
IdentityCore/src/parameters/MSIDInteractiveRequestParameters.h
IdentityCore/src/parameters/MSIDInteractiveRequestParameters.m
IdentityCore/src/parameters/MSIDRequestParameters.h
IdentityCore/src/parameters/MSIDRequestParameters.m
IdentityCore/src/requests/MSIDBrokerTokenRequest.m
IdentityCore/tests/MSIDAADV1WebviewFactoryTests.m
IdentityCore/tests/MSIDAADV2WebviewFactoryTests.m
IdentityCore/tests/MSIDAADWebviewFactoryTests.m
IdentityCore/tests/MSIDInteractiveRequestParametersTests.m
IdentityCore/tests/integration/ios/MSIDBrokerTokenRequestTests.m
IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m

There’re multiple extra parameters we might need to send to authorize and token endpoints. 
Authorize endpoint:
Extra query parameters are always sent as URL query parameters and there’re parameters that we want to send to both authorize and token endpoint (e.g. slice parameters) or just to authorize endpoint (e.g. domain_hint=XXX).
Token endpoint:
Most of extra parameters need to be sent as part of POST body. Those parameters shouldn’t be sent to authorize endpoint (e.g. itver=1)
However, some extra parameters will only work when sent as part of URL query (e.g. slice=testslice)
Since we need all 3 categories of extra parameters, this PR introduces 3 categories of parameters:
1. MSIDRequestParamaters.extraURLQueryParameters - those parameters will be sent to both authorize and token …

 Modifying extra query params logic to differentiate between authorize and token request extra query parameters

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj

The common authentication library is missing `armv7s` and `arm64e` CPU architectures. This PR adds those libraries to unblock https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/443 which does the same thing for the MSAL library.
Let me know if you need more context and don't hesitate to get in touch.
Cheers!
Benjamin

Add missing CPU architectures

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj

Reverts AzureAD/microsoft-authentication-library-common-for-objc#346.
This change shouldn't have been merged to master, but to dev. Reverting change from master.

Revert "Add missing CPU architectures"

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/network/MSIDHttpRequestProtocol.h
IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m
IdentityCore/src/network/request_configurator/MSIDAADRequestConfigurator.m
IdentityCore/src/network/response_serializer/MSIDResponseSerialization.h
IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDPKeyAuthHandler.h
IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDPKeyAuthHandler.m
IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinConstants.h
IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinConstants.m
IdentityCore/tests/MSIDAADRequestConfiguratorTests.m
IdentityCore/tests/MSIDAADRequestErrorHandlerTests.m
IdentityCore/tests/integration/MSIDAuthorityIntegrationTests.m
IdentityCore/tests/util/MSIDTestURLResponse+Util.m

Added PKeyAuth support for network request.
Question:
1) Currently B2C network request will also have `x-ms-PkeyAuth=1.0` in header, will that be an issue?
2) Does Mac needs PKeyAuth support for token endpoint? If not, needs to change not to send `x-ms-PkeyAuth=1.0` for Mac.
Manual testing has been done to verify the flow for broker.
TODO:
Some unit testing might be needed for `MSIDPKeyAuthHandler.m`, which I don't have time to finish today :P

Support pkeyauth for network request

---

IdentityCore/src/webview/response/MSIDWebOAuth2Response.m
IdentityCore/src/webview/response/MSIDWebviewResponse.h
IdentityCore/src/webview/response/MSIDWebviewResponse.m
IdentityCore/tests/MSIDWebAADAuthResponseTests.m

There's an issue with Facebook+B2C, where Facebook sends a dummy fragment for security reasons. Since MSAL had code to check for fragment first and only look for query parameters, when no fragment is present, the dummy fragment from Facebook broke MSALs. 
Normally, fragment should be never returned for authorization code flows, and is rather used for implicit flows. Therefore, it's questionable why ADALs always checked for fragments first. This change allows SDKs to be checking both fragment and query for authorization code with a preference for the query (since fragment shouldn't actually happen in normal scenario). 
This change will be released as MSAL hotfix once tested.

Fixed issue when Facebook sends a dummy fragment and MSAL is not able to read the auth code

---

IdentityCore/src/webview/MSIDWebviewAuthorization.m

Otherwise, if you start another interactive from completion block, you'd get multiple interactive sessions error (happens in some cases for broker auth)

 Change order of execution for completion block and session clearing

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

In case we use passed in webview, we might run into a race condition between previous controller clearing out navigation delegate and new controller setting it. What happens in most cases is that new controller already started loading some requests, but the previous controller gets its dealloc method called and clears out navigation delegate of the shared webview. This results in passed in webview getting "stuck", since nobody is handling its redirects anymore. 
This is the cause of some broker PRT operations getting "stuck", since it often has a chain of different interactive operations, which all are reusing same WKWebView.

Fixed navigation delegate clear for passed in webview

---

IdentityCore/tests/MSIDAADRequestErrorHandlerTests.m

This test was occasionally failing on random PRs

Fixed failing test testHandleError_whenItIsServerError_shouldRetryRequestAndDecreseRetryCounter

---

IdentityCore/src/network/MSIDHttpRequest.h
IdentityCore/src/network/MSIDHttpRequest.m
IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m
IdentityCore/src/network/error_handler/MSIDHttpRequestErrorHandling.h
IdentityCore/src/network/request/MSIDAADAuthorityMetadataResponseSerializer.m
IdentityCore/tests/MSIDAADRequestErrorHandlerTests.m
IdentityCore/tests/integration/MSIDHttpRequestIntegrationTests.m

Previous logic was wrong, because it was always trying to use AAD token response serializer and return token response (e.g. even for authority validation requests). This caused some issues in broker scenarios, where we didn't return correct error code. 
I changed the logic according to what ADAL has been doing:
1. If 200, parse response
2. If 400 and 401, look for PkeyAuth header. If pkeyauth header is missing, parse response. For response parsing, either use error response serializer if one is provided, or default one. 
3. If 500...599, retry
4. Everything else is unhandled response
I also fixed error case for authority validation response, which was previously working by accident :)

Fixed error http response handling to use correct serializer

---

IdentityCore/src/network/request/MSIDAADAuthorityMetadataResponseSerializer.m
IdentityCore/src/network/request/MSIDAADOpenIdConfigurationInfoResponseSerializer.m
IdentityCore/tests/MSIDAADAuthorityMetadataResponseSerializerTests.m
IdentityCore/tests/MSIDOpenIdConfigurationInfoResponseSerializerTests.m

Fix two issues:
1) `MSIDAADOpenIdConfigurationInfoResponseSerializer.m` is lack of code to handle error case
2) Error code `MSIDErrorAuthorityValidation` is mapped to be `AD_ERROR_UNEXPECTED` rather than `AD_ERROR_DEVELOPER_AUTHORITY_VALIDATION`. 
It is because in error converter, we expect authority validation error to be `MSIDErrorDomain`.

Handle error properly for authority validation

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m

NSTitledWindowMask and NSClosableWindowMask have been replaced by
NSWindowStyleMaskTitled and NSWindowStyleMaskClosable respectively
to match Obj-C naming guidelines, and the old ones are deprecated
as of macOS 10.12.

Update deprecated constants in MSIDWebviewUIController

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.h
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
IdentityCore/src/requests/sdk/adal/MSIDLegacyTokenResponseValidator.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenResponseValidator.m
IdentityCore/tests/MSIDDefaultTokenResponseValidatorTests.m
IdentityCore/tests/MSIDLegacyTokenResponseValidatorTests.m
IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m

Decouple account validation, as it should really be done only on interactive requests.

Account validation revisit

---

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/oauth2/token/MSIDAccessToken.m
IdentityCore/src/oauth2/token/MSIDIdToken.m
IdentityCore/src/oauth2/token/MSIDLegacyAccessToken.m
IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
IdentityCore/src/oauth2/token/MSIDLegacySingleResourceToken.m
IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.m
IdentityCore/src/oauth2/token/MSIDRefreshToken.m
IdentityCore/src/util/NSURL+MSIDExtensions.h
IdentityCore/src/util/NSURL+MSIDExtensions.m
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
IdentityCore/tests/MSIDURLExtensionsTests.m

Fixed logging refresh token in one place
Fixed logging endURL, which might contain authorization code
Log token hash instead of null-notnull

MSID logging fixes

---

IdentityCore/xcconfig/identitycore__common__ios.xcconfig

I noticed that Xcode was printing a warning whenever building for simulator due to additional armv7s architecture. I updated config to only have custom architectures when building for iOS, to avoid this warning.

Update architectures for iOS simulator

---

IdentityCore/src/controllers/ios/MSIDBrokerInteractiveController.m

msal update for release 0.3.0: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/495
broker update for dev: https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/316

Remove deprecated setPersistance for UIPasteboard

---

IdentityCore/xcconfig/identitycore__idlib__ios.xcconfig

- GENERATE_MASTER_OBJECT_FILE is activated to include category symbols into static library.
- armv7s and arm64e are added to ARCH.
- bitcode marker flag is added to support full bitcode on release configuration for real devices.

Change configuration to support AppCenter SDK

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/network/MSIDHttpRequest.h
IdentityCore/src/network/MSIDHttpRequest.m
IdentityCore/src/network/MSIDURLSessionManager.m
IdentityCore/src/network/request_configurator/MSIDAADRequestConfigurator.m
IdentityCore/src/network/request_configurator/MSIDOAuthRequestConfigurator.h
IdentityCore/src/network/request_configurator/MSIDOAuthRequestConfigurator.m
IdentityCore/src/validation/MSIDAuthority+Internal.h
IdentityCore/src/validation/MSIDAuthority.m
IdentityCore/tests/MSIDAADRequestConfiguratorTests.m
IdentityCore/tests/MSIDOAuthRequestConfiguratorTests.m

Fixes for following issues:
1. Translate programmatic cancel error to user cancel for MSAL (otherwise developer using passed in web view would need to look for internal error)
2. Don’t let configuration be editable after Public client is created, so copy it (follows the logic of NSURLSessionConfiguration)
3. Deprecate validateAuthority flag in public client application (Android already removed the flag, so might be a good idea to deprecate it)
4. Removes validateAuthority flag from public client conf (since we’re trying to get rid of the flag, no need to add new place for it)
5. Added known authorities logic for acquire token silent
6. Fixed known authorities logic: previously it was always comparing MSALAuthority with MSIDAuthority which failed
7. Added an exception for AAD authority: …

MSAL API updates bug fixes

---

IdentityCore/src/validation/MSIDB2CAuthority.m
IdentityCore/tests/MSIDB2CAuthorityTests.m

implement copyWithZone separately for B2C authority, without format validation.

Fix on B2C validation copyWithZone

---

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m

*Access token look up was not passing preferred host as the environment and was unable to delete access tokens with intersecting scopes.

Access Token look up cache fix.

---

IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.h

This protocol was neither forward-declared nor included by this header,
making it dependenant on its position in the include order of other files.
This change also sorts the forward-declared classes and symbols in this
file.

Forward-declare MSIDRequestContext in MSIDAccountCredentialCache.h

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDClientTLSHandler.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDPKeyAuthHandler.m
IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.h
IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinUtil.h
IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m
IdentityCore/src/workplacejoin/mac/MSIDWorkPlaceJoinUtil.m
changelog.txt

* Apply hotfix 2.7.9 for wpj cert fix for Mac OS.
* Update ios pkayAuth challenge code to create a pKeyAuth request with empty header incase we do not retrieve a WPJ identity from keychain or if the retrieved identity is corrupt which allows the server to show an Enroll page allowing the developer to register their device.
Previous implementation would fail with error in case the parts of the WPJ identity like the certificate or issuer were missing leaving the developer in an unrecoverable state.

apply hotfix 2.7.9-wpj

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/MSIDOAuth2Constants.h
IdentityCore/src/MSIDOAuth2Constants.m
IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
IdentityCore/src/cache/ios/MSIDKeychainTokenCache.m
IdentityCore/src/cache/key/MSIDLegacyTokenCacheKey.h
IdentityCore/src/cache/key/MSIDLegacyTokenCacheKey.m
IdentityCore/src/cache/token/MSIDCredentialCacheItem.h
IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
IdentityCore/src/configuration/MSIDConfiguration.h
IdentityCore/src/configuration/MSIDConfiguration.m
IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m
IdentityCore/src/oauth2/token/MSIDAccessToken.h
IdentityCore/src/oauth2/token/MSIDAccessToken.m
IdentityCore/src/oauth2/token/MSIDBaseToken.m
IdentityCore/src/oauth2/token/MSIDLegacyAccessToken.m
IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m

This is an update to the previous enrollment ID cache implementation.
This one applies it only for ADAL pieces, MSAL and broker updates will come separately.
- Enrollment ID is an Intune MAM SDK artifact that's used to differentiate app installation and record the fact that MAM policies have been properly enforced. ADAL and MSAL are passing Intune Enrollment ID to all token requests. If True MAM policies have been applied, ESTS won't return an access token without app providing a valid enrollment ID in the request. 
- Enrollment ID enforcement works properly unless broker is involved. When broker is involved, access tokens are cached in a shared location, where any authorized app can access them. However, current cache schema doesn't ensure that apps have a valid enrollment ID and that …

ADAL True MAM CA cache fix

---

IdentityCore/src/util/mac/MSIDKeychainUtil.m

I'm imagining that many macOS developers will try our SDK with no signing enabled during development time. Differently from iOS, where to run app on test device you need to have app signed, many developers will run test apps on macOS without signing.
Current experience without signing is rather bad - we can either fail immediately on public client application creation (which will let them figure out the error faster), or have nil tokenCache and not save anything to cache.
I'm suggesting falling back to bundleId for the teamId part instead when it's not available. That way, developers can play with our SDK in early development stages. When they distribute/ship, they'll need to sign their app so cache sharing will work at that stage. At stage of early development, I think it's fine to have …

[Proposal] Fallback to bundle identifier when teamID is not available

---

IdentityCore/src/cache/metadata/MSIDMetadataCache.m

Small fix of saving item into in-memory metadata cache after reading it, if it wasn't present in metadata in-memory cache before.
Also making sure nobody else is modifying in memory cache while we're removing item from it.

Save metadata cache item to memory after reading from disk

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
IdentityCore/src/cache/token/MSIDAccountCacheItem.m
IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
IdentityCore/src/logger/MSIDLogger+Internal.h
IdentityCore/src/logger/MSIDLogger+Trace.h
IdentityCore/src/logger/MSIDLogger.m
IdentityCore/tests/MSIDLoggerTests.m

* Move MSID_TRACE to a separate header for more effective overriding
* Add function name to logWithLevel: (disabled by default)

Additional logging updates

---

IdentityCore/src/cache/MSIDCacheAccessor.h
IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m

ADAL wasn't passing enrollmentId before when saving broker response

Pass enrollmentId in ADAL when saving broker response

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/webview/background/MSIDBackgroundTaskManager.h
IdentityCore/src/webview/background/MSIDBackgroundTaskManager.m
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/systemWebview/ios/MSIDAuthenticationSession.m
IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m

Looks like on iOS 13 system browser suffers from same "network connection lost" during MFA like embedded webview on previous versions, so added background task for system browser as well.
Additionally, Apple recommends (in its 2019 WWDC background tasks video) starting background task on user action and there's no need to wait until app is about to go to background - apparently it simply signals the system that there's a task going on. This PR changes that as well and starts background task on user action.

Rebuild background task for iOS 13

---

IdentityCore/src/requests/broker/MSIDBrokerCryptoProvider.h
IdentityCore/src/requests/broker/MSIDBrokerKeyProvider.h
IdentityCore/src/requests/broker/MSIDBrokerKeyProvider.m
IdentityCore/tests/integration/ios/MSIDBrokerKeyProviderTests.m

Needed for iOS broker to save any broker keys other than app key.

Update broker key provider to accept custom tag

---

IdentityCore/src/parameters/MSIDRequestParameters.h
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m

Today, developers pass `instance_aware` in extra query parameters. In future, we may want to have an `instance_aware` flag in config file.
In either of the of the above case, we will populate the flag into request parameters.

instance aware fix for broker

---

IdentityCore/src/cache/metadata/MSIDMetadataCache.m
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m

broker: https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/363
MSAL: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/639

Authority fix for account metadata cache

---

IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
IdentityCore/tests/MSIDPkeyAuthHelperTests.m

https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/640
https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/364

fix pkeyauth helper in handling a mismatch certificate issuer

---

IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m

Serhii already fixed this here: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/495/files#diff-dea44e3cfd3aa2007200d8ac56d53847
Applying this fix to current release as we're making parent controller mandatory

Fixed embedded webview when both passed in webview and parent controller are provided

---

IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
changelog.txt

*Hotfix to update update ACL authorization tag to kSecACLAuthorizationDecrypt for adding trusted applications to keychain items on OSX.

Release hotfix 1.3.3 with ACL changes

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDWPJChallengeHandler.m

Client TLS doesn't work in WKWebView on iOS (known issue). Sending certificate in that case makes WKWebView stuck.

Ignore WPJ challenge on iOS

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m
IdentityCore/src/oauth2/MSIDWebviewFactory.m
IdentityCore/src/util/ios/MSIDAppExtensionUtil.m
IdentityCore/src/webview/MSIDMainThreadUtil.h
IdentityCore/src/webview/MSIDMainThreadUtil.m
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDNTLMUIPrompt.m
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDCertificateChooser.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDNTLMUIPrompt.m
IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m
IdentityCore/tests/MSIDMainThreadUtilTests.m

Also fixes warnings on macOS 10.15 and iOS 13 due to ViewController initialization on bf thread.

Check for main thread before dispatching on main thread for ADAL

---

IdentityCore/src/util/NSKeyedArchiver+MSIDExtensions.m
IdentityCore/src/util/NSKeyedUnarchiver+MSIDExtensions.m
IdentityCore/src/util/ios/MSIDKeychainUtil.m
IdentityCore/src/util/ios/UIApplication+MSIDExtensions.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDClientTLSHandler.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDWPJChallengeHandler.h
IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDWPJChallengeHandler.m
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/systemWebview/ios/MSIDAuthenticationSession.m
IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m

Fixed following issues flagged by release automation run:
1. ViewController lookup was broken on non iOS 13 devices when developer passes parentController. Since we would be already presenting authentication controller on top of parent controller, additional presentations (e.g. CBA controller) would not work. 
2. If client receives a WPJ challenge, but doesn't handle it, previous implementation was falling back to Cert auth handler which is incorrect. Applied a fix to not fallback to cert auth handler. 
Additionally, updated TARGET_OS_UIKITFORMAC to TARGET_OS_MACCATALYST (see here https://developer.apple.com/documentation/xcode/creating_a_mac_version_of_your_ipad_app?language=objc)

Fixed viewcontroller lookup and WPJ lookup

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

It doesn't seem to be working and it's causing an occasional assert crash inside WebKit implementation, so reverting the change.

Remove WKWebView stopLoading in cancel

---

IdentityCore/src/cache/MSIDKeychainTokenCache.m

This fixes a bug on 10.15 macOS when iOS keychain is used and wipe data is written. Data protection flag wasn't passed and it was causing a keychain prompt.

Fixed macOS wipe query to use data protection keychain

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.h
IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.m
IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.h
IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
IdentityCore/src/cache/mac/MSIDMacLegacyCachePersistenceHandler.h
IdentityCore/src/cache/mac/MSIDMacLegacyCachePersistenceHandler.m
IdentityCore/tests/MSIDMacACLKeychainAccessorTests.m
IdentityCore/tests/MSIDMacLegacyCachePersistenceHandlerTests.m

Make generic ACL keychain pieces reusable
Allow reusing of existing MSAL ACL code to support backward compatibility with ADAL cache.

Componentize macOS ACL keychain operations

---

IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.m
IdentityCore/tests/automation/shared/MSIDAutomationTestResult.m
IdentityCore/tests/automation/shared/MSIDAutomationUserInformation.m
IdentityCore/tests/automation/ui_app_lib/MSIDClearCookiesTestAction.m
IdentityCore/tests/automation/ui_app_lib/ios/MSIDClearKeychainTestAction.m
IdentityCore/tests/automation/ui_app_lib/ios/MSIDOpenURLAction.m
IdentityCore/tests/automation/ui_app_lib/ui_common/ios/MSIDAutomationPassedInWebViewController.m
IdentityCore/tests/automation/ui_app_lib/ui_common/ios/MSIDAutomationRequestViewController.m
IdentityCore/xcconfig/identitycore__tests__ios.xcconfig
IdentityCore/xcconfig/identitycore__tests__mac.xcconfig

Applying some additional fixes for this PR: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/605

Disable unused variable warnings for tests and fix warnings

---

.github/config.yml

This change will send a message to any PR or an issue that is missing description. The goal is encourage to provide more details in PRs and issues.

Warn on empty issues and PRs

---

IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m

This change sets WKWebView content mode to Mobile for iOS libraries and Desktop for macOS libraries. This is needed to achieve consistency in User-Agent and UI between embedded web view and system webview (ASWebAuthenticationSession uses Mobile as well on iOS).

Set web config content mode

---

.travis.yml
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
IdentityCore/tests/util/network/MSIDTestURLSession.h
IdentityCore/tests/util/network/MSIDTestURLSession.m
build.py

This change sets WKWebView content mode to Mobile for iOS libraries and Desktop for macOS libraries. This is needed to achieve consistency in User-Agent and UI between embedded web view and system webview (ASWebAuthenticationSession uses Mobile as well on iOS).
This is back porting [fix](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/659) to an older ADAL-compatible common core version.

[ADAL-backport] Set default WKWebView content mode

---

IdentityCore/src/controllers/ios/MSIDBrokerInteractiveController.m

This change enables dogfood broker support without app having to do custom configuration. This will ensure that all Microsoft apps have support for it by default.

Enable dogfood authenticator support by default

---

.travis.yml
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/tests/util/network/MSIDTestURLSession.h
IdentityCore/tests/util/network/MSIDTestURLSession.m
build.py

Fixing an issue where setting both parent controller and webview for ADAL 4.0.x results in unexpected behavior (we display an empty navigation controller, and user is blocked).

[ADAL backport] Fix a presentation bug when both parent controller and webview are set

---

IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.h
IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.m

Fixes an issue where account metadata was never updated in Silent SSO extension requests

Set account metadata in silent sso request

---

IdentityCore/src/controllers/broker/MSIDSSOExtensionSignoutController.m

When SSO extension request is complete, there's often a delay before UIWindowScene will become active again. This causes failures for ASWebAuthenticationSession request that follows SSO extension signet request. This PR adds additional logic to wait for scene to become active before calling signout request. 
This is one of the ways to workaround this issue. Please take a look and provide feedback.

Wait for UIScene to become active before calling signout request

---

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.h
IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/parameters/MSIDInteractiveRequestParameters.h
IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultSilentTokenRequest.m
IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
build.py

With the introduction of Google B2B accounts, there’s now a potential conflict between MSA accounts and Google B2B accounts with the same email address. In this scenario, home account id-s for accounts with the same email address will be different, and refresh token for one account won’t work for another account.
The mitigation for developers is to always provide us home account id, and only lookup accounts by home account id. When looking up accounts by displayable id, there’s no guarantee that we get the right account in the above mentioned scenario.  
However, to ensure backward compatibility, and not break SSO, iOS broker should still be able to lookup accounts by only email/upn. In normal scenarios, it will be reliable. In Google B2B scenarios it will be the best effort, and we …

[Broker patch] Fixed account lookups and validation with the same email

---

IdentityCore/src/requests/broker/MSIDBrokerTokenRequest.m
IdentityCore/src/requests/sdk/MSIDBrokerResponseHandler.h
IdentityCore/src/requests/sdk/MSIDBrokerResponseHandler.m
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.h
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
IdentityCore/src/requests/sdk/adal/MSIDLegacyBrokerResponseHandler.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m
IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m
IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m

Make the change to fix a bug, where we didn't save account metadata in MSAL when receives broker response.

Save Account Metadata from Broker Token Response

---

IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.h
IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.m
IdentityCore/tests/integration/MSIDSSOExtensionGetAccountsRequestIntegrationTests.m

This PR enables propagation of returnOnlySignedInAccounts into SSO extension request. Previously this was not set.

Propagate return only signed in accounts flag

---

IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
IdentityCore/src/requests/MSIDSilentTokenRequest.m
IdentityCore/src/requests/MSIDTokenResponseHandler.h
IdentityCore/src/requests/MSIDTokenResponseHandler.m
IdentityCore/src/requests/broker/MSIDSSOTokenResponseHandler.m

SaveSSOStateOnly flag wasn't being propagated correctly for shared devices and therefore more information than needed was saved on shared devices in MSAL cache.

Fixed cache saving for shared devices

---

IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m
changelog.txt

This PR fixes the problem in this line:
`NSMutableDictionary *additionalServer = [[coder decodePropertyListForKey:@"additionalServer"] mutableCopy];`
When additionalServer has NSURL type (which ADAL normally injects), this line will:
1. Fail to deserialize on any version other than iOS 11.2.x. It will also cause any line after this line to fail to deserialize so other properties wouldn't be read correctly.
2. On iOS 11.2.x only, this line will always crash:
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSDictionary initWithObjects:forKeys:]: count of objects (0) differs from count of keys (5)'`
This PR also moves this operation to the very end so that on non iOS 11.2.x, even if it fails, it doesn't cause other critical properties from …

Keyed unarchiver hotfix for 11.2.x iOS versions

---

IdentityCore/src/util/mac/MSIDKeychainUtil.m

Add additional fallback logic for MSIDKeychainUtil.teamId to ensure it always has a non-empty value.
Previously, it will attempt to get the team ID or the bundle ID from the code signing API.
It will now retrieve the bundle ID outside of the code signing API if no team ID is found, and fallback to the process name when there's no bundle ID.

Add additional fallback logic for Team ID for MSIDKeychainUtil

---

IdentityCore/src/util/ios/MSIDAppExtensionUtil.h
IdentityCore/src/util/ios/MSIDAppExtensionUtil.m

Since SSO extension is showing UI, it should be able to handle non-extension safe APIs like openURL. This PR makes sure that common core doesn't treat SSO extension as a standard app extension and allows advanced APIs (for example, Company Portal install links will work now).

Enable openURL in SSO extension

---

IdentityCore/src/controllers/MSIDRequestControllerFactory.m

Previous logic was only passing SSO extension capabilities when SSO extension is present on the device. However, SSO extension capability should represent what SDK is capable of, and not what SDK+device configuration is capable of. Therefore, fixing it to always pass the flag for SSO extension capable SDKs.

Always pass SDK capabilities for brokered requests

---

IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.h
IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m
IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/tests/MSIDAccountCredentialsCacheTests.m

While subclassing from MSAIMSISAccountCeredentialCache in MSAL C++ codebase, I have noticed this typo. It's not a big deal, but people will keep on stumbling upon it. Since you will soon release, this seems like a good opportunity to fix.

Replace *Credetials* with *Credentials* in removeCredetialsWithQuery

---

IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.h
IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.m
IdentityCore/src/cache/metadata/MSIDMetadataCache.h
IdentityCore/src/cache/metadata/MSIDMetadataCache.m
IdentityCore/tests/MSIDAccountMetadataCacheAccessorTests.m
IdentityCore/tests/util/MSIDTestCacheDataSource.m

With the new SSO extension, there're now multiple processes reading and writing to account metadata cache. The problem arises if main app process writes something to account metadata, but SSO extension already has a cache version, or vice versa (or if you have multiple SSO extension processes running). 
Since integrity of data is critical for  account sign-in state and current account state, I made a change to bypass caching when reading those from broker process. Those will still be read from cache for MSAL requests (since it's a single process), and for authorities (since those are not critical and it will cause an extra network request if we miss it, but won't result in incorrect state for the end user).

Bypass cache for account metadata in broker

---

IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m

Changes in common core will log cert authorities and authority in local cert when mismatch detected for PkeyAuth challenges.

Added extra PkeyAuth logging for cert authorities matching

---

IdentityCore/src/cache/MSIDKeychainTokenCache.m
IdentityCore/src/cache/token/MSIDCredentialCacheItem.m

1. Only log "deserialization failed" with verbose level and if item has type attribute (all universal storage components specify type attribute)
2. Don't log "secret not present" when item is not a credential or an unknown credential. This error is only useful when item is a known credential but doesn't include secret.

Fixed too verbose logging for cache item deserialization

---

IdentityCore/src/requests/broker/MSIDSSOExtensionRequestDelegate.m
IdentityCore/tests/integration/MSIDSSOExtensionSignoutRequestIntegrationTests.m

Handle SSO extension "swipe down" cancellation correctly by returning MSAL cancel error. 
Currently it was returning default ASAuthorizationErrorDomain-error, which developers wouldn't handle.

Fixed SSO extension swipe down cancellation case

---

IdentityCore/src/oauth2/aad_v2/MSIDAADV2BrokerResponse.h
IdentityCore/src/oauth2/aad_v2/MSIDAADV2BrokerResponse.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m

Currently V2 broker returns http headers as a dictionary while client MSAL expects encoded string. V1 broker response doesn't have such an issue.
[V2 broker response](https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/blob/dev/ADAuthenticationBroker/ADAuthenticationBroker/ADBrokerAADv2Response.m#L134).
[V1 broker response](https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/blob/dev/ADAuthenticationBroker/ADAuthenticationBroker/ADBrokerAADv1Response.m#L111).
Such a bug will cause a crash as we pass NSDictionary as NSString when we call `[NSString msidIsStringNilOrBlank:]`.
Now V2 broker response handling has been changed to handle both dictionary and string. In the future, we may want to consider adding data type check in `NSString+MSIDExtensions.m`.

Handle http headers in broker response properly

---

IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m

Clearing storage should be a complete reset of the storage structure. On mac, there is a fallback cache (in memory), which is not cleared by the `clearWithContext` method.

Clear in-memory storage on mac

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m
IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m

Convert access denied error to cancelled error on MSAL side.
MSAL PR: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/894
Associated MSAL issue: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/882

Convert access denied error to cancelled

---

IdentityCore/src/MSIDBrokerConstants.h
IdentityCore/src/MSIDBrokerConstants.m

Allow Authenticator app to use any Redirect URI, since Authenticator app will be moving away from the default urn:... Redirect URI.

Removed default urn redirect uri dependency

---

IdentityCore/src/controllers/MSIDRequestControllerFactory.m
IdentityCore/src/parameters/MSIDRequestParameters+Broker.m
IdentityCore/src/requests/broker/MSIDBrokerKeyProvider.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenRequestProvider.m

This change enables MSAL for macOS to call SSO extension
MSAL PR: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/899

Enable SSO extension requests on macOS

---

IdentityCore/src/validation/MSIDAuthority.h
IdentityCore/src/validation/MSIDAuthority.m
IdentityCore/tests/MSIDAADAuthorityTests.m

There's currently a problem when developer declares a custom AAD authority, because it would still go to login.microsoftonline.com to download the aliases instead of using actual authority host. If login.microsoftonline.com is unavailable, this would cause failures for validation.
Since developer explicitly declared authority as known and trusted, it is fine to go to actual authority for validation.
MSAL PR: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/913

Fixed authority validation for developer known authorities

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDNTLMHandler.m
IdentityCore/src/webview/embeddedWebview/ui/MSIDNTLMUIPrompt.h
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDNTLMUIPrompt.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDNTLMUIPrompt.m
IdentityCore/tests/automation/ui_tests_lib/MSIDClientCredentialHelper.m
changelog.txt

Office has reported an occasional crash when NTLM is triggered. 
Looks like it's caused by the situation when app has no key window, which causes WebKit to crash since no prompt is shown. The fix aligns it with Client TLS handler which uses window from the webview instead and seems to be working.

Apply NTLM crash fix to main common core branch

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationBrowserTokenRequest.h
IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationBrowserTokenRequest.m
IdentityCore/src/broker_operation/request/token_request/MSIDBrowserRequestValidating.h
IdentityCore/src/util/NSURL+MSIDAADUtils.h
IdentityCore/src/util/NSURL+MSIDAADUtils.m

This PR includes some preparatory/refactoring work to allow SSO extension to handle all requests, including support multiple different types of handling:
- Handling where we add PRTs
- Handling where we just execute request and add existing cookies
- Handling where we add device assertion headers (not supported yet)
- Handling for SAML/WS-Fed (non OAuth2) requests (not supported yet)
The main change is in broker where there're multiple possible controllers that can handle browser requests and not all controllers have to lookup PRTs. 
Request filtering got also moved to broker to allow more complex handling in the future.

Prepare SSO extension to handle all requests

---

IdentityCore/src/MSIDConstants.h
IdentityCore/src/controllers/broker/MSIDSSOExtensionInteractiveTokenRequestController.m
IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.m
IdentityCore/src/requests/broker/MSIDSSOExtensionGetDeviceInfoRequest.m
IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.m
IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m

Fix Build Break for Anaheim. 
1. As Anaheim's build system is using -std=c11 so that the usage of the typeof will break their build.
2. Anaheim team has issue with adding IdentityCore.pch into pre-compile. So added #include in MSIDConstant.h to help them avoid build break 
- [X ] Bug fix
- [X ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)
An open question: Is that possible to switch language mode in order to avoid future breaks?

Fix Build Break for Anaheim as consumer of OneAuth

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDNTLMHandler.m
IdentityCore/src/webview/embeddedWebview/ui/MSIDNTLMUIPrompt.h
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDNTLMUIPrompt.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDNTLMUIPrompt.m
IdentityCore/tests/MSIDLoggerTests.m

Office has reported an occasional crash when NTLM is triggered. 
Looks like it's caused by the situation when app has no key window, which causes WebKit to crash since no prompt is shown. The fix aligns it with Client TLS handler which uses window from the webview instead and seems to be working.

Fixed NTLM crash when app has no keywindow

---

IdentityCore/src/MSIDExternalAADCacheSeeder.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
IdentityCore/tests/integration/MSIDExternalAADCacheSeederIntegrationTests.m

There's is a macOS cache compatibility issue between ADAL and MSAL.
Here're the repro steps:
1. Signin in MSAL app (uses shared cache - RT with deviceId). 
2. Signout.
3. Signin in MSAL app again (doesn't use shared cache because account is marked as signed out)
4. Acquire new token with less claims (RT without deviceId).
5. Write RT without deviceId to both caches as FOCI token. 
6. ADAL app tries to use RT. First it requests a token for a resource that doesn't require deviceId. 7. Request succeeds and overrides FRT and RT in ADAL cache.
8. ADAL app trie to use RT to request a token for a resource that requires deviceId. Request fails.
Possible solutions:
Option 1: Don't override a FOCI token in legacy ADAL cache if it already exists 
Option 2: Only override FOCI token in legacy ADAL …

Protect legacy macOS cache (#ADO1001313)

---

IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationSignoutFromDeviceRequest.h
IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationSignoutFromDeviceRequest.m
IdentityCore/src/controllers/broker/MSIDSSOExtensionSignoutController.m
IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.h
IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.m
IdentityCore/tests/MSIDBrokerOperationSignoutFromDeviceRequestTests.m
IdentityCore/tests/integration/MSIDSSOExtensionSignoutRequestIntegrationTests.m

Add support to pass a flag to clear SSO extension cookies in the signout operation explicitly.
This is needed for the broker host app.

Support clearing SSO extension cookies

---

IdentityCore/tests/MSIDAADOauth2FactoryTests.m
IdentityCore/tests/MSIDAADV1Oauth2FactoryTests.m
IdentityCore/tests/MSIDAADV2Oauth2FactoryTests.m
IdentityCore/tests/MSIDB2COauth2FactoryTests.m
IdentityCore/tests/MSIDBrokerOperationInteractiveTokenRequestTests.m
IdentityCore/tests/MSIDBrokerOperationSilentTokenRequestTests.m
IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m
IdentityCore/tests/integration/MSIDInteractiveControllerIntegrationTests.m
IdentityCore/tests/integration/MSIDLegacyTokenCacheIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDBrokerInteractiveControllerIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m
IdentityCore/tests/mac/MSIDMacKeychainTokenCacheTests.m
IdentityCore/tests/util/MSIDTestIdentifiers.h

MSAL C++ has added a sanity check in our account constructor which requires UID and UTID to both be GUIDs.
Unfortunately, this has an impact on tests. Since we would like to continue running obj-c tests, I've cleaned up (some) of the tests to use GUID identifiers.

Change test constants to use a GUID for home account

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/cache/crypto/MSIDAssymetricKeyGenerating.h
IdentityCore/src/cache/crypto/MSIDAssymetricKeyGeneratorFactory.h
IdentityCore/src/cache/crypto/MSIDAssymetricKeyGeneratorFactory.m
IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.h
IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.m
IdentityCore/src/cache/crypto/MSIDAssymetricKeyLookupAttributes.h
IdentityCore/src/cache/crypto/MSIDAssymetricKeyLookupAttributes.m
IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.h
IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m
IdentityCore/src/cache/crypto/MSIDAssymetricKeyPairWithCert.h
IdentityCore/src/cache/crypto/MSIDAssymetricKeyPairWithCert.m
IdentityCore/src/cache/crypto/mac/MSIDAssymetricKeyLoginKeychainGenerator.h
IdentityCore/src/cache/crypto/mac/MSIDAssymetricKeyLoginKeychainGenerator.m
IdentityCore/tests/MSIDAssymetricKeychainGeneratorTests.m

Both AT POP and PRT v3 need a common interface to handle keys.
Submitting a common interface that both features can use.

Added common interface for assymetric key generation

---

IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
IdentityCore/tests/MSIDPkeyAuthHelperTests.m

Certain versions of ADFS send PkeyAuth certificate authorities URL encoded.
This is correct as per spec at https://docs.microsoft.com/en-us/openspecs/windows_protocols/MS-PKAP/f2980059-9437-4cb6-baf2-6b8325158b21 showing a sample response.
It means that PKeyAuth response handling is broken in the iOS broker when challenge comes from ADFS side. Fixing handling as per spec:
`cert-authorities: A semicolon-delimited list of URL-encoded issuer names. The client must prove possession of the private key of a certificate that was issued by one of these issuers.`
Will require full broker test pass to verify.

[ICM] Fixed PkeyAuth when ADFS challenge is URL encoded

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m

ICM reported that MSAL interactive token acquisition hangs when certificate challenge is received. Same flow works in Microsoft Authenticator app. 
Code analysis revealed that MSAL never sets redirectUri when creating a certificate handling challenge, which causes the flow to hang. Submitting a fix that sets redirectUri to the uri in the request when custom logic for URL swapping is not applied.  
Will require manual testing of CBA in both broker and MSAL on iOS.

[ICM] Fixed CBA handling in MSAL

---

IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.h
IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.m
IdentityCore/src/parameters/MSIDRequestParameters.m
IdentityCore/tests/MSIDPrimaryRefreshTokenTests.m

As the first step to support seamless SSO in broker, we'll try to refresh PRT every couple of hours after using PRT. In order to track last PRT usage and expiry time, PRT will now utilize expiresOn and cachedAt fields. This PR includes PRT schema updates needed to support first phase of PRT refresh.

Support PRT refresh

---

.travis.yml
IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/tests/mac/MSIDMacKeychainTokenCache+Test.h
IdentityCore/tests/mac/MSIDMacKeychainTokenCacheTests.m
IdentityCore/tests/util/MSIDApplicationTestUtil.m

The change is to remove items in memory and keep those items in local cache(storage)
This PR is to address a unit test failure on 10.15 and above where we should not be able to get local cached items. However, the logic of query items is a combination of getting items from both local and memory which fails the unit test. This PR will help to remove the items in memory only to prove we cannot get items from local cache

fix a failure unit test when running on 10.15

---

IdentityCore/src/webview/embeddedWebview/MSIDAADOAuthEmbeddedWebviewController.m
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
IdentityCore/src/webview/embeddedWebview/ui/MSIDWebviewUIController.h

Fix embedded webview response handling to set the complete flag only once in endWebAuth function. Setting this flag in multiple places was causing the webview to hang indefinitely without returning the response.

Fixed issue with webview cancellation

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m

When using ASWebAuthenticationSession for certificate based auth, we don't need to change Redirect URI anymore so we can use current URL that requested the cert challenge.
This will help user to avoid additional username entry and take them directly to their on prem page. 
Note that this is the way it used to work with ADAL, and got regressed with MSAL.

Use correct request URL when using CBA with Auth Session

---

IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenRequestProvider.h

There're cases where account metadata update is unneeded (e.g. PRT flows).
Hence, making account metadata accessor optional.

Make account metadata accessor optional

---

IdentityCore/src/MSIDBrokerConstants.h
IdentityCore/src/MSIDBrokerConstants.m
IdentityCore/src/MSIDJsonSerializer.m
IdentityCore/src/broker_operation/response/MSIDDeviceInfo.h
IdentityCore/src/broker_operation/response/MSIDDeviceInfo.m
IdentityCore/src/util/NSJSONSerialization+MSIDExtensions.m
IdentityCore/tests/MSIDDeviceInfoTests.m

Adding additional field for the SSO extension protocol that allows passing additional information/settings.
This is needed to allow Authenticator read settings from SSO extension.

Support reading broker feature flags

---

IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.h
IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m
IdentityCore/tests/MSIDAssymetricKeychainGeneratorTests.m

Add OEAP SHA1 decryption to AssymetricKeyPair

Add OEAP SHA1 decryption to AssymetricKeyPair

---

IdentityCore/src/cache/crypto/mac/MSIDAssymetricKeyLoginKeychainGenerator.m
IdentityCore/src/cache/key/MSIDDefaultCredentialCacheKey.m
IdentityCore/src/cache/token/MSIDCredentialCacheItem.m

The macOS leychain < 10.15 had a bug for AT pop tokens. This PR adds a fix for it.
- [*] Bug fix
- [*] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

Cache fix for pop tokens in login keychain.

---

IdentityCore/src/cache/MSIDKeychainTokenCache.m
IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.m
IdentityCore/src/cache/metadata/MSIDMetadataCache.h
IdentityCore/src/cache/metadata/MSIDMetadataCache.m
IdentityCore/src/cache/metadata/MSIDMetadataCacheDataSource.h
IdentityCore/src/cache/metadata/accountMetadata/MSIDAccountMetadataCacheItem.h
IdentityCore/src/cache/metadata/accountMetadata/MSIDAccountMetadataCacheItem.m
IdentityCore/tests/MSIDAccountMetadataCacheAccessorTests.m
IdentityCore/tests/MSIDAccountMetadataCacheItemTests.m
IdentityCore/tests/integration/ios/MSIDKeychainTokenCacheIntegrationTests.m
IdentityCore/tests/mac/MSIDMacKeychainTokenCacheTests.m
IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.h
IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.m

Added API to `MSIDAccountMetadataCacheAccessor` to remove account metadata by home account id. Such an API will be used by broker.

Remove Account metadata when Remove Account in Broker

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h
IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m

This is a follow-up PR for this PR: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/775
Instead of enabling using last request URL for all cert based authentication requests, this PR enforces an additional flag.
This will allow us to test out the feature and rollout through various releases with a feature flag and minimize the risk.

Revert CBA URL change

---

IdentityCore/src/requests/sdk/MSIDBrokerResponseHandler.m
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m

In case the Pop request from MSAL is corrupted, fallback broker to use Bearer Scheme.
Related PRs:
[MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/996)
[Broker](https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/542)

In case the Pop request from MSAL is corrupted, fallback broker to use Bearer Scheme

---

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m

An issue came from Yammer where a developer was not able to use an access token in the cache when acquiring token silently from a guest tenant. The account had a different UPN in the guest tenant than it did in its home tenant, which caused the account to not be found when creating the access token result from cache. When looking up an account in the cache, only the homeAccountID is necessary if the account has been used with MSAL, while using username in the lookupAccountIdentifier is only necessary for ADAL and for migrating from ADAL to MSAL.
The previous fix for this issues caused a regression, so the is the resulting new fix. Since the fix is within the default account cache accessor, it should not affect ADAL functionality.

New fix - Guest account with different UPN can't find cached access token

---

IdentityCore/src/MSIDOAuth2Constants.h
IdentityCore/src/MSIDOAuth2Constants.m
IdentityCore/src/cache/token/MSIDCredentialCacheItem.h
IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.h
IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.m
changelog.txt

Current broker SDK uses a hardcoded PRT refresh interval of 4 or 12 hours. That might be insufficient if tenant has configured PRT to be valid for a much shorter period of time like 4 hours. 
In order to correctly calculate PRT refresh interval related to PRT lifetime, introduce a cached property for PRT lifetime.

Store PRT expires in time

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/cache/crypto/MSIDSymmetricKey.h
IdentityCore/src/cache/crypto/MSIDSymmetricKey.m
IdentityCore/tests/MSIDSymmetricKeyTests.m

Symmetric key support for creating a verify signature and key derivation without AES-GCM support, which can come in a follow up item since its not supported natively in objective c.

Symmetric key support for creating a verify signature and key derivation

---

IdentityCore/tests/mac/MSIDMacKeychainTokenCacheTests.m
changelog.txt

Fix a test bug in MSIDMacKeychainTokenCacheTests.m where, if the loginKeychainEmpty key is not reset, then the test will fail, since `_dataSource` will be nil.

Fix a test bug in MSIDMacKeychainTokenCacheTests.m

---

IdentityCore/src/MSIDJsonSerializableFactory.m
IdentityCore/src/oauth2/MSIDOauth2Factory.m
IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
IdentityCore/src/oauth2/token/MSIDRefreshToken.m
changelog.txt

Clean up SSO extension logs that are too verbose.
Currently we log following on each response from SSO extension:
```
[W-AH][MSAL] TID=168600 MSAL 1.1.4 iOS 13.5.1 [2020-08-05 01:19:59] Creating Error with description: Failed to create object from json, class: MSIDAuthority wasn't registered in factory under provider_aad_v2 key.¬
TID=168600 MSAL 1.1.4 iOS 13.5.1 [2020-08-05 01:19:59] Creating Error with description: Failed to create object from json, class: MSIDTokenResponse wasn't registered in factory under provider_aad_v2 key.¬
TID=168600 MSAL 1.1.4 iOS 13.5.1 [2020-08-05 01:19:59] Failed to init id token claims in MSIDAADV2TokenResponse, error: Masked(null)
TID=168600 MSAL 1.1.4 iOS 13.5.1 [2020-08-05 01:19:59] Trying to initialize refresh token when missing refresh token field
``` …

SSO extension log cleanup

---

IdentityCore/src/network/request/MSIDAADRefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDAADRefreshTokenGrantRequest.m
IdentityCore/src/network/request/MSIDAADV1RefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDAADV1RefreshTokenGrantRequest.m
IdentityCore/src/network/request/MSIDRefreshTokenGrantRequest.h
IdentityCore/src/network/request/MSIDRefreshTokenGrantRequest.m
IdentityCore/src/oauth2/MSIDOauth2Factory.m
IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
IdentityCore/tests/integration/MSIDExternalAADCacheSeederIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m
IdentityCore/tests/util/MSIDTestURLResponse+Util.m
changelog.txt

Make changes to send redirect uri to refresh token grant flow. With such parameter being sent, it helps server to identify client types (public client or confidential client) correctly. It is addressing [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1020).

Send redirect uri for refresh token grant flow

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/util/mac/MSIDRedirectUriVerifier.m
IdentityCore/tests/mac/MSIDRedirectUriVerifierMacTests.m
changelog.txt

Allow bypassing redirect uri on macOS. This is needed to allow macOS CP app to add account for SSO. 
This flag is already in use by iOS.

Support bypassing macOS redirectUri validation

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDClientTLSHandler.m
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinConstants.h
IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinConstants.m
changelog.txt

On iOS, passing in the x-ms-PkeyAuth field in the HTTP header doesn't work for the scenario where the user is first directed to Microsoft sign-in page and then redirected to another adfs sign in page.
ex:
User opens ADAL test app and then attempts to acquire token using OneDrive or Office profile.
user is redirected to Office356 login page (login.microsoft.com)
3)user types in the user id - test@unisys.com
4)user is then redirected to (adfs.unisys.com)
Embedded webview is initialized during step 1, and "x-ms-PkeyAuth" field is added to the HTTP request header.
However, when the user makes it to step 4, "x-ms-PkeyAuth" field is lost in the HTTP header from the server side by then.
This issue can be addressed by appending "PKeyAuth/1.0" keyword to the User Agent string in the HTTP header …

PKeyAuth UserAgent String + WPJChallenge disabling on iOS

---

IdentityCore/src/cache/token/Matchers/MSIDAccountCacheItem+MSIDAccountMatchers.m
IdentityCore/src/oauth2/account/MSIDAccountIdentifier.m
IdentityCore/tests/MSIDAccountCredentialsCacheTests.m
IdentityCore/tests/MSIDAccountIdentifierTests.m
IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m
changelog.txt

In current cache lookups not all account identifiers where properly normalized.
From looking at an issue reported by customer, I've noticed that Teams is passing home account id in following format "uid.UTID". This seems to happen because another Office app is writing account to external cache in this format. 
What is happening is that access token lookups succeeds, but account lookup fails. Therefore, we'll always make a network call to the server and after a few calls request will be dropped with the "loop detected error". After that happens, Teams will reach out to SSO extension and that will use PRT to get new token. That will also be marked as "looping" after a few tries. 
In the end of the loop, Teams will be unable to get a token.

Normalize home account id in cache lookups

---

IdentityCore/src/logger/MSIDLogger.m
IdentityCore/src/logger/MSIDLoggerConnecting.h
IdentityCore/tests/MSIDLoggerTests.m

We need to disable logger's queue when we integrate with MSAL CPP logger.

Add a flag to disable logger queue

---

IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.h
changelog.txt

Remove obsolete TODO that causes OneAuth-MSAL automation open bugs.

Remove obsolete todo comment

---

IdentityCore/src/webview/embeddedWebview/ui/MSIDWebviewUIController.h
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
changelog.txt

Added public APIs on iOS & MacOS to generate custom WKWebViewConfiguration with PKeyAuth UserAgent Keyword.

Public APIs to generate custom WKWebViewConfiguration with PKeyAuth UserAgent Str

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.m
IdentityCore/src/cache/crypto/MSIDAssymetricKeyLookupAttributes.m
IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.h
IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m
IdentityCore/src/util/MSIDJWTHelper.m
IdentityCore/src/util/NSData+JWT.h
IdentityCore/src/util/NSData+JWT.m
IdentityCore/src/util/NSData+MSIDExtensions.m
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
changelog.txt

This PR reverts the signing code change I made which used SecKeyVerifySignature in my previous PR as it breaks cpp build. SecKeyVerifySignature was always using sha256 hashing and cpp was relying on this method to do sha1 hashing as well. 
The files NSData+JWT is the same code we had before which used SecKeyRawSign. Added these files back again unchanged. Deleting these files was breaking cpp build.
Also exposed the properties like, keyModulus and keyExponent of public key as it was before because cpp is relying on these properties being publicly exposed.

Revert signing code to fix cpp build

---

azure_pipelines/verify_msalcpp_per_pr_ios.yml
azure_pipelines/verify_msalcpp_per_pr_mac.yml

Disabled the Test running iOS and macOS on MSAL CPP. Our change in common core is just a subset of the whole Apple related test in MSAL C++ which is flaky for a while. Make compiling only just in case it will cause unnecessary blockers, and we can save some time as well

remove test when running cpp pipeline

---

IdentityCore/src/cache/token/MSIDCredentialCacheItem.m

Fix an error in the comparison function for requested claims.
This bug crept in due to a misunderstanding during the PR process of the original feature work PR. MSAL C++ doesn't specify a ClientIDMatching Option for AT lookups and thus default to exact string match, not SuperSet. As such, we never hit this codepath.
Nevertheless, claims are unrelated to client ID's so the current location doesn't make a lot of sense.

Fix for requested claims comparison function

---

.travis.yml
IdentityCore/tests/MSIDLastRequestTelemetryTests.m
IdentityCore/tests/MSIDLoggerTests.m
IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
scripts/update_xcode_config_cpp_checks.py

Added a new script to insert warning configurations per [this PR](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/814) and prevent warnings been introduced into cpp layer. The configuration changes only happens in pipelines (Travis) and will not propagate into broker or MSAL Objc

Adding warning checks on pipelines only

---

IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m

We have recently identified an issue with ADFS v4.0 that prevents PKeyAuth Challenge from being handled properly.
Disable it for now to unblock customers until ADFS team finishes investigating the issue

Disable PKeyAuth on ADAL

---

IdentityCore/src/util/ios/MSIDAppExtensionUtil.h
IdentityCore/src/util/ios/MSIDAppExtensionUtil.m

Parent PR for context:
https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/645

Broker save the session to local cache when in background state

---

IdentityCore/src/util/NSDictionary+MSIDExtensions.m
IdentityCore/src/util/NSString+MSIDExtensions.h
IdentityCore/src/util/NSString+MSIDExtensions.m
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
IdentityCore/tests/MSIDStringExtensionsTests.m
IdentityCore/tests/MSIDWebviewFactoryTests.m

When PKeyAuth is enabled through UA string, Client-side PKeyAuth handler creates a PkeyAuth header and then responds to the server-side challenge.
There was a bug in the client-side code, specifically in the msidEncodeStringFromDictionary API in the MSID category method for the NSString object.
This API constructs a URL string from the key-value pairs contained in the input dictionary.
ex: https://fs.msidlab4.com/adfs/ls/?&key1=value1&key2=value2&......&keyn=valuen.
This input dictionary is constructed from the submitURL parameter contained within the PKeyAuth request URL returned by the server. this submitURL field contains the information about the endpoint to which the PKeyAuth response must be submitted.
This is how the flow goes:
Client submits PKeyAuth request through the UA string …

ADFS PKeyAuth fix for ADAL

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/IdentityCore.pch
IdentityCore/src/util/MSIDAppExtensionUtil.h
IdentityCore/src/util/ios/MSIDAppExtensionUtil.m
IdentityCore/src/util/mac/MSIDAppExtensionUtil.m
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

Currently in embedded web view, links with target=_blank (web links that should open in a new window/tab) are ignored by WKWebView since it is an embedded web view. These links should be handled by opening in the default browser. Links that can be opened via URL schemes on the device need to also be handled. This is required during MFA setup since the link to activate MFA code looks like this : microsoft-authenticator://activateMFA?code=
This PR adds logic to handle these types of links in embedded web view by opening them in browser or application that supports the URL's scheme.
This is for ADAL common core update.

Added logic for handling external links that open in new tab for embedded web view.

---

IdentityCore/src/requests/MSIDSilentTokenRequest.m
IdentityCore/src/validation/MSIDAADAuthority.m
IdentityCore/src/validation/MSIDAuthority.h
IdentityCore/src/validation/MSIDAuthority.m
IdentityCore/tests/MSIDAADAuthorityTests.m
IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m
changelog.txt

Most of the changes are in MSAL repo. Changes in common core here is to make sure we do not send RT to a wrong cloud.
The reason we could send RT to wrong cloud is:
server open id configuration endpoint supports url `login.microsoftonline.com/<CHINA_CLOUD_TENANT_ID>/v2.0/.well-known/openid-configuration`, where it will return the correct token endpoint, i.e. `login.partner.microsoftonline.cn`. In such a case, RT issued by WW cloud could be sent to China cloud.
Logic is added to handle such mismatch more actively (only for AADAuthority). UT will be added later.

Cross cloud support

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

When links with target=_blank ( anchor links that open in new tab) are clicked in an embedded webview, notifyWebAuthDidFinishLoad must be called so that any remaining actions that must be performed by observer are performed once navigation is complete.
Eg : ASDKBrokerViewController in Authenticator app initializes a UIActivityIndicator spinner on loading the web content. It relies on observing the notification mentioned to stop the spinner animation.

Calling notifyWebAuthDidFinishLoad when external links are clicked

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

For ADAL embedded webview,
When links with target=_blank ( anchor links that open in new tab) are clicked in an embedded webview, notifyWebAuthDidFinishLoad must be called so that any remaining actions that must be performed by observer are performed once navigation is complete.
Eg : ASDKBrokerViewController in Authenticator app initializes a UIActivityIndicator spinner on loading the web content. It relies on observing the notification mentioned to stop the spinner animation.

Notify observer for WebAuthDidFinishLoad when opening external links in embedded webview

---

IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.m

Latest broker that supports PRT refresh has reduced PRT expiry to 15%. However, we still have PRT expiry causing 15% of prompts. Adjusting the frequency to be a bit more aggressive (instead of expiry/10, expiry/30 - so if PRT expires in 14 days, we'll now try to refresh every 11 hours. This is still less aggressive than Windows (every 4 hours)).

Increase PRT refresh frequency

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
IdentityCore/tests/MSIDWebviewDefaultConfigurationSettingsTest.m

Removed PKeyAuth from the UA string on MacOS, and also added a regression test.

Remove PKeyAuth from MacOS and add regression test.

---

IdentityCore/src/MSIDBrokerConstants.h
IdentityCore/src/MSIDBrokerConstants.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m

removing MSID_BROKER_IS_PERFORMING_CBA since alternate way to check broker flow during SSO was discovered
- [ x ] Bug fix
- [ x ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

Removing MSID_BROKER_IS_PERFORMING_CBA

---

IdentityCore/src/MSIDCache.m
IdentityCore/src/cache/mac/MSIDMacCredentialStorageItem.m
IdentityCore/src/cache/metadata/MSIDMetadataCache.m
IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m
changelog.txt

There are reports that deadlock could happen in MSAL if too many threads are calling MSAL APIs at the same time. 
After some investigation, we found that deadlock could happen if there are more than 64 threads calling MSAL APIs.
**Root cause:**
There is a limit regarding how many GCD threads we can create for an app (limit is 64 according to my testing, also found reference here https://www.oreilly.com/library/view/high-performance-ios/9781491910993/ch04.html). Such a limitation could cause deadlock in our code. E.g., if a `dispatch_barrier_async` block is at the front of a queue and waiting to be executed, it will block all other `dispatch_sync` blocks. Image there are 64 threads (limit is hit) waiting at `dispatch_sync`, then no more thread can be created to execute the …

Fix Possible Deadlock caused by Thread Explosion

---

IdentityCore/src/controllers/MSIDSilentController.m
IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
IdentityCore/src/webview/background/ios/MSIDBackgroundTaskManager.h
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/systemWebview/session/MSIDSystemWebviewController.m

We have customers reporting if they have MFA and put Authenticator app into background for 2FA, they are getting "The network connection was lost." or "The Internet connection appears to be offline." error from Authenticator app and cannot finish the whole authentication. 
When putting app into background, for interactive request, app will finish the authcode process first and then end the background task. At that moment, the app will be suspended. When reopen the app after 2nd FA is done, the AuthCode-token exchange flow will continue, however server drops the connection (not sure why) already and caused the network error.
Instead of closing the background task when the web view (both ASWebSession and WKWebView ) is dismissed, we will stop the task once the whole interactive/silent …

Extend backgroud tasks for silent and interactive request

---

IdentityCore/src/throttling/cache/MSIDLRUCache.h
IdentityCore/src/throttling/cache/MSIDLRUCache.m
IdentityCore/tests/MSIDLRUCacheTest.m

The issue was that for the last test case, waitforexpectation was outside of the block statement. 
silly bug :(

LRU Cache - Last unit Test Fix

---

IdentityCore/src/throttling/cache/MSIDLRUCache.h
IdentityCore/src/throttling/cache/MSIDLRUCache.m
IdentityCore/tests/MSIDLRUCacheTest.m

There was a minor bug in the last unit test case for the MSIDLRUCache class, where expectation fullfill was being done outside of the async block, resulting in intermittent test failures due to inaccurate synchronization.

fixed a minor bug in MSIDLRUCache last unit test

---

IdentityCore/src/cache/MSIDKeychainTokenCache.m
IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m
IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.m
IdentityCore/src/cache/token/MSIDAccountCacheItem.m
IdentityCore/src/logger/MSIDLogger+Internal.h
IdentityCore/src/logger/MSIDLogger.h
IdentityCore/src/logger/MSIDLogger.m
IdentityCore/src/logger/MSIDLoggerConnecting.h
IdentityCore/src/logger/MSIDMaskedHashableLogParameter.m
IdentityCore/src/logger/MSIDMaskedLogParameter.h
IdentityCore/src/logger/MSIDMaskedLogParameter.m
IdentityCore/src/logger/MSIDMaskedUsernameLogParameter.m
IdentityCore/src/oauth2/account/MSIDAccount.m
IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
IdentityCore/src/requests/MSIDOIDCSignoutRequest.m
IdentityCore/src/requests/broker/MSIDBrokerTokenRequest.m
IdentityCore/src/requests/sdk/adal/MSIDLegacyTokenResponseValidator.m
IdentityCore/src/util/NSDictionary+MSIDLogging.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDPKeyAuthHandler.m
IdentityCore/src/webview/operations/MSIDWebOpenBrowserResponseOperation.m
IdentityCore/tests/MSIDLoggerTests.m
IdentityCore/tests/MSIDMaskedLogParameterTests.m
IdentityCore/tests/MSIDMaskedUsernameLogParameterTests.m
IdentityCore/tests/util/MSIDTestLogger.m
changelog.txt

MSAL and broker provide logging callbacks that assist in diagnostics. By default the library will not return any messages with any user or organizational information. However, this might make diagnosing issues difficult.
The most sensitive information is EUII (things like upn, name, email etc). 
This PR introduces a new logger flag and macro that allows masking only EUII, while keeping EUPI and OII intact. 
When both piiEnabled is set to YES, and maskEUII is set to YES, MSAL logs will still include OII (organization identifiable information), and EUPI (end user pseudonymous identifiers), but MSAL will try to exclude and/or mask any EUII (end user identifiable information) like UPN, username, email from its logs.
This flag has no effect when piiEnabled is set to NO.
Default value is NO.

Mask EUII logs

---

IdentityCore/src/cache/MSIDKeychainTokenCache.m

Current logic will crash the code if process is missing a bundle identifier. 
Applying a fix to fallback to process name, or empty string if it's missing.
Crash reported by Jamf on macOS.

Handle missing bundle identifier when writing wipe data to keychain

---

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/oauth2/MSIDOauth2Factory.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenResponseValidator.m
IdentityCore/tests/MSIDOauth2FactoryTests.m
IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m

Support for scenarios where `access_token` is not returned (only `id_token` / `refresh_token` is returned). Changed to make it an error if both `access_token` and `id_token` are not returned.
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/852

Support for scenarios where access_token is not returned

---

IdentityCore/src/intune/MSIDIntuneApplicationStateManager.h
IdentityCore/src/intune/MSIDIntuneApplicationStateManager.m
IdentityCore/src/requests/MSIDSilentTokenRequest.m
IdentityCore/src/validation/MSIDAADAuthority.m
IdentityCore/tests/MSIDIntuneMAMResourcesCacheTests.m
IdentityCore/tests/mocks/MSIDAuthorityMock.m

Removed input param in isAppCapableForMAMCA to make it reusable in CPP later on

Remove input param to make the method reusable in CPP, added tests

---

IdentityCore/tests/MSIDAccountCacheItemTests.m

In the past, we disabled these tests in MSAL C++ because of the account type discrepancy issue. Currently, after resolving that problem, we are willing to run these tests in our CI. 
And there are three bugs which will fail the tests on our side:
1. The home_account_id should be in UUID format.
2. MSAIAccountInternal requires nonnull values, so we need to add all of the values while comparing the accountCacheItem with expectedDictionary.
3. localAccountId, realm, and username cannot be nil while creating an account.
According to these bugs, I made this PR. If there is any problem, please let me know.

Fix bugs in MSIDAccountCacheItemTests from MSAL C++

---

IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
changelog.txt

This is a hot-fix to revert a logic of comparing requestedClaims back to [this one](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/840#discussion_r486694061)

revert the change on requetClaims lookup logic

---

IdentityCore/src/util/ios/MSIDRedirectUriVerifier.m
IdentityCore/src/webview/response/MSIDCBAWebAADAuthResponse.m
IdentityCore/tests/MSIDCBAWebAADAuthResponseTests.m
IdentityCore/tests/MSIDRedirectUriVerifierTests.m
changelog.txt

Fix parsing of the redirect URI in CBA flow when the server returns URL with the hashtag.

Fix redirect uri parsing in cba flow

---

IdentityCore/src/telemetry/request_telemetry/MSIDCurrentRequestTelemetrySerializedItem.m
IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetrySerializedItem.m
changelog.txt

ESTS has recently introduced a change to truncate telemetry strings in the "x-client-current-telemetry" and "x-client-last-telemetry" headers if they exceed 100 and 350 bytes respectively (the previous max limit for each string was 4kB). While we currently have nothing that will break if telemetry data is truncated on the server-side, it is useful to update the limits in our code so we are not sending excess data in our network requests. Also, we have code that sends telemetry data that has been cut off due to size during serialization in subsequent requests, so that can preserve the data that the server would truncate.
The last request serialization object will now override the telemetry string size methods in order to keep its own size limit value.

Update telemetry string size limit to ESTS's new limits

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
changelog.txt

add about:srcdoc into policy navigation in Oauth2Webview to fix Oauth2 flow in some providers (e.g facebook login).

add about:srcdoc into policy navigation in Oauth2Webview

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/requests/MSIDSilentTokenRequest.m
IdentityCore/src/telemetry/request_telemetry/MSIDCurrentRequestTelemetry.h
IdentityCore/src/telemetry/request_telemetry/MSIDCurrentRequestTelemetry.m
IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m
IdentityCore/src/telemetry/request_telemetry/MSIDRequestTelemetryConstants.h
IdentityCore/src/telemetry/request_telemetry/MSIDRequestTelemetryConstants.m
IdentityCore/tests/MSIDCurrentRequestTelemetryTests.m
IdentityCore/tests/MSIDLastRequestTelemetryTests.m
changelog.txt

Update server telemetry (Current Request Telemetry) to follow schema version 4. Replace existing field for force refresh with below values
->InteractiveNoCacheLookupInvolved = 0, request goes to ESTS for interactive call for which there is no cache look-up involved (N/A for S2S).
-> ForcedTokenRefresh = 1, request goes to ESTS because caller requested to forcefully refresh the cache.
-> CacheMiss = 2, request goes to ESTS because cache entry for the requested token does NOT exist.
-> CachedTokenExpired = 3, request goes to ESTS because cache entry for the requested token does exist but token has expired.
-> ProactiveTokenRefresh = 4, request goes to ESTS because refresh_in was used and existing non-expired token needs to be refreshed proactively.
-> CachingMechanismNotImplemented = 5, …

Refresh_in telemetry changes

---

IdentityCore/src/util/ios/UIApplication+MSIDExtensions.h
IdentityCore/src/util/ios/UIApplication+MSIDExtensions.m

OneAuth-MSAL did renaming from `MSID` prefix to `MSAIMSID` to avoid conflicts between OneAuth-MSAL and ADAL. This file used random word in the extensions which our automation script in under MSAL cpp didn't detect, and lead to compiling conflict for Outlook who consume both OneAuth-MSAL and ADAL. So rename to `MSIDExtensions` as other extension files.  See this [teams thread](https://teams.microsoft.com/l/message/19:79277c14b7314a308a29465e43d91b67@thread.skype/1623198298182?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=83a3ee91-d323-4a09-b01c-6ee0bae50992&parentMessageId=1623198298182&teamName=OneAuth&channelName=Outlook%20Collaboration%20(iOS)&createdTime=1623198298182) as reference.

Rename the UIApplication Extensions

---

IdentityCore/src/throttling/cache/MSIDThrottlingCacheRecord.h
IdentityCore/src/webview/background/ios/MSIDBackgroundTaskManager.m
IdentityCore/tests/MSIDLRUCacheTest.m

As pointed in following issues : 
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/issues/993
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/issues/991
there are some implicit casts performed.
I don't think existing code will cause any issues as : 
- input param MSIDBackgroundTaskType is an enum with values 0 and 1 passed into MSIDBackgroundTaskManager setBackgroundTask: so the case should always work.
- throttlingType is passed in as enum MSIDThrottlingType with values ranging 0 to 2
Please disregard PR if the changes are not necessary.

Fixing casting to unsigned ints

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/throttling/model/MSIDThrottlingModelFactory.m
IdentityCore/src/throttling/model/MSIDThrottlingModelNonRecoverableServerError.h
IdentityCore/src/throttling/model/MSIDThrottlingModelNonRecoverableServerError.m
IdentityCore/tests/throttling/MSIDThrottlingModelNonRecoverableServerError.m

Adding a few additional error codes that should be throttled:
```
// MSALErrorServerDeclinedScopes                = -50003
// MSALErrorServerProtectionPoliciesRequired    = -50004
```
Since both of those are technically not "interaction required" errors, also renaming the model to MSIDThrottlingModelNonRecoverableServerError

Added additional errors to throttle

---

IdentityCore/src/MSIDError.h
IdentityCore/src/throttling/cache/MSIDLRUCache.m
IdentityCore/src/throttling/model/MSIDThrottlingModelFactory.m
IdentityCore/tests/MSIDLRUCacheTest.m
changelog.txt

Throttle internal logs confuse the reader. Add new throttle internal errors to help distinguish with cached error response from server.

New internal throttle errors to distinguise error from cache

---

IdentityCore/src/cache/key/MSIDDefaultAccountCacheQuery.m
IdentityCore/tests/MSIDAccountCredentialsCacheTests.m
IdentityCore/tests/mac/MSIDMacKeychainTokenCacheTests.m
changelog.txt

Report in this [link](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1449130)
These messages are repetitive written:
`2021-06-25T06:33:56.781Z kWarning [MSAL:0001] WARNING -[MSAIMSIDAccountCacheItem initWithJSONDictionary:error:]:284 No account type present in the JSON for credential`
`2021-06-25T06:33:56.781Z kVerbose [MSAL:0001] DEBUG   -[MSAIMSIDCacheItemJsonSerializer deserializeCacheItem:ofClass:]:96 TID=515301 (main thread) MSAL.xplat.iOS 1.0.0+bdeeb209 iOS 14.6 [2021-06-25 06:33:56] Failed to deserialize object (null) of expected class MSAIMSIDAccountCacheItem`
`2021-06-25T06:33:56.782Z kInfo [MSAL:0001] INFO   -[MSAIMSIDKeychainTokenCache cacheItemsWithKey:serializer:cacheItemClass:context:error:]:755 TID=515301 (main thread) MSAL.xplat.iOS 1.0.0+bdeeb209 …

Repetitive log when query account from cache

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/mac/MSIDCertAuthHandler.m
changelog.txt

Fix issue with showing smart card's cert on macOS 11.

Fix issue with showing smart card's cert on macOS.

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDClientTLSHandler.m
changelog.txt

Fix showing smart card's cert on macOS (ADAL hotfix).

Fix showing smart card's cert on macOS (ADAL hotfix).

---

IdentityCore/src/MSIDConstants.h
IdentityCore/src/parameters/MSIDInteractiveRequestParameters.h
IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m

During OneAuth-MSAL integration, there are chance that partners are not passing in a parentViewController. 
When presenting Sso extenion UI on Mac, the window will be placed randomly without an anchor. 
Current OneAuth can pass in a default Window, and we can use it in CommonCore as an anchor window.
The change is only applied to acquire token interactively.

add option to pass in fallback anchor window

---

IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
changelog.txt

Fix for ADAL apps that send passed In view to show spinner while blocked from showing SSO UI prompt on mac.
- [x ] Bug fix

Fix for ADAL apps that send passed In view to show spinner while blocked from showing SSO UI prompt on mac.

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/MSIDJsonSerializableTypes.h
IdentityCore/src/MSIDJsonSerializableTypes.m
IdentityCore/src/broker_operation/response/MSIDBrokerOperationGetSsoCookiesResponse.h
IdentityCore/src/broker_operation/response/MSIDBrokerOperationGetSsoCookiesResponse.m
IdentityCore/src/broker_operation/response/sso_cookies_response/MSIDCredentialHeader.h
IdentityCore/src/broker_operation/response/sso_cookies_response/MSIDCredentialHeader.m
IdentityCore/src/broker_operation/response/sso_cookies_response/MSIDCredentialInfo.h
IdentityCore/src/broker_operation/response/sso_cookies_response/MSIDCredentialInfo.m
IdentityCore/src/broker_operation/response/sso_cookies_response/MSIDDeviceHeader.h
IdentityCore/src/broker_operation/response/sso_cookies_response/MSIDDeviceHeader.m
IdentityCore/src/broker_operation/response/sso_cookies_response/MSIDPrtHeader.h
IdentityCore/src/broker_operation/response/sso_cookies_response/MSIDPrtHeader.m
IdentityCore/tests/MSIDBrokerOperationGetSsoCookiesResponseTests.m

Add broker respose for sso cookies.
MSIDBrokerOperationGetSsoCookiesResponse has a list of prtHeaders and deviceHeaders
prtHeader is subclassed from MSIDCredentialHeader
deviceHeader is subclassed from MSIDCredentialHeader.
The difference listed form sample json
For each MSIDCredentialHeader, there is a MSIDCredentialInfo which represents cookieName and cookieValue
Sample JSON:
@{
@"prt_headers":
@[
@{
@"header": @{@"x-ms-RefreshTokenCredential1": @"Base 64 Encoded JWT1"},
@"account_identifier": @"uid.utid1",
@"displayable_id": @"demo1@contoso.com"
},
@{
@"header": @{@"x-ms-RefreshTokenCredential2": @"Base 64 Encoded JWT2"},
@"account_identifier": @"uid.utid2",
@"displayable_id": @"demo2@contoso.com"
},
@{
@"header": @{@"x-ms-RefreshTokenCredential3": @"Base 64 Encoded JWT3"}, …

add sso cookies broker response

---

IdentityCore/src/MSIDError.h
IdentityCore/src/controllers/MSIDSilentController.m
IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
IdentityCore/src/requests/broker/MSIDSSOExtensionTokenRequestDelegate.m
IdentityCore/tests/integration/MSIDSilentControllerIntegrationTests.m
IdentityCore/tests/mocks/MSIDTestTokenRequestProvider.m
changelog.txt

- Add more log when we have response from sso ext for future debugging
- Exit the flow earlier if the response is invalid.
- If we don't have meaningful error from sso-ext, we choose the one from local controller

sso ext sanity check response

---

IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDTestAutomationAccountConfigurationRequest.m

/api/User from msidlab not returns the account if federationProviderType = none for truemamca account. tmp workaround by not sending that param if the value is none

temp remove federationprovider param in automation api

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
changelog.txt

In the sign in page, there is an option for user to create a MSA account via signup. 
During the sign up flow, there is a javascript game loaded in iframe to check if user is a robot/spammer. 
Clicking captcha image links in it causes them to open in safari instead of the same webview. This PR aims to update this logic so that links in iframes do not open in safari while keeping existing logic of opening links with target="_blank" in safari.

Updating logic to check if targetFrame is nil for new window

---

IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.m
changelog.txt

Expose keychain error osstatus in errors returned by MSIDAssymetricKeyKeychainGenerator
This change fixes 2 issues:
1. MSIDAssymetricKeyKeychainGenerator generateKeyPainForAttributes:error: overwrites an error returned by deleteItemWithAttributes:error: today. The change updates generateKeyPainForAttributes:error to directly returns the error.
2. MSIDAssymetricKeyKeychainGenerator logAndFillError:status:error: does not expose the status parameter on the returned error today. This prevents the calling code (like OneAuth-MSAL) to report the error in telemetry. This change packs any non-trivial status into an underlying NSError and attaches it to the error created by  logAndFillError:status:error: .
ADO#1729972

Expose keychain error osstatus in errors returned by MSIDAssymetricKeyKeychainGenerator

---

IdentityCore/src/util/NSDictionary+MSIDExtensions.m
IdentityCore/tests/MSIDDictionaryExtensionsTests.m
changelog.txt

Add generic warning message when query contains more than one '=' before converting it to NSDictionary and prevent logging PII data. 
Update tests with additional cases.

Prevent logging PII in query to NSDictionary extension method

---

IdentityCore/MSIDTestsHostApp/MSIDTestsHostApp.entitlements
IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinUtil.h
IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinUtilBase.m
IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m
IdentityCore/src/workplacejoin/mac/MSIDWorkPlaceJoinUtil.m
IdentityCore/tests/MSIDPkeyAuthHelperTests.m
IdentityCore/tests/MSIDWorkPlaceJoinUtilTests.m
changelog.txt

Allows handling PkeyAuth challenges for multiple tenant registrations. Note that MSAL version bump to 1.2 is a requirement to get tenantId from ESTS.

Multitenant PkeyAuth support

---

IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDTestAutomationAccount.h
IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDTestAutomationAccount.m
changelog.txt

Added overriddenKeyvaultName and  overriddenTargetTenantId to MSIDTestAutomationAccount. Lab team suggests to use `homeDomainName` to construct key vault URL for guest account:
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1651300

Add more utility to automation tests

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.h
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

Allow reading navigation response from MSIDOAuth2EmbeddedWebviewController.
This is required to extract request-id & session-id from the response headers, this information will help troubleshoot when doing compliance check fails.

Read navigation response on MSIDOAuth2EmbeddedWebviewController

---

IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m
changelog.txt

The issue is reported in the MSAL repo: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1455
The fix is to add the NSString type to when calling decode.

Fix a warning during telemetry decoding

---

IdentityCore/src/cache/MSIDMacTokenCache.m

Office reported seeing a lot of warnings when app is running, these warnings will be disallowed in the future:
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1843056
The repro in OneAuthTestApp:
I believe the changes could eliminate the warnings.

Fix warning "allowed unarchiving safe plist type 'NSString'..."

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/requests/MSIDSilentTokenRequest.m
IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m

Fix mapping unauthorized_client + protection_policy_required.
It was mapped to 50002 (MSALErrorInteractionRequired) instead of 50004 (MSALErrorServerProtectionPoliciesRequired) in silent flow.

Fix handling protection_policies_required in silent flow

---

IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
IdentityCore/tests/integration/ios/MSIDBrokerInteractiveControllerIntegrationTests.m
changelog.txt

Pass token result (MSIDInvalidTokenResultKey), granted scopes (MSIDGrantedScopesKey) and declined scopes (MSIDDeclinedScopesKey) as part of error.userInfo when these values are returned as additional_tokens in the broker response.
This will help provide the same `error.userInfo` when getting the error `MSIDErrorServerDeclinedScopes` and making the call through the broker.
This will help unblock https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1482

Provide all the error.userInfo details when getting MSIDErrorServerDeclinedScopes error

---

IdentityCore/src/cache/crypto/MSIDSymmetricKey.m
IdentityCore/src/requests/broker/MSIDBrokerCryptoProvider.m

Add checks to make sure memory allocation is successful before continuing the process. 
Suggested in https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1497

Validate if memory was successfully allocated before continuing.

---

IdentityCore/src/MSIDConstants.h
IdentityCore/src/MSIDConstants.m

This PR ONLY adds a constant for the string content of the shared mode Darwin notification. Currently, this will only be used in MSAL/Common Core to implement a listener for the notification in the test app.
In the future, this will be used to build Darwin notification listening code into Common Core, to be implemented in MSAL and OneAuth.

Add constant for Darwin notification name

---

IdentityCore/src/webview/embeddedWebview/ui/MSIDWebviewUIController.h
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m

MSAL CPP need to implement form sheet UI style on iPad. The only way is to overwrite -(void)presentView in MSIDWebviewUIController.m, but -(void)presentView is using a private property propertypresentInParentController.
Since MSIDOAuth2EmbeddedWebviewController which extends MSIDWebviewUIController is also used by MSAL CPP, adding a MSIDWebviewUIController+private will be not very applicable.
The easiest way is to make propertypresentInParentController a public property.

Make a property public for MSAL CPP to overwrite -(void)presentView

---

IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
IdentityCore/src/webview/systemWebview/session/MSIDSystemWebviewController.m

The issue is mentioned in this [GitHub issue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1526).
There are currently 2 small issues with the background task logic in the system webview case:
1. There are 2 tasks being spun up when doing a system webview request. Once in MSIDInteractiveTokenRequest (line 80), and once in MSIDSystemWebviewController (line 124).
2. If the user cancels the request before the auth code step, the existing "stop" call won't be reached.
This PR adds a "stop" call in the dealloc step of MSIDInteractiveTokenRequest to ensure tasks for cancelled requests are stopped, and a "stop" call in the completion handler of MSIDSystemWebviewController to ensure that all system webview background tasks are stopped.

Stop extra background tasks in the system webview case

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.h
IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.m

Some of federated msidlab4.com tests unexpectedly prompt for CBA, causing automation tests to be flaky.
This explicitly disables CBA for those tests to increase test stability.

Disable CBA automation

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
changelog.txt

This reverts commit a71be0ef4380da81adb77644b15f89a88b2e1a68, reversing changes made to a68a20bd7f179aa4e826dbecfdd4687e81b0223e.
Revert this pr: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1148

Revert disable bitcode pr

---

IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m
changelog.txt

Update Home accountId from clientInfo only if available in response
- [ x] Bug fix

Update Home accountId from clientInfo only if available

---

IdentityCore/src/util/NSURL+MSIDExtensions.m

On iOS 16.0 or macOS 13.0 and above, NSURLComponents percentEncodedHost will no longer throw an exception if invalid when building with Xcode 14, causing unit tests to fail to check an invalid host.
Note: There might be a better way to validate a host, specially since we are currently using the deprecated property `percentEncodedHost`.

Xcode 14: NSURLComponents percentEncodedHost will no longer throw an exception if invalid on iOS16+ & macOS13+

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/broker_operation/response/MSIDBrokerNativeAppOperationResponse.h
IdentityCore/src/broker_operation/response/MSIDBrokerNativeAppOperationResponse.m
IdentityCore/src/requests/MSIDSilentTokenRequest.h
IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.m
IdentityCore/src/requests/broker/MSIDSSOExtensionGetDeviceInfoRequest.m
IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.m
IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.h
IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m
IdentityCore/src/util/NSDate+MSIDExtensions.h
IdentityCore/tests/MSIDBrokerNativeAppOperationResponseTests.m
IdentityCore/tests/MSIDLastRequestTelemetryTests.m

Adding basic SSO extension performance telemetry for MSAL.Objective C. Note, it doesn't measure any actual performance inside the broker, it only provides info on MSAL side and sends it to ESTS telemetry. 1DS nor MATS won't give us this insight.

Basic SSO extension perf telemetry on MSAL side

---

IdentityCore/src/MSIDBrokerConstants.h
IdentityCore/src/MSIDBrokerConstants.m

GetDeviceInfo API will now return additional metadata about primary AAD device registration.

Return additional metadata about primary registration in SSO extension getDeviceInfo call

---

IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m

Edge is having issue when trying so handle PKeyAuth on iOS for ManBro. It cannot find device info, but broker can, and there is only single legacy device registration. Adding an error log to check the accessGroup and error Status

Add/modify more level logs for CPP when Edge cannot find PkeyAuth in OneAuth but broker can

---

IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m
IdentityCore/tests/MSIDWorkPlaceJoinUtilTests.m
changelog.txt

Fix a crash when identity is nil during getting device registration information on iOS

Fix a logging crash

---

IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m
IdentityCore/src/util/NSError+MSIDExtensions.h
IdentityCore/src/util/NSError+MSIDExtensions.m
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
IdentityCore/tests/MSIDErrorExtensionsTests.m
changelog.txt

- Add additional error codes for a more detailed telemetry for JIT.
- Fix typos.
This PR replaces https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1180 which had some build errors.

Add more detailed error codes for JIT WPJ - 2 [common]

---

IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.m
IdentityCore/tests/MSIDAADAuthorityTests.m
IdentityCore/tests/MSIDAADOauth2FactoryTests.m
IdentityCore/tests/MSIDIntuneEnrollmentIdsCacheTests.m
IdentityCore/tests/MSIDThrottlingServiceIntegrationTests.m
changelog.txt

- Return first enrollmentId from cache only if homeAccountId and legacyId are both empty. 
- Fetch enrollmentId by upn/oid with case insensitive checks. 
- Update/add unit tests.

EnrollmentIds issue with empty home account and legacy id

---

IdentityCore/src/controllers/MSIDLocalInteractiveController.m
changelog.txt

Check if completionBlock is valid before calling it on local interactive aquireToken.
MSAL issue: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1652

Prevent crash on MSAL issue

---

IdentityCore/src/webview/operations/MSIDWebOpenBrowserResponseOperation.m

The existing method  for masking PII : MSID_PII_LOG_MASKABLE(self.browserURL)); masks only when the masking level is set to 0 or 1. If, for some reason, it is changed to something else, masking isn't performed. See : https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/8a4a62b74992d1bf21ca156605797f1ecda0e44a/IdentityCore/src/logger/MSIDMaskedLogParameter.m#L79
This PR aims to use a method to mask parts of the URL and does not depend on a masking level.

Change method of masking PII

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/mac/MSIDCertAuthHandler.m
changelog.txt

Linking original PR: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1192
The existing method of certificate-based authorization does not save the preferred identity certificate choice of the user on MacOS. This PR aims to resolve this issue by saving (memorizing) the certificate preference after the first login, which should be picked automatically for future logins. The goal of the PR is to prevent the user from being asked multiple times to choose the same certificate when trying to access Office applications.
Creating new PR to make it cleaner and remove unchanged files from previous PR

[new PR] memorize certificate preference for macos

---

IdentityCore/src/oauth2/MSIDExternalSSOContext.h
IdentityCore/src/oauth2/MSIDExternalSSOContext.m
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebViewPlatformParams.m

Make internal method to calculate OS version protected, and add a placeholder MSIDExternalSSOContext class that will start accumulating everything related to SSO (reach out offline in private for more details if needed).

Make internal method to calculate OS version protected

---

IdentityCore/src/MSIDError.m
changelog.txt

Fix `A function declaration without a prototype is deprecated in all versions of C` error when using the new Xcode 14.3 [beta]

Fix function declaration without prototype

---

IdentityCore/src/throttling/model/MSIDThrottlingModel429.m
IdentityCore/src/util/NSError+MSIDThrottlingExtension.h

Copying per Office discoveries.
Crash happened when OneAuth SSO extension ran into error from -[ASAuthorizationController authorization:didCompleteWithError:], if this NSError has userInfo:
_userInfo __NSDictionaryI * [0](about:blanknull)x606000f03e60 0x0000606000f03e60
0 @"MSALErrorDescriptionKey" : @"Interaction is required to complete broker request, and interaction is not allowed in silent token acquisition."
[1](about:blanknull) @"MSALBrokerVersionKey" : @"5.2212.0"
IdentityCore code -[NSError(MSAIMSIDThrottlingExtension) msaimsidGetUserInfoValueWithMSIDKey:orMSALKey:] will try to parse httpStatus code from method:
(NSString *)msaimsidGetUserInfoValueWithMSIDKey:(NSString *)msidKey
orMSALKey:(NSString *)msalKey
{
return self.userInfo[[self msaimsidIsMSIDError] ? msidKey : msalKey];
} …

Fix a crash when UBSan validates

---

IdentityCore/src/broker_operation/response/MSIDDeviceInfo.m
changelog.txt

Added null check for additional json info in DeviceInfo to fix the crash given here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1659

Added null check for additional json info in DeviceInfo

---

IdentityCore/src/broker_operation/request/MSIDBrokerOperationRequest.h
IdentityCore/src/broker_operation/request/MSIDBrokerOperationRequest.m
IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
IdentityCore/src/parameters/MSIDRequestParameters.h
IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.m
IdentityCore/src/util/ASAuthorizationSingleSignOnProvider+MSIDExtensions.m
IdentityCore/src/util/mac/MSIDKeychainUtil+MacInternal.h
IdentityCore/src/util/mac/MSIDKeychainUtil.m
IdentityCore/tests/MSIDBrokerOperationRequestTests.m

Skip broker_key nil check when preparing broker request. The change:
1. Does not impact any current iOS flow
2. Does not impact Mac apps if they are correctly signed with app entitlements
3. Will change for apps without correct app entitlements, and allow using empty broker_key (Broker will use the caller_bundle_identifier as broker_key instead)  
4. This should also help with browser_core work if it cannot add entitlements @antrix1989

Kaisong1990/2435627 relaxing broker_key validation

---

IdentityCore/src/MSIDJsonSerializer.h
IdentityCore/src/MSIDJsonSerializer.m

MSIDJsonSerializer API has a great internal method to deserialize JSON.
This is needed in broker. Making it public to avoid duplicating code there.

Make JSON serializer method public

---

IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinUtilBase.m

Restructuring code to check for primary registration tenantId only for ECC based default registration.

Restructuring code to check primary registration tenantId only for ECC

---

IdentityCore/src/workplacejoin/MSIDWorkPlaceJoinUtilBase.m
changelog.txt

Cherry picking changes for PkeyAuth+ changes for release/1.7.18. These changes also include some external key prt changes but it is fine as to include it as they are broker changes and will be taken up by broker later

Cherry picking changes for release 1.7.18

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/tests/util/network/MSIDTestURLSession.m
IdentityCore/tests/util/network/MSIDTestURLSessionUploadTask.h
IdentityCore/tests/util/network/MSIDTestURLSessionUploadTask.m
azure_pipelines/pr-validation.yml

Added uploadTaskWithRequest method has been required by 1DS library while logging event in Unit Tests as we sizziling the NSURLSession with MSIDTestURLSession class it is causing crash since it is not able to found in MSIDTestURLSession

Add uploadTaskWithRequest method to fix unit tests in telemetry

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
changelog.txt

CBA + system web view + SSO extension didn't work as expected because it was missing MSID_BROKER_IS_PERFORMING_CBA flag

Fix CBA in SSO ext flow

---

IdentityCore/src/validation/MSIDCIAMAuthority.m
IdentityCore/tests/MSIDCIAMAuthorityTests.m

This PR is to fix a realm issue in the CIAM authority (makes sure the realm is correctly extracted from the URL and remove any unnecessary characters).
Related PRs:
[MSAL CIAM Changes](https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/1682) 
[Identity Core CIAM Changes](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1227) 
[Related work item](https://identitydivision.visualstudio.com/Engineering/_boards/board/t/Auth%20Client%20-%20Apple/Backlog%20items)

Fix CIAM Authority Tests

---

IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.h
IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.m

Adding property in automation WPJ request to propagate useMostSecureStorage in WorkplaceJoin

Adding property to use most secure storage for WPJ in broker automation request

---

IdentityCore/src/MSIDBrokerConstants.h
IdentityCore/src/MSIDBrokerConstants.m
IdentityCore/tests/MSIDDeviceInfoTests.m

Expose is CallerApp managed in extraDeviceInfo dict for MAM sdk
- [x ] Feature work
- [x ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

Add isCallerAppManaged to extraDeviceInfoDict

---

IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.h
IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m
IdentityCore/src/cache/key/MSIDDefaultCredentialCacheQuery.h
IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
IdentityCore/tests/MSIDAccountCredentialsCacheTests.m
changelog.txt

@dorinung:
AB#2613823
Added code that removes expired AT for apple storage.
(removeExpiredCredentialsWithQuerys). This method is called from deleteAccessTokens which in turn is called from writeCredentials. Note that is only called from MSAIStorageManagerImpl.m so it will not be part of any other IdentityCore code paths. It relies on the addition getCredentialsWithQuery and matchesWithRealm relying on new value MSIDAny in MSAIMSIDComparisonOptions to return all entries for homeAccountId, environment, realm and clientId in cache query. The returned entries are then tested for expiration. Expired tokens are deleted using removeAllCredentials call.
Here is an MSAL draft PR that shows end to end changes with both XPLAT and apple storage changes. …

Added code that removes expired AT for apple storage.

---

IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.h
IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m
IdentityCore/src/cache/key/MSIDDefaultCredentialCacheQuery.h
IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
IdentityCore/tests/MSIDAccountCredentialsCacheTests.m
changelog.txt

hotfix AzureAD/hotfix/1.7.23
Fix for OneAuth to add code that removes expired AT for apple storage. This is just syncing up dev with master

merge master/hotfix for OneAuth removeExpiredAccessTokensCredentialsWithQuery  to dev

---

IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m

Replace deprecated NSProgressIndicatorSpinningStyle based on: remyjette
https://developer.apple.com/documentation/appkit/nsprogressindicatorspinningstyle
This PR is same a this fork PR: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1258

Replace deprecated NSProgressIndicatorSpinningStyle with NSProgressIndicatorStyleSpinning

---

IdentityCore/src/util/MSIDRedirectUri.h
IdentityCore/src/util/MSIDRedirectUri.m
IdentityCore/src/util/ios/MSIDRedirectUriVerifier.m
IdentityCore/src/util/mac/MSIDRedirectUriVerifier.m
IdentityCore/tests/MSIDBrokerRedirectUriTest.m
changelog.txt

Cherry-picked the feature from dev and provide more details when broker redirect_uri is not valid

Enhancing broker redirect_uri validation

---

IdentityCore/src/util/NSDate+MSIDExtensions.h
IdentityCore/src/util/NSDate+MSIDExtensions.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/mac/MSIDCertAuthHandler.m
changelog.txt

Steps to test:
**Picker test.**
1. Make sure you have expired and valid certificates in the keychain
2. Open MSAL Mac Test App.
3. Pick: "Passed In" webview.
4. Click "acquire token"
5. Enter upn that supports CBA.
6. Pick "Sign in using x.509 certificate"
7. Make sure only unexpired certificates are shown.
**Preferred expired certificate test.**
1. Comment/remove kSecMatchValidOnDate from the query.
2. Make sure you have expired and valid certificates in the keychain.
3. Build and open MSAL Mac Test App.
4. Pick: "Passed In" webview.
5. Click "acquire token"
6. Enter upn that supports CBA.
7. Pick "Sign in using x.509 certificate"
8. Pick expired certificate
9. Uncomment/put back kSecMatchValidOnDate in the query.
10. Build MSAL Mac Test App again
11. Make sure certificate picker is …

Filter expired certs in the certificate picker

---

IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m
IdentityCore/src/controllers/broker/ios/MSIDBrokerInteractiveController.m
IdentityCore/tests/integration/ios/MSIDBrokerInteractiveControllerIntegrationTests.m

When legacy cannot be opened when app is in background or inactive, return a separate error code for OneAuth telemetry purpose

Add new broker failed to open error

---

IdentityCore/src/configuration/webview/MSIDBaseWebRequestConfiguration.h

Property can be initialized as nil via nullable param.
- [ x] Bug fix

Fix for nullability annotation for `MSIDBaseWebRequestConfiguration soContext` property.

---

IdentityCore/src/util/MSIDKeyOperationUtil.m

Do not log error if key doesn't support signing alg : Bug fix for https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2609499

Do not log error when checking if key supports a signing alg

---

IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDPKeyAuthHandler.m

In order to decrease the size of OneAuth, CommonCore telemetry is excluded, so does the pKeyAuth handler class.

Exclude telemetry logic from commoncore when building against MSAL cpp

---

IdentityCore/src/MSIDDeviceId.m

[kIOMasterPortDefault](https://developer.apple.com/documentation/iokit/kiomasterportdefault?language=objc) was deprecated and renamed to [kIOMainPortDefault](https://developer.apple.com/documentation/iokit/kiomainportdefault?language=objc).
IDO: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2673884?src=WorkItemMention&src-action=artifact_link

update deprecated symbol kIOMasterPortDefault

---

IdentityCore/src/MSIDOAuth2Constants.h
IdentityCore/src/MSIDOAuth2Constants.m
IdentityCore/src/network/response_serializer/preprocessor/MSIDAADJsonResponsePreprocessor.m
IdentityCore/src/oauth2/MSIDTokenResponse.h
IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.h
IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.m

Added ccs request id flag in token response to be consumed by OneAuth.

Added ccs request id flag in token response to be consumed by OneAuth

---

IdentityCore/src/webview/embeddedWebview/ui/MSIDWebviewUIController.h
IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
changelog.txt

MSAL C++ needs to isolate the local web browsing state from that of the app. We need to use non-persistent website data store, and they need to clear cookies because MSAL has "retry" UX flows that can be triggered from error page. However, it is only possible to truly "go back in time" if the cookies are cleared.

Introduce a way to inject external WKWebviewConfiguration for MSIDWebviewUIController (needed for MSAL C++) 

---

IdentityCore/src/MSIDCache.h
IdentityCore/src/MSIDCache.m
IdentityCore/tests/MSIDCacheTests.m

Add API `MSIDCache:copyAndReplaceObjectForKey:withObject:]` in `MSIDCache`, which is needed for fixing race condition bug in broker repo: https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/1522

Add API copyAndReplaceObjectForKey in MSIDCache

---

IdentityCore/src/MSIDBrokerConstants.h
IdentityCore/src/MSIDBrokerConstants.m
IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h
IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
IdentityCore/src/parameters/MSIDRequestParameters.h
IdentityCore/src/requests/MSIDSilentTokenRequest.h
IdentityCore/src/requests/MSIDSilentTokenRequest.m
IdentityCore/tests/MSIDBrokerOperationInteractiveTokenRequestTests.m
IdentityCore/tests/MSIDBrokerOperationSilentTokenRequestTests.m
IdentityCore/tests/MSIDBrokerOperationTokenRequestTests.m
IdentityCore/tests/MSIDThrottlingServiceIntegrationTests.m
changelog.txt

For silent request, allowing if client passing forceRefresh=Yes in the param will ask broker ignore token cache and using PRT to get new token

Ignore broker cache

---

IdentityCore/tests/MSIDURLExtensionsTests.m
IdentityCore/tests/util/MSIDTestIdentifiers.h

From Apple documentation: https://developer.apple.com/documentation/foundation/nsurl/1572047-urlwithstring:
> For apps linked on or after iOS 17 and aligned OS versions, [NSURL](https://developer.apple.com/documentation/foundation/nsurl) parsing has updated from the obsolete RFC 1738/1808 parsing to the same [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) parsing as [NSURLComponents](https://developer.apple.com/documentation/foundation/nsurlcomponents). This unifies the parsing behaviors of the NSURL and NSURLComponents APIs. Now, NSURL automatically percent- and IDNA-encodes invalid characters to help create a valid URL.
This change will make strings like `https://stuff.com#bar=foo#` be parsed as `https://stuff.com#bar=foo%23` where in the previous version it would return `nil`. …

Update unit tests after changes on NSURL URLWithString on iOS 17

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/MSIDConstants.h
IdentityCore/src/MSIDOAuth2Constants.h
IdentityCore/src/MSIDOAuth2Constants.m
IdentityCore/src/auth_scheme/MSIDAuthenticationSchemeSshCert.h
IdentityCore/src/auth_scheme/MSIDAuthenticationSchemeSshCert.m
IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
IdentityCore/src/requests/broker/MSIDBrokerTokenRequest.m
IdentityCore/src/util/MSIDAuthScheme.m
IdentityCore/tests/MSIDAuthenticationSchemeSshCertTest.m
IdentityCore/tests/MSIDInteractiveTokenRequestParametersTests.m
IdentityCore/tests/MSIDRequestParametersTests.m
IdentityCore/tests/integration/MSIDCacheSchemaValidationTests.m
IdentityCore/tests/integration/ios/MSIDBrokerTokenRequestTests.m

Add new auth scheme for ssh-cert
Broker change: https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/1580

CommonCore change to support ssh-cert flow for runtime

---

IdentityCore/src/controllers/broker/ios/MSIDBrokerInteractiveController.m
IdentityCore/tests/integration/ios/MSIDBrokerInteractiveControllerIntegrationTests.m
changelog.txt

Fix bug when fallback to legacy broker interactive controller successfully, it should update last refresh time stamp of throttling cache

Fix throttling bug

---

IdentityCore/src/parameters/MSIDRequestParameters.h
IdentityCore/src/parameters/MSIDRequestParameters.m
IdentityCore/tests/MSIDRequestParametersTests.m

Added property to allow developers to set a nil redirect URI in a request. Needed for Native Auth refresh token call.

Added property to allow developers to set a nil redirect URI in a request.

---

IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m
IdentityCore/src/controllers/MSIDLocalInteractiveController.m
IdentityCore/src/webview/response/MSIDWebWPJResponse.h
IdentityCore/src/webview/response/MSIDWebWPJResponse.m
IdentityCore/tests/MSIDAADWebviewFactoryTests.m
IdentityCore/tests/MSIDWebMSAuthResponseTests.m
IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
changelog.txt

Add a new hint to indicate that the registration requires token protection i.e passing a flag to WPJ to set using most_secure_storage to true.
This part is in common core to set the flags in additionalInfo.

Update device register to include a new hint for Token protection

---

IdentityCore/src/oauth2/account/MSIDAccountType.h
IdentityCore/src/oauth2/account/MSIDAccountType.m

Update MSIDAccountType enum to include "ADFS" as new account type. Correspondingly update implementation as well
When ADFS account type is presented to Identity Core then it is defaulted to type "Other" causing ADFS on prem flow to fail for Outlook macOS. Hence added "adfs" account type.
Migration of existing ADFS accounts will not work. This is expected by OneAuth-MSAL.
Tested these changes locally along with Outlook mac and OneAuth-MSAL code and end to end flow works as expected.

Add new account type to support ADFS on prem scenarios

---

IdentityCore/src/MSIDBrokerConstants.h
IdentityCore/src/MSIDBrokerConstants.m
IdentityCore/src/network/MSIDHttpRequest.m
IdentityCore/src/network/MSIDURLSessionManager.h
IdentityCore/src/network/MSIDURLSessionManager.m

This is to create a new sessionUrl each time instead of using a singleton to avoid blocking network request when other network stuck
We will put a flight around and only available in broker

Create new url session instead of reusing a singlton with serial queue

---

IdentityCore/src/controllers/MSIDLocalInteractiveController.m

NSDictionary holds object values of type (id) entries. `NSError additionalInfo[MSIDTokenProtectionRequired]` was set with either  NO  or YES which translates to 0 or 1 because BOOL is tranformed to NO (0) or YES (1) as described [here](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/%5BApple%5D%20Objective%20C%20Style%20Guide/Objectice-C%20Style%20format%20and%20Guide.md&_a=preview&anchor=bool-pitfalls).
While reading, using the following format caused the value of BOOL to be always equals YES
```objc
// tokenProtection was always set to YES as the object exists not evaluating the content of id.
BOOL tokenProtection = error.userInfo[MSIDTokenProtectionRequired];
```
The proper fix is to use 
`[[error.userInfo objectForKey:MSIDTokenProtectionRequired] …

IdentityCore register device with hint - Enable ECC when hint is available

---

IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationOperationAPIRequestHandler.m

Get lab credentials in background thread to prevent error message and avoid possible UI issues.
Error message from pipeline: `This method should not be called on the main thread as it may lead to UI unresponsiveness.`

Automation - Get lab credentials in background thread

---

IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.h
IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m

Reported in [AppCenter crash](https://appcenter.ms/orgs/thomas-olsen-er92/apps/Skype-Teams-iOS-Store/crashes/errors/659814541u/reports/2516770165280009999-eb69eb07-8a16-41eb-9c54-40bd5f14b4e6/raw) tracking. There seems to be a crash that shows more often at this call stack
```objc
libobjc.A.dylib objc_release 
CoreFoundation -[__NSArrayM dealloc]
CoreFoundation cow_cleanup
CoreFoundation -[__NSDictionaryM dealloc]
CoreFoundation __RELEASE_OBJECTS_IN_THE_ARRAY__
CoreFoundation -[__NSArrayM dealloc]
TeamSpaceApp -[MSIDLastRequestTelemetry saveTelemetryToDisk] MSIDLastRequestTelemetry.m:440
```
From this stack. It is more obvious that NSArrayM dealloc is crashing either because that object is already deallocated or nil. Looking at the source code. We had an operation for [NSArray copy] which …

Attempt to fix an ios crash for MSAL at MSIDLastRequestTelemetry

---

IdentityCore/src/MSIDAADNetworkConfiguration.m
IdentityCore/src/controllers/broker/MSIDSSOExtensionSignoutController.m
IdentityCore/src/oauth2/MSIDWebviewFactory.m
IdentityCore/tests/MSIDLRUCacheTest.m
IdentityCore/tests/MSIDThrottlingServiceIntegrationTests.m
IdentityCore/tests/MSIDWebviewFactoryTests.m
IdentityCore/tests/integration/MSIDInteractiveControllerIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDBrokerInteractiveControllerIntegrationTests.m
IdentityCore/tests/integration/ios/MSIDBrokerOptionsTests.m
IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
changelog.txt

Signout from browser was previously not allowing developers to pass extra parameters.
If developer wants to pass a slice or logout_hint parameter, they won't be able to.
Adding support for the same
MSAL PR: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/2339

Support extra query parameters on signout

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj

Add specific minimum version to match downloaded visionOS simulator's version to fix this issue on `[MSAL] Common core submodule update check` pipeline:
for example: https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1371147&view=logs&j=ca125a0f-805b-582c-c197-3584139e4584&t=e20b3035-7539-51e8-aba3-a8fc9c962b85

Fix visionOS related errors during build pipeline

---

IdentityCore/src/util/ios/MSIDAppExtensionUtil.m
changelog.txt

Apple has begun force-returning false for any calls to the deprecated [openURL](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl?language=objc) method for apps/frameworks compiled with Xcode 16.
This is documented in the iOS 18 release notes at https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-18-release-notes
> Fixed: Applications built with iOS 18, iPadOS 18, Mac Catalyst 18, or tvOS 18 SDKs will call to the deprecated method
UIApplication.openURL(_:). The specified URL will not open and will always return false. (125695759)

Replace deprecated method UIApplication.openURL(_:) for all targets

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.h
IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
IdentityCore/src/configuration/webview/MSIDBaseWebRequestConfiguration.h
IdentityCore/src/oauth2/MSIDWebviewFactory.m
IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
IdentityCore/src/parameters/MSIDInteractiveTokenRequestParameters.h
IdentityCore/src/validation/MSIDAADAuthority.m
IdentityCore/src/validation/MSIDAadAuthorityCache.h
IdentityCore/src/validation/MSIDAadAuthorityCache.m
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.h
IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
IdentityCore/src/webview/embeddedWebview/customHeaderProviding/MSIDCustomHeaderProviding.h
IdentityCore/tests/MSIDAadAuthorityCacheTests.m
IdentityCore/tests/integration/MSIDAuthorityIntegrationTests.m
changelog.txt

Add support in common to allow broker to attach cross domain PRT headers in webview. 
More details, please see here:
https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/1703

Add support to attach cross domain PRT in embedded webview

---

azure_pipelines/msal_submodule_check.yaml

Due to consistent failures in the "[MSAL] Common core submodule update check" pipeline since visionOS was added, this PR converts that Azure Pipelines UI pipeline to a yaml-based pipeline. After this PR is merged into dev, I will create an accompanying new pipeline that runs from this yaml file and eventually remove "[MSAL] Common core submodule update check".
The benefit of a yaml based pipeline is that we can run the pipeline from different branches, allowing us to test changes to the pipeline before those changes affect all other pipeline runs.
This pipeline should:
~ Clone MSAL
~ Update the submodule of common core to the specified commit
~ Run the MSAL build.py to verify the common core changes with MSAL dev

Convert "[MSAL] Common core submodule update check" to a yaml file

---

IdentityCore/tests/automation/ui_tests_lib/MSIDBaseUITest.m

Resolve a crash when assign the 0 to expectedFulfillmentCount

---

IdentityCore/src/logger/MSIDMaskedUsernameLogParameter.m
IdentityCore/tests/MSIDMaskedUsernameLogParameterTests.m
changelog.txt

MSID_PII_LOG_EMAIL() returns different hash values for the same email address with different cases.
This can cause confusion in log if caller passes UPN in request parameters without case conversion.
This PR aims to log UPN hash in a case-insensitive manner to avoid confusion in logs.
There is no change in functionality for keychain queries using upn because we already lower case before making keychain query.

Make upn hash case insensitive

---

azure_pipelines/msal_submodule_check.yaml
azure_pipelines/pr-validation.yml

Sometimes the tests in pipelines fail, but there is an error in xcpretty that doesn't allow it to show the actual error in the test; apparently happening in the new version of xcpretty: https://github.com/xcpretty/xcpretty/issues/391 
The error in the pipelines look like this:
```
Build & Testing Failed! \n /usr/local/lib/ruby/gems/3.0.0/gems/xcpretty-0.4.0/lib/xcpretty/parser.rb:366:in 'parse': uninitialized constant XCPretty::Parser::ERB (NameError)
from /usr/local/lib/ruby/gems/3.0.0/gems/xcpretty-0.4.0/lib/xcpretty/formatters/formatter.rb:88:in 'pretty_format'
from /usr/local/lib/ruby/gems/3.0.0/gems/xcpretty-0.4.0/lib/xcpretty/printer.rb:19:in 'pretty_print'
from /usr/local/lib/ruby/gems/3.0.0/gems/xcpretty-0.4.0/bin/xcpretty:84:in 'block in <top (required)>'
from …
```

Use older version of xcpretty [Common]

---

IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h
IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
IdentityCore/src/broker_operation/response/browser_native_message_response/MSIDBrowserNativeMessageGetTokenResponse.m
IdentityCore/src/oauth2/MSIDOauth2Factory.m
IdentityCore/src/oauth2/MSIDTokenResponse.h
IdentityCore/src/oauth2/MSIDTokenResponse.m
IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.h
IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.m
IdentityCore/src/parameters/MSIDRequestParameters.h
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.h
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
IdentityCore/src/requests/sdk/adal/MSIDLegacyTokenResponseValidator.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenResponseValidator.m
IdentityCore/tests/MSIDDefaultTokenResponseValidatorTests.m
IdentityCore/tests/MSIDLegacyTokenResponseValidatorTests.m
IdentityCore/tests/automation/ui_tests_lib/MSIDBaseUITest.m
changelog.txt

Merge Hotfix/1.7.44

---

IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h
IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
IdentityCore/src/broker_operation/response/browser_native_message_response/MSIDBrowserNativeMessageGetTokenResponse.m
IdentityCore/src/oauth2/MSIDOauth2Factory.m
IdentityCore/src/oauth2/MSIDTokenResponse.h
IdentityCore/src/oauth2/MSIDTokenResponse.m
IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.h
IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.m
IdentityCore/src/parameters/MSIDRequestParameters.h
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.h
IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
IdentityCore/src/requests/sdk/adal/MSIDLegacyTokenResponseValidator.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenResponseValidator.m
IdentityCore/tests/MSIDDefaultTokenResponseValidatorTests.m
IdentityCore/tests/MSIDLegacyTokenResponseValidatorTests.m
changelog.txt

Merge main in dev

---

azure_pipelines/msal_submodule_check.yaml
azure_pipelines/pr-validation.yml

Uninstall xcpretty version 0.4.0 before installing version 0.3.0

Uninstall xcpretty version 0.4.0 before installing version 0.3.0 [CommonCore]

---

IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m
IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m
IdentityCore/tests/MSIDAADRequestErrorHandlerTests.m
IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m

When token request fails with http error code 403 and 404 , we currently return MSIDErrorServerUnHandledResponse. This PR will add a new error MSIDErrorUnexpectedHttpResponse in case of http error code 403 or 404 and add this as an underlying error in the MSIDErrorServerUnHandledResponse error returned.
- [x ] Feature work

Add new error mapping for http error code 403 and 404

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/network/request_server_telemetry/MSIDAADTokenRequestServerTelemetry.m
IdentityCore/src/network/request_server_telemetry/MSIDHttpRequestServerTelemetryHandling.h
IdentityCore/tests/MSIDAADTokenRequestServerTelemetryTests.m
IdentityCore/tests/mocks/MSIDLastRequestTelemetry+Tests.h

Update resetting MSID telemetry logic to make sure reset happens correctly when in no error cases. Previous accumulated errors should be sent through a successful session

Modify the MSID telemetry reset logic

---

azure_pipelines/broker_submodule_check.yml

This PR updates the broker submodule check pipeline to split the testing on separate threads per platform, and to run the broker unit tests on visionOS.

Update broker submodule check to test on visionOS

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

This PR stops the navigation notification from triggering when the webview navigation item is not targeting the main frame. When this would happen before, the main frame cannot end the navigation action and the stop notification is not sent. This caused the loading spinner in the webview to stay up even if the main webview content loaded.

Loading spinner fix - check if webview navigation action targeted to main frame

---

IdentityCore/src/parameters/MSIDInteractiveTokenRequestParameters.h

`crossDomainHeaderProvider` can be null for `MSIDInteractiveTokenRequestParameters`. Add the specifier "nullable" to the property.

Add nullable to crossDomainHeaderProvider

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Adding Issue templates. Took references from MSALJS and MSAL Android
Please feel to provide any suggestions regarding the template fields, structure, grammatical mistakes or any other.
To view templates:
Bug Report:
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/swagup/issue_templates/.github/ISSUE_TEMPLATE/bug_report.yml 
Feature Request:
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/swagup/issue_templates/.github/ISSUE_TEMPLATE/feature_request.yml 
Documentation:
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/swagup/issue_templates/.github/ISSUE_TEMPLATE/documentation.yml

Adding issue templates

---

IdentityCore/src/MSIDError.h
IdentityCore/src/MSIDError.m
IdentityCore/src/util/MSIDRedirectUri.h
IdentityCore/src/util/MSIDRedirectUri.m
IdentityCore/src/util/ios/MSIDRedirectUriVerifier.m
IdentityCore/src/util/mac/MSIDRedirectUriVerifier.m
IdentityCore/tests/MSIDBrokerRedirectUriTest.m
IdentityCore/tests/MSIDRedirectUriVerifierTests.m
IdentityCore/tests/mac/MSIDRedirectUriVerifierMacTests.m

Ensure valid broker capable redirect URI is required for AAD scenarios
Related MSAL PR: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/2592

[MSAL2.x]Ensure valid broker capable redirect URI is required for AAD scenarios

---

IdentityCore/src/requests/MSIDInteractiveTokenRequest.m

Fix condition to log error when getting RT for SFRT

Fix condition to log error when getting RT for SFRT

---

azure_pipelines/verify_msalcpp_per_pr_ios.yml
azure_pipelines/verify_msalcpp_per_pr_mac.yml

Fixing MSALCPP pipeline to use OneAuth instead of Microsoft Authentication Library for C++
- [* ] Bug fix
- [ *] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)
Right now these jobs are both failing due to legitimate incompatibilies (a new enum value not handled in an MSALCPP switch statement).

Run common core pipelines against OneAuth instead of MSALCPP

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/MSIDConstants.h
IdentityCore/src/MSIDConstants.m
IdentityCore/src/MSIDOAuth2Constants.h
IdentityCore/src/MSIDOAuth2Constants.m
IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.h
IdentityCore/src/requests/MSIDSilentTokenRequest+Internal.h
IdentityCore/src/requests/MSIDSilentTokenRequest.m
IdentityCore/src/requests/sdk/adal/MSIDLegacySilentTokenRequest.m
IdentityCore/src/requests/sdk/msal/MSIDDefaultSilentTokenRequest.m
IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m

Ensuring that any remaining artifacts on the device for deleted user accounts are removed when ESTS returns the suberror=user_account_deleted. This fix should be applied in the common core where Brokers and MSALs are addressed.
Added TestFlight entry: "disable_rm_metadata"
WILink: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/3168316

 Handle account removed suberror in brokers and MSALs

---

IdentityCore/src/MSIDConstants.h
IdentityCore/src/MSIDConstants.m
IdentityCore/src/webview/embeddedWebview/challangeHandlers/mac/MSIDCertAuthHandler.m
changelog.txt

Disable preferred identity save/query in CBA flow to let user choose cert.
```
By design, CBA supports multiple accounts with different certificates on the same device.
The hostname (certauth.login.microsoftonline.com) and distinguished names (list of subject names of all the cert authorities configured in the tenant) are used to find the correct certificate for authentication. There is no user-specific unique ID per certificate because, in CBA, a user can have multiple certificates to authenticate the same UPN, and a certificate can be used to authenticate multiple users (e.g., personal/admin account, etc.).
The way it works relies on the user deciding the correct certificate, so the client needs to present the certificate picker.
The cache problem: We have two cache layers here: …
```

Disable preferred identity in CBA flow

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/cache/MSIDCachedNonce.h
IdentityCore/src/cache/MSIDCachedNonce.m
IdentityCore/src/network/request/MSIDNonceHttpRequest.h
IdentityCore/src/network/request/MSIDNonceHttpRequest.m
IdentityCore/src/requests/MSIDNonceTokenRequest.h
IdentityCore/src/requests/MSIDNonceTokenRequest.m
IdentityCore/tests/MSIDNonceTokenRequestTest.m
IdentityCore/tests/integration/MSIDOIDCSignoutRequestTests.m
IdentityCore/tests/mocks/MSIDNonceTokenRequestMock.h
IdentityCore/tests/mocks/MSIDNonceTokenRequestMock.m
changelog.txt

This PR aims to shift code to obtain nonce from broker to common-core so that it can also be used for bound refresh token acquisition by non-broker apps.

Shift nonce acquisition code from broker to common-core

---

IdentityCore/src/util/mac/MSIDXpcSingleSignOnProvider.m

This is to add an early return when falls into if block instead of continuing the completion handler after that

Add early return in if block

---

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
IdentityCore/src/requests/broker/MSIDBrokerCryptoProvider.m
IdentityCore/src/util/NSData+MSIDAES.h
IdentityCore/src/util/NSData+MSIDAES.m

Fix to avoid namespace conflict reported by : https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/2624
- [x ] Feature work

fix for github issue 2624

---

IdentityCore/src/MSIDConstants.h
IdentityCore/src/MSIDConstants.m
IdentityCore/src/webview/embeddedWebview/MSIDAADOAuthEmbeddedWebviewController.m
IdentityCore/tests/MSIDAADOAuthEmbeddedWebviewControllerTests.m

Calling `externalDecidePolicyForBrowserAction` will be done when running in legacy auth flow to decide to intercept the URL redirect or not.

JIT troubleshooting in legacy auth flow

---

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m

There are now 2 possible camera consent suppression flags possible in the SSO extension config. This PR adds a check for the 2nd flag.

Check for both possible camera consent suppression flags in user defaults

---

IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationBrowserTokenRequest.m
IdentityCore/tests/MSIDBrokerOperationBrowserTokenRequestTests.m

Print the protocol from URL path in SSO extension logs. 
Add log line when HTTP body of request intercepted by SSO extension is empty or undefined.

Add log to print URL protocol in path and stmt when http body is nil

---

IdentityCore/src/oauth2/MSIDExternalSSOContext.h
IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.h
IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.m

This PR adds a boolean flag to the MSIDExternalSSOContext to determine if PSSO registration is currently in-progress. It can be checked as the obj is passed through various flows.
This PR also adds a isDevicelessPRTv3 function.

Add flag for PSSO registration in progress to MSDIExternalSSOContext
