IdentityCore/src/util/MSIDJsonObject.m, IdentityCore/src/util/MSIDURLFormObject.m
I merged the PR too quick, didn't realize dev has already been updated earlier today. A couple of places need to be changed due to API change.
=> Fix error caused by merging a PR that is not in sync with the latest dev

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/cache/MSIDAdfsToken.h, IdentityCore/src/cache/MSIDAdfsToken.m, IdentityCore/src/cache/MSIDSharedCacheAccessor.h, IdentityCore/src/cache/MSIDToken.h, IdentityCore/src/cache/MSIDToken.m, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m, IdentityCore/src/cache/accessor/MSIDSharedTokenCache.h, IdentityCore/src/cache/accessor/MSIDSharedTokenCache.m, IdentityCore/src/oauth2/MSIDBrokerResponse.m, IdentityCore/src/util/MSIDJsonObject.h, IdentityCore/src/util/MSIDJsonObject.m, IdentityCore/tests/integration/MSIDLegacyTokenCacheIntegrationTests.m, IdentityCore/tests/integration/MSIDSharedTokenCacheIntegrationTests.m, IdentityCore/tests/util/MSIDTestBrokerResponse.h, IdentityCore/tests/util/MSIDTestBrokerResponse.m, IdentityCore/tests/util/MSIDTestCacheDataSource.h, IdentityCore/tests/util/MSIDTestCacheDataSource.m, IdentityCore/tests/util/cache/MSIDTestCacheAccessor.h, IdentityCore/tests/util/cache/MSIDTestCacheAccessor.m, IdentityCore/tests/util/cache/MSIDTestRequestParams.h, IdentityCore/tests/util/cache/MSIDTestRequestParams.m, IdentityCore/tests/util/cache/MSIDTestTokenResponse.h, IdentityCore/tests/util/cache/MSIDTestTokenResponse.m
This PR also includes some bug fixes discovered during testing
=> Legacy accessor tests

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/cache/MSIDTokenCacheKey.h, IdentityCore/src/cache/MSIDTokenCacheKey.m, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/util/NSURL+MSIDExtensions.h, IdentityCore/src/util/NSURL+MSIDExtensions.m, IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m, IdentityCore/tests/util/MSIDTestCacheDataSource.h, IdentityCore/tests/util/MSIDTestCacheDataSource.m, IdentityCore/tests/util/cache/MSIDTestCacheIdentifiers.h, IdentityCore/tests/util/cache/MSIDTestRequestParams.h, IdentityCore/tests/util/cache/MSIDTestRequestParams.m, IdentityCore/tests/util/cache/MSIDTestTokenResponse.h, IdentityCore/tests/util/cache/MSIDTestTokenResponse.m
Also includes some bug fixes to the accesssor and test utilities.
=> Msal accessor unit test

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/cache/mac/MSIDMacTokenCache.m, IdentityCore/src/cache/token/MSIDCacheItem.m, IdentityCore/src/cache/token/MSIDTokenCacheItem.h, IdentityCore/src/cache/token/MSIDTokenCacheItem.m, IdentityCore/src/oauth2/token/MSIDAccessToken.m, IdentityCore/src/oauth2/token/MSIDBaseToken.h, IdentityCore/src/oauth2/token/MSIDBaseToken.m, IdentityCore/src/oauth2/token/MSIDTokenType.h, IdentityCore/src/oauth2/token/MSIDTokenType.m, IdentityCore/tests/MSIDAccessTokenTests.m, IdentityCore/tests/MSIDBaseTokenTests.m, IdentityCore/tests/MSIDIdTokenTests.m, IdentityCore/tests/MSIDKeyedArchiverSerializerTests.m, IdentityCore/tests/MSIDLegacySingleResourceTokenTests.m, IdentityCore/tests/MSIDRefreshTokenTests.m, IdentityCore/tests/integration/MSIDAccessTokenIntegrationTests.m, IdentityCore/tests/integration/MSIDBaseTokenIntegrationTests.m, IdentityCore/tests/integration/MSIDIdTokenIntegrationTests.m, IdentityCore/tests/integration/MSIDLegacyTokenIntegrationTests.m, IdentityCore/tests/integration/MSIDRefreshTokenIntegrationTests.m, IdentityCore/tests/integration/MSIDTokenCacheDataSourceIntegrationTests.m, IdentityCore/tests/integration/ios/MSIDKeychainTokenCacheIntegrationTests.m, IdentityCore/tests/integration/mac/MSIDMacTokenCacheIntegrationTests.m
* Adding additionalClientInfo
* Fixing accessTokenType copying
* Fixing Mac token cache for empty accounts (backward compatibility with ADAL)
=> Fixing bugs found during ADAL integration

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/oauth2/MSIDOauth2Factory.h, IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/oauth2/aad_v1/MSIDAADV1Oauth2Factory.m, IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m, IdentityCore/src/webview/MSIDWebviewAuthorization.h, IdentityCore/src/webview/MSIDWebviewAuthorization.m, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.h, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2WebviewController.m, IdentityCore/src/webview/systemWebview/MSIDSystemWebviewController.h, IdentityCore/src/webview/systemWebview/MSIDSystemWebviewController.m
- Use factory for creating webview controllers, 
- Create a MSIDWebviewAuthorization class to handle auth session (single auth session)
- Other minor changes.
=> Webview definition update

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/IdentityCore.xcodeproj/xcshareddata/xcschemes/IdentityCore iOS.xcscheme, IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, IdentityCore/src/oauth2/MSIDWebviewFactory.h, IdentityCore/src/oauth2/MSIDWebviewFactory.m, IdentityCore/src/webview/MSIDWebviewAuthorization.h, IdentityCore/src/webview/MSIDWebviewAuthorization.m, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m, IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDPKeyAuthHandler.m, IdentityCore/src/webview/embeddedWebview/ui/MSIDWebviewUIController.h, IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m, IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDCredentialCollectionController.m, IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m, IdentityCore/src/webview/systemWebview/MSIDSFAuthenticationSession.h, IdentityCore/src/webview/systemWebview/MSIDSFAuthenticationSession.m, IdentityCore/src/webview/systemWebview/MSIDSafariViewController.h, IdentityCore/src/webview/systemWebview/MSIDSafariViewController.m, IdentityCore/src/webview/systemWebview/MSIDSystemWebviewController.h, IdentityCore/src/webview/systemWebview/MSIDSystemWebviewController.m, IdentityCore/tests/MSIDSystemWebviewControllerTests.m, IdentityCore/tests/MSIDWebviewAuthorizationTests.m, IdentityCore/tests/MSIDWebviewFactoryTests.m, IdentityCore/tests/util/MSIDTestWebviewInteractingViewController.m, IdentityCore/xcconfig/identitycore__common.xcconfig
- include additional checks to disable system webview from project
- minor fixes
=> Additional error fixes for ADAL/MSAL integration

IdentityCore/src/cache/MSIDCacheAccessor.h, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m, IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m, IdentityCore/src/oauth2/account/MSIDAccount.h, IdentityCore/src/oauth2/account/MSIDAccount.m, IdentityCore/src/oauth2/token/MSIDBaseToken.h, IdentityCore/src/oauth2/token/MSIDBaseToken.m, IdentityCore/src/oauth2/token/MSIDLegacyAccessToken.h, IdentityCore/src/oauth2/token/MSIDLegacyAccessToken.m, IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.h, IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m, IdentityCore/tests/MSIDAADOauth2FactoryTests.m, IdentityCore/tests/MSIDAADV1Oauth2FactoryTests.m, IdentityCore/tests/MSIDAADV2Oauth2FactoryTests.m, IdentityCore/tests/MSIDAccessTokenTests.m, IdentityCore/tests/MSIDAccountTests.m, IdentityCore/tests/MSIDBaseTokenTests.m, IdentityCore/tests/MSIDIdTokenTests.m, IdentityCore/tests/MSIDLegacyAccessTokenTests.m, IdentityCore/tests/MSIDLegacyRefreshTokenTests.m, IdentityCore/tests/MSIDLegacySingleResourceTokenTests.m, IdentityCore/tests/MSIDOauth2FactoryTests.m, IdentityCore/tests/MSIDRefreshTokenTests.m, IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m, IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m, IdentityCore/tests/integration/MSIDLegacyTokenCacheIntegrationTests.m
This is necessary for True MAM changes
=> Allow to get specific account from cache and added account identifier to the token

IdentityCore/tests/MSIDSystemWebviewControllerTests.m
check MSID_EXCLUDE_SYSTEMWV and exclude if this is set.
=> Add conditionals to tests

IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m, IdentityCore/tests/MSIDAADRequestErrorHandlerTests.m
*Updated Error Handler for the case of invalid requests.
=> updated error Handler for invalid requests

IdentityCore/src/util/NSDictionary+MSIDExtensions.h, IdentityCore/src/util/NSDictionary+MSIDExtensions.m, IdentityCore/tests/MSIDDictionaryExtensionsTests.m, IdentityCore/tests/MSIDURLExtensionsTests.m, IdentityCore/tests/MSIDWebviewFactoryTests.m
- let it handle query without value
- additional method: non-decoding string->dict
=> Revise utility - NSDictionary extension

IdentityCore/src/webview/response/MSIDWebOAuth2Response.m, IdentityCore/tests/MSIDWebOAuth2ResponseTests.m
If no value in code, return nil.
=> Additional check for blank auth code return

.travis.yml, IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/webview/systemWebview/ios/MSIDAuthenticationSession.m
=> Support iOS12 and ASWebAuthenticationSession

IdentityCore/src/util/NSString+MSIDExtensions.m
*Minor fix in api which generates hex string from NSData
=> minor fix for hexString length

IdentityCore/src/cache/token/MSIDAccountCacheItem.m, IdentityCore/src/cache/token/MSIDCredentialCacheItem.m, IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m, IdentityCore/tests/MSIDAccountCacheItemTests.m, IdentityCore/tests/MSIDCredentialCacheItemTests.m, IdentityCore/tests/MSIDKeyedArchiverSerializerTests.m, IdentityCore/tests/MSIDLegacyAccessTokenTests.m, IdentityCore/tests/MSIDLegacyRefreshTokenTests.m, IdentityCore/tests/MSIDLegacySingleResourceTokenTests.m, IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m, IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m, IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
*Fix minor issue in isEqualTo method
=> fixed object equality issue

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.h, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m, IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDCertAuthHandler.h, IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDClientTLSHandler.h, IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDClientTLSHandler.m, IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDWPJChallengeHandler.h, IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDWPJChallengeHandler.m, IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h, IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m, IdentityCore/src/webview/embeddedWebview/challangeHandlers/mac/MSIDCertAuthHandler.m
CBA, previously in broker code only, could be supported in common for future.
=> CBA Support

IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.h, IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.m, IdentityCore/src/validation/MSIDAADAuthority.m, IdentityCore/src/validation/MSIDADFSAuthority.m, IdentityCore/src/validation/MSIDAuthority.h, IdentityCore/src/validation/MSIDAuthority.m, IdentityCore/tests/MSIDAADAuthorityTests.m
Moved enrollmentId method to MSIDAuthority.
=> Moved enrollmentId method to MSIDAuthority

IdentityCore/src/util/MSIDKeychainUtil.m
* Previously applied fix doesn't seem to always work when Intune MAM SDK is also involved. If the offending teamID entry is written into com.microsoft.adalcache or com.microsoft.intune.mam keychain groups, Intune MAM SDK would block from deleting them under certain circumstances.
* Changing default teamID to not conflict with the problematic one should resolve the issue.
* Also added more error logs around keychain teamID retrieval to allow better investigation of similar issues in the future.
=> Changed default teamID hint to avoid conflicts

IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenRequestProvider.h, IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenRequestProvider.m, IdentityCore/tests/MSIDDefaultTokenRequestProviderTests.m
MSAL PR: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/418
=> Make token response validator configurable

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/MSIDConstants.h, IdentityCore/src/controllers/MSIDRequestControllerFactory.m, IdentityCore/src/oauth2/MSIDWebviewFactory.m, IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m, IdentityCore/src/parameters/MSIDInteractiveRequestParameters.h, IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m, IdentityCore/src/telemetry/MSIDTelemetryAPIEvent.m, IdentityCore/src/util/MSIDPromptType.m, IdentityCore/src/util/MSIDPromptType_Internal.h, IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m, IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
MSAL corresponding PR here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/415
=> Changed prompt from string to enum

IdentityCore/src/oauth2/MSIDWebviewFactory.m, IdentityCore/src/parameters/MSIDInteractiveRequestParameters.h, IdentityCore/src/parameters/MSIDInteractiveRequestParameters.m, IdentityCore/src/requests/MSIDInteractiveTokenRequest.h, IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
These changes are needed in the broker.
=> Add few properties to request params

IdentityCore/src/MSIDOAuth2Constants.h, IdentityCore/src/MSIDOAuth2Constants.m, IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/cache/key/MSIDDefaultCredentialCacheKey.h, IdentityCore/src/cache/key/MSIDDefaultCredentialCacheKey.m, IdentityCore/src/cache/key/MSIDDefaultCredentialCacheQuery.m, IdentityCore/src/cache/token/MSIDCredentialCacheItem.h, IdentityCore/src/cache/token/MSIDCredentialCacheItem.m, IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m, IdentityCore/src/oauth2/token/MSIDAccessToken.h, IdentityCore/src/oauth2/token/MSIDAccessToken.m, IdentityCore/tests/MSIDAADAuthorityTests.m, IdentityCore/tests/MSIDAADOauth2FactoryTests.m, IdentityCore/tests/MSIDAccessTokenTests.m, IdentityCore/tests/MSIDAccountCredentialsCacheTests.m, IdentityCore/tests/MSIDCredentialCacheItemTests.m, IdentityCore/tests/MSIDDefaultCredentialCacheKeyTests.m, IdentityCore/tests/MSIDDefaultCredentialCacheQueryTests.m, IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m
Access Token caching by enrollmentId
=> Access Token caching by enrollmentId

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
Add arm64e and armv7s architectures and create PR against `dev`.
=> Add missing archs

IdentityCore/src/cache/token/MSIDCredentialCacheItem.h, IdentityCore/src/cache/token/MSIDCredentialCacheItem.m, IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m, IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m, IdentityCore/src/oauth2/token/MSIDAccessToken.h, IdentityCore/src/oauth2/token/MSIDAccessToken.m, IdentityCore/tests/MSIDAADV2Oauth2FactoryTests.m, IdentityCore/tests/MSIDAccessTokenTests.m, IdentityCore/tests/MSIDCredentialCacheItemTests.m, IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m, IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m, IdentityCore/tests/integration/mac/MSIDMacTokenCacheIntegrationTests.m
Split the non-contentious part out of #385
=> Added extendedExpiresIn field to the CredItem

IdentityCore/src/controllers/ios/MSIDBrokerInteractiveController.m, IdentityCore/tests/integration/MSIDInteractiveControllerIntegrationTests.m, IdentityCore/tests/integration/ios/MSIDBrokerInteractiveControllerIntegrationTests.m
Also disabled tests that will always fail when running inside broker
=> Do authority validation before calling broker

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/IdentityCore_Internal.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/telemetry/MSIDTelemetry+Cache.h, IdentityCore/src/telemetry/MSIDTelemetry+Cache.m, IdentityCore/src/telemetry/MSIDTelemetry.m, IdentityCore/src/util/NSData+JWT.h, IdentityCore/src/util/NSData+JWT.m, IdentityCore/src/util/NSData+MSIDExtensions.h, IdentityCore/src/util/NSData+MSIDExtensions.m, IdentityCore/src/util/NSDate+MSIDExtensions.h, IdentityCore/src/util/NSDate+MSIDExtensions.m, IdentityCore/src/util/NSDictionary+MSIDExtensions.h, IdentityCore/src/util/NSDictionary+MSIDExtensions.m, IdentityCore/src/util/NSError+MSIDExtensions.h, IdentityCore/src/util/NSError+MSIDExtensions.m, IdentityCore/src/util/NSMutableDictionary+MSIDExtensions.h, IdentityCore/src/util/NSMutableDictionary+MSIDExtensions.m, IdentityCore/src/util/NSOrderedSet+MSIDExtensions.h, IdentityCore/src/util/NSOrderedSet+MSIDExtensions.m, IdentityCore/src/util/NSString+MSIDExtensions.h, IdentityCore/src/util/NSString+MSIDExtensions.m, IdentityCore/src/util/NSString+MSIDTelemetryExtensions.h, IdentityCore/src/util/NSString+MSIDTelemetryExtensions.m, IdentityCore/src/util/NSURL+MSIDExtensions.h, IdentityCore/src/util/NSURL+MSIDExtensions.m, IdentityCore/src/util/ios/UIApplication+MSIDExtensions.h, IdentityCore/src/util/ios/UIApplication+MSIDExtensions.m, IdentityCore/xcconfig/identitycore__idlib__ios.xcconfig
Adding arm64e and armv7s ARCHs support to the library.
Adding a workaround to include categories to static library.
=> Add arm64e and armv7s ARHCs and fix category issue in static library

IdentityCore/src/MSIDCache.m
*Make write/update operations async.
=> update msidcache code to make write/update operations async

IdentityCore/src/cache/ios/MSIDKeychainTokenCache.m
* Update cache logic to avoid regenerating keys.
=> update cache logic to avoid regenerating keys

IdentityCore/src/MSIDError.h, IdentityCore/tests/automation/shared/MSIDAutomationErrorResult.h, IdentityCore/tests/automation/shared/MSIDAutomationErrorResult.m
MSAL [PR](https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/512).
=> Add MSIDErrorRedirectSchemeNotRegistered error

IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m, IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h, IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
=> Merge 1.1.1 hot fix to master

IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m, IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h, IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
=> Merge 1.1.1 to dev

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/cache/ios/MSIDKeychainTokenCache.m, IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m, IdentityCore/src/requests/broker/MSIDBrokerKeyProvider.m, IdentityCore/src/util/MSIDKeychainUtil+Internal.h, IdentityCore/src/util/MSIDKeychainUtil.h, IdentityCore/src/util/ios/MSIDKeychainUtil.m, IdentityCore/src/util/mac/MSIDKeychainUtil.m, IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m, IdentityCore/tests/MSIDMacKeychainTokenCacheTests.m, IdentityCore/tests/integration/ios/MSIDKeychainTokenCacheIntegrationTests.m, IdentityCore/tests/util/MSIDTestBrokerKeyProviderHelper.m
*Change teamId to readonly property and editable for internal usage and unit testing.
=> Make teamId editable for testing

IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/oauth2/token/MSIDAccessToken.m, IdentityCore/src/oauth2/token/MSIDBaseToken.m, IdentityCore/src/oauth2/token/MSIDIdToken.m, IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.m, IdentityCore/src/oauth2/token/MSIDRefreshToken.m, IdentityCore/src/util/NSDictionary+MSIDExtensions.m
Since we have a growing number of differences between release/0.5.0 and dev, merging this to dev and will use dev going forward until changes ready. release/0.5.0 has become bigger than anticipated.
=> Merge 0.5.0 release branch into dev

IdentityCore/src/oauth2/account/MSIDAccountIdentifier.m
Need to use the logging macros to build as part of msalcpp.
=> use logging macros

IdentityCore/src/cache/metadata/accountMetadata/MSIDAccountMetadataCacheItem.m, IdentityCore/src/util/NSDictionary+MSIDExtensions.h, IdentityCore/src/util/NSDictionary+MSIDExtensions.m, IdentityCore/tests/MSIDAccountMetadataCacheItemTests.m
*Added a deep copy extension on nsdictionary.
=> Fixed issue with account metadata copy

IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m, IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m
Fixed bug in creating pKeyAuthHeader.
=> Fixed bug in creating pkey auth header

IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m, IdentityCore/src/oauth2/token/MSIDBaseToken.m
Minor improvements for v2 broker logging
=> V2 broker logging improvements

IdentityCore/src/MSIDNotifications.h, IdentityCore/src/MSIDNotifications.m, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m, IdentityCore/src/webview/systemWebview/ios/MSIDAuthenticationSession.m, IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m, IdentityCore/src/webview/systemWebview/ios/MSIDSystemWebviewController.m
https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1426
=> Pass webview in notifications

IdentityCore/tests/util/NSDictionary+MSIDTestUtil.m
Will target the PR to release/1.0.13 one the branch is created :)
Needed for ADAL 2.7.14. Updating unit tests in older ADAL.
=> Update UT util (needed for handling broker nonce in ADAL)

IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
=> Get homeaccount from account rather than access token

IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/tests/MSIDAADV1Oauth2FactoryTests.m, IdentityCore/tests/MSIDAADV2Oauth2FactoryTests.m
There is a PRT update fix that is in 1.1.5 but not in 1.3.1.
=> Merge PRT update fix from release 1.1.5

IdentityCore/src/cache/mac/MSIDMacCredentialStorageItem.m, IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m, IdentityCore/tests/MSIDMacKeychainTokenCacheTests.m
=> Fix macOS cache api's regarding querying all items.

IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m
This is to keep it consistent with dev branch
=> Retry 500 error on background queue

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/broker_operation/MSIDBrokerOperationRequestFactory.h, IdentityCore/src/broker_operation/MSIDBrokerOperationRequestFactory.m, IdentityCore/src/broker_operation/request/MSIDBrokerOperationInteractiveTokenRequest.h, IdentityCore/src/broker_operation/request/MSIDBrokerOperationInteractiveTokenRequest.m, IdentityCore/src/broker_operation/request/MSIDBrokerOperationRequest.h, IdentityCore/src/broker_operation/request/MSIDBrokerOperationRequest.m, IdentityCore/src/broker_operation/request/MSIDBrokerOperationSilentTokenRequest.h, IdentityCore/src/broker_operation/request/MSIDBrokerOperationSilentTokenRequest.m, IdentityCore/src/broker_operation/request/MSIDBrokerOperationTokenRequest.h, IdentityCore/src/broker_operation/request/MSIDBrokerOperationTokenRequest.m, IdentityCore/src/broker_operation/response/MSIDBrokerOperationResponse.h, IdentityCore/src/broker_operation/response/MSIDBrokerOperationResponse.m, IdentityCore/src/broker_operation/response/MSIDBrokerOperationTokenResponse.h, IdentityCore/src/broker_operation/response/MSIDBrokerOperationTokenResponse.m
- DTO objects for communication between ADAL/MSAL and broker extension
- Factory which knows how to create DTO objects from json.
=> Add broker operations.

IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m, IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
Addressing: https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1475
=> Check for main thread in AADWebViewFactory and disable swipe to cancel for ADAL

build.py
Iphone 6 isn't available anymore on travis.
=> Update build script

IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.m
Intune enrollment ID error was logged even if there was no error
=> Don't log intune enrollment ID error

IdentityCore/src/oauth2/aad_v1/MSIDAADV1IdTokenClaims.m, IdentityCore/src/oauth2/aad_v2/MSIDAADV2IdTokenClaims.m, IdentityCore/src/oauth2/b2c/MSIDB2CIdTokenClaims.m
We were logging error even if issuer is not present
=> Improve error logging when creating claims

IdentityCore/src/util/NSString+MSIDExtensions.h, IdentityCore/src/util/NSString+MSIDExtensions.m, IdentityCore/tests/MSIDStringExtensionsTests.m
This is needed in the broker to check WPJ state.
=> Domain suffix helper

IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.h, IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.m
Added additional features to the account metadata cache mocks.
=> Metadata cache accessor mock changes

IdentityCore/src/MSIDBrokerConstants.h, IdentityCore/src/MSIDBrokerConstants.m, IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationGetAccountsRequest.h, IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationGetAccountsRequest.m, IdentityCore/tests/MSIDBrokerOperationGetAccountsRequestTests.m
Add option to SSO ext. request to get all accounts including signed out accounts.
=> Add option to get all accounts including signed out accounts

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.h, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m, IdentityCore/src/parameters/MSIDInteractiveRequestParameters.h, IdentityCore/src/requests/MSIDInteractiveTokenRequest.m, IdentityCore/src/requests/sdk/msal/MSIDDefaultSilentTokenRequest.m, IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m, IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m, IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m, IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m, changelog.txt
Will be releasing an MSAL hotfix with two patches from broker release.
=> Merge broker hot fixes into latest MSAL branch

IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
Issue:
On iOS 13.4 SSO extension behaves similarly to the web view and drops network connection when app goes to the background. This means that certain MFA-s will not complete. 
Fix:
Applying same workaround as for normal interactive flows by starting a background task.
=> Fixed SSO extension + MSIT MFA

IdentityCore/src/cache/metadata/accountMetadata/MSIDAccountMetadata.m, IdentityCore/tests/util/MSIDApplicationTestUtil.m, IdentityCore/xcconfig/identitycore__idlib__common.xcconfig
Enable -Wunknown-pragmas to solve breaks on MSAL cpp.
=> Add Warning -Wunknown-pragmas

changelog.txt
=> Merge 1.4.1 release back into dev

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
Some newly added files were missing from the IdentityCore macOS target. Including them there.
=> Include missing files into IdentityCore macOS target

CODEOWNERS
Updated code owners from AppleIdentity to the new team.
Previous team didn't have any maintainers left so I couldn't update it anymore and had to create a new team.
=> Updated codeowners team

changelog.txt
Merging just released version back into dev.
=> Merge 1.5.0 release back into dev

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/oauth2/MSIDWebviewFactory.m, IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m, IdentityCore/src/webview/MSIDWebviewAuthorization.m, IdentityCore/src/webview/MSIDWebviewInteracting.h, IdentityCore/src/webview/embeddedWebview/MSIDAADOAuthEmbeddedWebviewController.h, IdentityCore/src/webview/embeddedWebview/MSIDAADOAuthEmbeddedWebviewController.m, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.h, IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m, IdentityCore/src/webview/embeddedWebview/ui/MSIDWebViewPlatformParams.h, IdentityCore/src/webview/embeddedWebview/ui/MSIDWebviewUIController.h, IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m, IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebViewPlatformParams.m, IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m, IdentityCore/src/webview/systemWebview/ios/MSIDSFAuthenticationSessionHandler.m, IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m, IdentityCore/src/webview/systemWebview/session/MSIDASWebAuthenticationSessionHandler.m, IdentityCore/src/webview/systemWebview/session/MSIDSystemWebViewControllerFactory.m, IdentityCore/src/webview/systemWebview/session/MSIDSystemWebviewController.m, IdentityCore/tests/MSIDOAuth2EmbeddedWebviewControllerTests.m, IdentityCore/tests/mocks/MSIDTestWebviewInteractingViewController.m
Necessary API Changed for Cpp Integration
This change is to add missing component to integrate embeded webview implementation into Cpp. The changes in CPP repo for integration was made [there] (https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/1038)
=> Necessary API Changed for Cpp Integration

IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.m, IdentityCore/tests/MSIDAccountMetadataCacheAccessorTests.m
=> Fix signout state

IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.m, IdentityCore/src/requests/MSIDSilentTokenRequest.m
- [ *] Logging/Telemetry
- [* ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)
=> Add logging for enrollment id mismatch for access tokens

IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetrySerializedItem.m
Fix a build issue by adding cast to long.
=> Fix build issue

IdentityCore/src/network/request_server_telemetry/MSIDAADTokenRequestServerTelemetry.m, IdentityCore/tests/mac/MSIDMacKeychainTokenCacheTests.m
=> Server telemetry reset last request

IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m, changelog.txt
=> Fix handling of cert based authentication challenge.

IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m, changelog.txt
- [*] Bug fix
- [*] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
=> Merge hotfix 1.5.2 changes back to dev.

IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m
- [*] Test
- [*] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)
=> Fix telemetry tests

changelog.txt
Merging 1.5.3 release branch back into dev.
=> Merge release back into dev

IdentityCore/tests/util/MSIDHttpRequest+OverrideCacheSave.m
=> Add __unused tag

IdentityCore/src/cache/key/MSIDDefaultCredentialCacheQuery.m
Fix query cache when Intune enrolled + AT Pop
=> Fix query cache in Intune Enrolled case

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/MSIDConstants.m, IdentityCore/src/MSIDOAuth2Constants.h, IdentityCore/src/MSIDOAuth2Constants.m, IdentityCore/src/auth_scheme/MSIDAuthenticationSchemePop.m, IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator+Internal.h, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.h, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m, IdentityCore/src/cache/mac/MSIDMacCredentialStorageItem.m, IdentityCore/src/cache/token/MSIDCredentialCacheItem.h, IdentityCore/src/cache/token/MSIDCredentialCacheItem.m, IdentityCore/src/oauth2/token/MSIDAccessTokenWithAuthScheme.m, IdentityCore/src/oauth2/token/MSIDLegacyAccessToken.h, IdentityCore/src/pop_manager/MSIDDevicePopManager+Internal.h, IdentityCore/src/pop_manager/MSIDDevicePopManager.h, IdentityCore/src/pop_manager/MSIDDevicePopManager.m
* Update cache schema to change "access_token_type" to "token_type"
* Update iOS/macOS test app to request pop tokens and generate RSA key pair
=> Update cache schema and add test app changes

IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m
=> update atpop key label

IdentityCore/src/oauth2/MSIDTokenResponse.m
=> Add if checks before printing error

IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m, IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
=> Bug fix for pop tokens

IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m, IdentityCore/src/util/NSData+MSIDExtensions.h, IdentityCore/src/util/NSData+MSIDExtensions.m, changelog.txt
Moved broker crypto utility to a common place, since macOS broker has a dependency on the same code base.
=> macOS broker crypto integration

changelog.txt
Merging release/1.5.4 branch back to dev.
=> Merge 1.5.4 back to dev

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/cache/crypto/MSIDAssymetricKeyGenerating.h, IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.m, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.h, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m, IdentityCore/src/pop_manager/MSIDDevicePopManager.h, IdentityCore/src/pop_manager/MSIDDevicePopManager.m, IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m, IdentityCore/tests/MSIDAssymetricKeyPair+Test.h, IdentityCore/tests/MSIDAssymetricKeyPair+Test.m, IdentityCore/tests/MSIDAssymetricKeychainGeneratorTests.m, changelog.txt
Move jsonWebKey creation to key pair class for Cpp integration.
=> Move jsonWebKey creation to key pair class for Cpp integration.

IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m, changelog.txt
Fix an incorrectly-cased include.
=> Fix incorrectly-cased filename

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, changelog.txt
There were a few unit test/mock files in the main product targets.
Removed them from targets.
=> Cleaned up test files from main targets

IdentityCore/src/cache/crypto/MSIDAssymetricKeyLookupAttributes.m, changelog.txt
Mark RSA public key as extractable
=> Mark RSA public key as extractable

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/MSIDBrokerConstants.h, IdentityCore/src/MSIDBrokerConstants.m, IdentityCore/src/MSIDWebResponseOperationConstants.h, IdentityCore/src/MSIDWebResponseOperationConstants.m, IdentityCore/src/requests/MSIDInteractiveAuthorizationCodeRequest.m, IdentityCore/src/webview/operations/MSIDWebOpenBrowserResponseOperation.h, IdentityCore/src/webview/operations/MSIDWebOpenBrowserResponseOperation.m, IdentityCore/src/webview/operations/MSIDWebResponseBaseOperation.h, IdentityCore/src/webview/operations/MSIDWebResponseBaseOperation.m, IdentityCore/src/webview/operations/MSIDWebResponseBrokerInstallOperation.m, IdentityCore/src/webview/response/MSIDWebOpenBrowserResponse.m, IdentityCore/src/webview/response/MSIDWebWPJResponse.m, IdentityCore/tests/integration/ios/MSIDWebResponseOperationFactoryTests.m, changelog.txt
In this PR, moved open url handler into openBroswerOperation so that it can be reused later on in CPP side
=> Code changes on common core side to integrate with cpp open broswer url

IdentityCore/src/cache/crypto/MSIDAssymetricKeyLookupAttributes.h, IdentityCore/src/webview/operations/MSIDWebResponseBrokerInstallOperation.m, changelog.txt
=> Fix unused parameter for macOS

IdentityCore/src/webview/operations/MSIDWebResponseBaseOperation.m, IdentityCore/src/webview/operations/MSIDWebResponseBrokerInstallOperation.m, changelog.txt
Merge 1.5.5 release back into dev.
=> Merge 1.5.5 release into dev

IdentityCore/src/webview/operations/MSIDWebResponseBaseOperation.m, IdentityCore/src/webview/operations/MSIDWebResponseBrokerInstallOperation.m, changelog.txt
Merging 1.5.5 release branch back into dev.
=> Merge 1.5.5 release back into dev

IdentityCore/src/oauth2/account/MSIDAccount.h, IdentityCore/src/oauth2/account/MSIDAccount.m, IdentityCore/tests/MSIDAccountTests.m, IdentityCore/tests/MSIDBrokerOperationGetAccountsResponseTests.m, changelog.txt
Allow SSO extension to return additional information about account availability for device wide SSO purposes.
=> Indicate whether account is an SSO account

changelog.txt
Merging common core release 1.5.6 back into dev.
=> Merge 1.5.6 release back into dev

IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.m, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.h, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPairWithCert.h, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPairWithCert.m, IdentityCore/src/workplacejoin/MSIDRegistrationInformation.h, IdentityCore/src/workplacejoin/MSIDRegistrationInformation.m, IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m, IdentityCore/src/workplacejoin/mac/MSIDWorkPlaceJoinUtil.m, changelog.txt
Add ability to query creation date on RSA key pair.
=> Return private key attributes on key pair generation.

changelog.txt
=> Release version 1.5.8

IdentityCore/tests/automation/ui_app_lib/MSIDClearCookiesTestAction.m
Previous way of removing WKWebview is not able to remove all cookies according to testing. Change to another API to remove all cookies. The change is only affecting our test app but not our MSAL logic.
=> Improve cookies remove logic in test automation

IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m, IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m, IdentityCore/tests/automation/ui_app_lib/MSIDClearCookiesTestAction.m, changelog.txt
Merge release/1.5.9 back into dev branch.
=> Merge release/1.5.9 back into dev

IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m, IdentityCore/src/util/mac/MSIDRedirectUriVerifier.m, IdentityCore/tests/MSIDInteractiveRequestParametersTests.m, IdentityCore/tests/MSIDLoggerTests.m, IdentityCore/tests/MSIDPkeyAuthHelperTests.m, IdentityCore/tests/MSIDWorkPlaceJoinUtilTests.m, IdentityCore/tests/integration/MSIDOIDCSignoutRequestTests.m, IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m, IdentityCore/tests/util/NSData+MSIDTestUtil.m, changelog.txt
=> Fix various warnings from MSAL C++

IdentityCore/src/cache/crypto/MSIDSymmetricKey.m, IdentityCore/tests/MSIDSymmetricKeyTests.m, changelog.txt
- [ x Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)
=> Fix kDF function

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
For common-core changes in MSAL
Since URL could contain PII, we should log only the scheme and host. Changing logging to log scheme & host instead of entire URL.
=> Log just the host & scheme of url clicked by the user in embedded WV

IdentityCore/tests/MSIDWebviewDefaultConfigurationSettingsTest.m
=> unit test timing update for PKeyAuth regression to pass CI/CD

changelog.txt
Merge 1.6.0 release back into dev and resolve conflicts.
=> Merge 1.6.0 release back into dev

IdentityCore/tests/mac/MSIDMacKeychainTokenCacheTests.m
We saw a failure in one of our nightly builds in this test, so I am fixing it.
=> Fix a race condition which could cause a test failure on a slow CI machine

IdentityCore/tests/MSIDLRUCacheTest.m, changelog.txt
Merge release 1.6.1 branch back into dev.
=> Merge release 1.6.1 back into dev

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/MSIDOAuth2Constants.h, IdentityCore/src/MSIDOAuth2Constants.m, IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.m, IdentityCore/src/network/request/MSIDAADRefreshTokenGrantRequest.m, IdentityCore/src/network/request/MSIDAADV1RefreshTokenGrantRequest.m, IdentityCore/src/network/request/MSIDRefreshTokenGrantRequest.h, IdentityCore/src/network/request/MSIDRefreshTokenGrantRequest.m, IdentityCore/src/throttling/thumbprint_calculation/MSIDThumbprintCalculatable.h, IdentityCore/src/throttling/thumbprint_calculation/MSIDThumbprintCalculator.h, IdentityCore/src/throttling/thumbprint_calculation/MSIDThumbprintCalculator.m, IdentityCore/tests/MSIDThumbprintCalculatorTests.m, changelog.txt
Resolved merge conflict with dev - now has both cache and thumbprint calculator. 
Since all the changes included are not invoked elsewhere, it is safe to merge into dev.
=> thumbprint calculators 

changelog.txt
=> Update change log

changelog.txt
Merge release branch back to dev
=> Merge release branch back to dev

IdentityCore/src/throttling/cache/MSIDLRUCache.m
=> solved concurrency issue

IdentityCore/src/pop_manager/MSIDDevicePopManager.m, IdentityCore/tests/MSIDDevicePopManagerTest.m, changelog.txt
fix at pop logic when creating signed AT for some required fields -> optional fields based on this spec:
https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/%5bXplat%5d%20AT-PoP%20Client%20Side/signed_http_requests.md&_a=preview&anchor=client-sdk-parameters
=> update at pop logic when creating signed at

IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.h, IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.m
Address two left comments from this pr:
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/965
=> Address commits from previous PR

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.h, IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.m, IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenResponseValidator.m, IdentityCore/tests/MSIDOauth2FactoryTests.m, IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m, IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m
Cannot update the release branch directly, it is protected :(
=> Update release branch

changelog.txt
=> Merge release 1.6.3 into dev

IdentityCore/src/cache/token/MSIDCredentialCacheItem.m, changelog.txt
* revert the change on requetClaims lookup logic
* Update change logs
=> revert the change on requetClaims lookup logic (#974)

IdentityCore/src/cache/token/MSIDCredentialCacheItem.m, changelog.txt
=> Kaisong1990/merge hotfix 1.6.4 into dev

IdentityCore/src/MSIDError.h, IdentityCore/src/auth_scheme/MSIDAuthenticationScheme.h, IdentityCore/src/broker_operation/response/MSIDBrokerNativeAppOperationResponse.h, IdentityCore/src/broker_operation/response/MSIDBrokerNativeAppOperationResponse.m, IdentityCore/src/cache/crypto/MSIDAssymetricKeyGenerating.h, IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.m, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.h, IdentityCore/src/cache/crypto/MSIDAssymetricKeyPairWithCert.h, IdentityCore/src/pop_manager/MSIDDevicePopManager.m, IdentityCore/src/telemetry/request_telemetry/MSIDCurrentRequestTelemetrySerializedItem.h, IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.h, IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m, IdentityCore/src/throttling/model/MSIDThrottlingModelFactory.h, IdentityCore/src/throttling/model/MSIDThrottlingModelFactory.m, IdentityCore/src/webview/operations/MSIDWebResponseOperationFactory.m, IdentityCore/src/workplacejoin/MSIDRegistrationInformation.h, IdentityCore/src/workplacejoin/mac/MSIDWorkPlaceJoinUtil.m, IdentityCore/tests/MSIDErrorTests.m
Fix warnings found by the static analyzer.
=> Fix warnings

azure_pipelines/verify_msalcpp_per_pr_ios.yml, azure_pipelines/verify_msalcpp_per_pr_mac.yml
=> Add unit and integration tests checks to early check any broken changes in common core

.travis.yml, IdentityCore/src/telemetry/request_telemetry/MSIDLastRequestTelemetry.m, changelog.txt
=> Improve telemetry storage security

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/parameters/MSIDInteractiveTokenRequestParameters.m, IdentityCore/src/parameters/MSIDRequestParameters+Internal.h, IdentityCore/src/parameters/MSIDRequestParameters.h, IdentityCore/src/parameters/MSIDRequestParameters.m, IdentityCore/src/requests/MSIDInteractiveTokenRequest.m, IdentityCore/src/requests/MSIDSilentTokenRequest.m, IdentityCore/tests/MSIDAADV1WebviewFactoryTests.m, IdentityCore/tests/MSIDAADV2WebviewFactoryTests.m, IdentityCore/tests/MSIDAADWebviewFactoryTests.m, IdentityCore/tests/MSIDInteractiveTokenRequestParametersTests.m, IdentityCore/tests/MSIDRequestParametersTests.m, IdentityCore/tests/MSIDWebviewFactoryTests.m, IdentityCore/tests/util/MSIDTestURLResponse+Util.m, changelog.txt
Add an HTTP header to the request containing the user's id or login hint.
=> Add CCS hint header

IdentityCore/src/pop_manager/MSIDDevicePopManager.m, IdentityCore/tests/MSIDAccountCacheItemTests.m, IdentityCore/tests/MSIDCredentialCacheItemTests.m
Change ts field from string to number in AT Pop
=> update ts in AT pop signature from string to long

IdentityCore/tests/automation/ui_app_lib/ui_common/ios/MainAutomation.storyboard
=> add some padding on top of go button

changelog.txt
merge back release 1.6.6 into dev
- [x ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)
=> Hieund/merge release 1.6.6 into dev

IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m, changelog.txt
=> Login keychain for developers

changelog.txt
Merge release 1.6.7 back into dev.
=> Merge release 1.6.7 into dev

IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, IdentityCore/src/cache/MSIDKeychainTokenCache.m, IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m, IdentityCore/src/logger/MSIDLogger.m, IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/oauth2/MSIDTokenResponse.m, IdentityCore/src/util/NSURL+MSIDExtensions.m, IdentityCore/src/validation/MSIDAadAuthorityCache.m
Related work item: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1437512
=> Refactor exceptions.

IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m, changelog.txt
=> Merge 1.6.8 hotfix in dev

IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m, changelog.txt
=> Merge 1.6.8 in master

changelog.txt
=> trying to resolve merge conflict

IdentityCore/tests/MSIDSystemWebviewControllerTests.m, IdentityCore/tests/integration/ios/MSIDBrokerInteractiveControllerIntegrationTests.m, azure_pipelines/pr-validation.yml
=> [In progress] Use mac os 11 for ci/cd.

azure_pipelines/verify_msalcpp_per_pr_ios.yml, azure_pipelines/verify_msalcpp_per_pr_mac.yml
=> Update cpp pipelines.

IdentityCore/src/MSIDConstants.h, IdentityCore/src/util/MSIDPromptType.m, changelog.txt
Work item: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1233367
Spec: https://openid.net/specs/openid-connect-prompt-create-1_0.html
=> Add support of "create" prompt.

build.py, changelog.txt, device_guids.py
Merging release 1.7.1 back into dev.
=> Merge release 1.7.1 back into dev

IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m, build.py, changelog.txt, device_guids.py
A copy of [this pr](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1057).
=> [Hotfix] Use base64URLEncoding for RSA modules

IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m, build.py, changelog.txt, device_guids.py
* Use base64URLEncoding for RSA modules.
* Update changelog.
* Use msidBase64UrlEncodedString for exponent.
* Update scripts.
=> Merge Hotfix 1.7.2 in master

IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m, build.py, changelog.txt, device_guids.py
=> Merge 1.7.2 in dev

IdentityCore/src/webview/MSIDWebviewAuthorization.m
log webview type before showing prompt
=> log webview type before showing prompt

IdentityCore/src/throttling/cache/MSIDLRUCache.m, IdentityCore/src/throttling/model/MSIDThrottlingModelFactory.m, changelog.txt
Remove throttle noise in log:
- Miss cache will be treated as internal error and will not be log
- Change some log from INFO/ERROR to VERBOSE/INFO
=> reduce throttle noise

IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDTestAutomationAccountConfigurationRequest.m
Merge automation fix to release branch
=> Merge automation fix to release branch

IdentityCore/src/util/NSString+MSIDExtensions.h, IdentityCore/src/util/NSString+MSIDExtensions.m, changelog.txt
Based on internal discussion with Olga on this PR: https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/833
adding additional string manipulation convenience methods in the extension class.
=> added more string convenience methods

changelog.txt
=> Merge release branch to dev

IdentityCore/src/oauth2/MSIDWebviewFactory.m, IdentityCore/src/parameters/MSIDInteractiveTokenRequestParameters.h, IdentityCore/src/parameters/MSIDInteractiveTokenRequestParameters.m, IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m, IdentityCore/tests/MSIDInteractiveTokenRequestParametersTests.m
=> Fix broker EQP

IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.m, IdentityCore/src/oauth2/MSIDWebviewFactory.m, IdentityCore/src/parameters/MSIDInteractiveTokenRequestParameters.h, IdentityCore/src/parameters/MSIDInteractiveTokenRequestParameters.m, IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m, IdentityCore/tests/MSIDInteractiveTokenRequestParametersTests.m, changelog.txt
Merge Release/1.7.3 back to dev
=> Merge Release/1.7.3 back to dev

IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.m, IdentityCore/src/requests/broker/MSIDSSOExtensionGetDeviceInfoRequest.m
Update TODO item to unfinished work, otherwise, a bug will be generated here in CPP.
Example here: https://identitydivision.visualstudio.com/Engineering/_boards/board/t/Auth%20Client%20-%20CPP/Backlog%20items/?workitem=1740487
=> Update TODO item to remove system generated bug in Cpp dashboard

IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationSignoutFromDeviceRequest.h, IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationSignoutFromDeviceRequest.m, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.h, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/controllers/MSIDRequestControllerFactory.h, IdentityCore/src/controllers/MSIDRequestControllerFactory.m, IdentityCore/src/controllers/broker/MSIDSSOExtensionSignoutController.h, IdentityCore/src/controllers/broker/MSIDSSOExtensionSignoutController.m, IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.h, IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.m, IdentityCore/tests/MSIDBrokerOperationSignoutFromDeviceRequestTests.m, IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m, IdentityCore/tests/integration/MSIDSSOExtensionSignoutRequestIntegrationTests.m, changelog.txt
=> Wipe cache for all accounts - IdentityCore

IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.m
createTrustedAppListWithCurrentApp is called multiple times during initialization, increasing the application init time. 
Calling it once and using the result of createTrustedAppListWithCurrentApp, improves app init time.
It improves Office boot time by around 6/7%.
=> Perf improvements by calling trustedAppListWithCurrentApp once

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m, IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m, IdentityCore/src/cache/token/MSIDAccountCacheItem.h, IdentityCore/src/cache/token/MSIDAccountCacheItem.m, IdentityCore/src/oauth2/account/MSIDAccountIdentifier.h, IdentityCore/src/oauth2/account/MSIDAccountIdentifier.m, IdentityCore/tests/MSIDMSIDAccountIdentifierTests.m, azure_pipelines/pr-validation.yml, build.py, device_guids.py
add more logs in cache query in ADAL to investigate Outlook + MAM SDK issue (hot fix 6.0.3)
=> ADAL hotfix 6.0.3

IdentityCore/src/cache/serializers/MSIDKeyedArchiverSerializer.m, IdentityCore/tests/MSIDKeyedArchiverSerializerTests.m
Address common-core update for hotfix [ADAL 6.0.2]
=> Update common core from ADAL hot fix 6.0.2

IdentityCore/src/cache/MSIDMacTokenCache.m, IdentityCore/src/util/NSDictionary+MSIDExtensions.m
=> Fix mac token cache thread safety

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
Enable BitCode in Common Core project:
For more info, please refer to:
https://developer.apple.com/documentation/xcode/doing-basic-optimization-to-reduce-your-app-s-size
=> enable bitcode

IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, IdentityCore/src/network/request_server_telemetry/MSIDAADTokenRequestServerTelemetry.m, IdentityCore/src/network/request_server_telemetry/MSIDHttpRequestServerTelemetryHandling.h
Add detailed SSO-JIT telemetry:
- Add error codes specific for each case
- Allow lastError telemetry to use a custom error string
=> [IdentityCore] Add detailed SSO-JIT telemetry

IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m
=> Fix a compiling issue with Edge on Mac

IdentityCore/src/util/ios/MSIDKeychainUtil.m
=> Improve logging

IdentityCore/src/cache/key/MSIDDefaultCredentialCacheKey.m, IdentityCore/src/oauth2/token/MSIDCredentialType.h, IdentityCore/src/oauth2/token/MSIDCredentialType.m
Refactor code to allow removing specific credentials in the broker.
=> Refactor credential type utility methods

IdentityCore/IdentityCore.xcodeproj/project.pbxproj
=> Disable bitcode flag everywhere

IdentityCore/src/webview/MSIDWebviewAuthorization.m, changelog.txt
Intune team reported a wrong error logger
=> fix a wrong error logger

IdentityCore/src/MSIDBrokerConstants.h, IdentityCore/src/MSIDBrokerConstants.m
Add AAD certificate thumbprint to returned deviceInfo.
=> Add AAD certificate thumbrpint to constants

IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.h, IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.m
Added a couple of WPJ oriented UI automation operations.
=> Added a few WPJ UI automation operations

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/controllers/MSIDRequestControllerFactory.h, IdentityCore/src/controllers/MSIDRequestControllerFactory.m, IdentityCore/tests/MSIDRequestControllerFactoryTests.m, changelog.txt
=> update API to allow pass in skipLocalRt when creating silent controller

IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.m
Add more logs to understand how enrollment_id is queried by, also remove some duplicate code
=> Add more logs to print how enrollment_id is fetched

IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m, changelog.txt
=> Update change logs

IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m, IdentityCore/tests/MSIDWorkPlaceJoinUtilTests.m, changelog.txt
Merge hotfix branch back to dev
=> Kaisong1990/merge release 1.7.15 into dev

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationBrowserTokenRequest.m, IdentityCore/tests/MSIDBrokerOperationBrowserTokenRequestTests.m
Print additional Browser SSO request type to quickly distinguish between OAuth authorize and token requests in the logs.
=> Print browser sso request type in logs

IdentityCore/src/network/MSIDAADEndpointProvider.m, IdentityCore/src/network/MSIDAADEndpointProviding.h
Updated EndpointProvider to return jwksEndpoint and issuer
- [ x] Feature work
- [x ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)
=> Updated EndpointProvider to return jwksEndpoint and issuer

IdentityCore/src/MSIDError.m
Updated MSIDError in MSIDErrorToString to have server error as well.
Updated MSIDError -> MSIDErrorTOString to have MSIDErrorServerError
=> Updated MSIDError

IdentityCore/src/util/MSIDKeyOperationUtil.h
Adding missing import header to fix CPP build
=> Adding missing header

IdentityCore/src/MSIDBrokerConstants.h, IdentityCore/src/MSIDBrokerConstants.m, IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, IdentityCore/src/webview/response/MSIDJITTroubleshootingResponse.h, IdentityCore/src/webview/response/MSIDJITTroubleshootingResponse.m, IdentityCore/tests/MSIDJITTroubleshootingResponseTests.m
Update JITTroubleshootingResponse to also return when JIT troubleshooting page is required.
=> JIT troubleshooting flow - part 2 [common]

changelog.txt
=> Use correct format for changelog's version

azure_pipelines/pr-validation.yml, build.py
Update pipeline to macOS13.
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2502860
=> Update CI/CD and automation to use Xcode 14 instead of Xcode 13 (IdentityCore)

changelog.txt
=> Merge release 1.7.22 into dev

IdentityCore/tests/MSIDAccountCredentialsCacheTests.m
=> Address comment

IdentityCore/src/util/MSIDRedirectUri.h, IdentityCore/src/util/MSIDRedirectUri.m, IdentityCore/src/util/ios/MSIDRedirectUriVerifier.m, IdentityCore/src/util/mac/MSIDRedirectUriVerifier.m, IdentityCore/tests/MSIDBrokerRedirectUriTest.m
Enhance broker redirect_uri validation and expose failure reasons to OneAuth/MSAL for better telemetry.
=> Enhance broker redirect validation

IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, IdentityCore/src/cache/MSIDKeychainTokenCache.m, IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m, changelog.txt
Add method and line number for the error occured in telemetry
=> Add method and line number for the error occured in telemetry

IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, IdentityCore/src/cache/MSIDKeychainTokenCache.m, IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m, changelog.txt
=> Master to main

IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, IdentityCore/src/cache/MSIDKeychainTokenCache.m, IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m, changelog.txt
=> Merge main to dev

README.md
Updating readme about master branch deprecation
=> Update readme about master deprecation

README.md
=> Updating readme with master branch deprecation

IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetCookiesRequest.h, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetCookiesRequest.m, IdentityCore/tests/MSIDBrowserNativeMessageGetCookiesRequestTests.m, IdentityCore/tests/MSIDWorkPlaceJoinUtilTests.m, build.py
=> Refactor MSIDBrowserNativeMessageGetCookiesRequest

changelog.txt
Update changelog to include 1.7.25 release entry.
=> Update changelog to 1.7.25 release

changelog.txt
Merge main to release branch + update changelog
=> Merge main to release branch + update changelog

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/util/MSIDWebAuthNUtil.h, IdentityCore/src/util/MSIDWebAuthNUtil.m, build.py
Add helper to know if we are running in SSO Extension or not.
=> Running in SSO extension helper

build.py
=> fix build pipeline in hotfix

azure_pipelines/verify_msalcpp_per_pr_ios.yml, azure_pipelines/verify_msalcpp_per_pr_mac.yml
This is to fix CPP pipelines on iOS and MacOS
=> Update verify_msalcpp_per_pr_ios.yml for Azure Pipelines

changelog.txt
Merge back from main branch to dev
=> merge hotfix 1.7.29 into dev

IdentityCore/src/requests/MSIDInteractiveTokenRequest.m, IdentityCore/src/requests/MSIDSilentTokenRequest.m, IdentityCore/src/requests/MSIDTokenResponseHandler.h, IdentityCore/src/requests/MSIDTokenResponseHandler.m, IdentityCore/src/requests/broker/MSIDSSOTokenResponseHandler.m, IdentityCore/tests/MSIDThrottlingServiceIntegrationTests.m
Mapping broker version to token results for OneAuth telemetry
=> Mapping broker version to existing token result value

IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, changelog.txt
=> Fix typo in error code

IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m, changelog.txt
Common core hotfix 1.7.31 release
-[x] Release
=> IdentityCore Hotfix/1.7.31 release

IdentityCore/src/MSIDError.m
=> Pass back real error code when there is no matching MSID error code

IdentityCore/src/MSIDBrokerConstants.h, IdentityCore/src/MSIDBrokerConstants.m, IdentityCore/src/network/MSIDHttpRequest.h, IdentityCore/src/network/MSIDHttpRequest.m, IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m, IdentityCore/src/network/request_configurator/MSIDAADRequestConfigurator.m, IdentityCore/src/network/request_serializer/MSIDUrlRequestSerializer.m, IdentityCore/tests/MSIDAADRequestErrorHandlerTests.m, IdentityCore/tests/util/MSIDTestURLResponse+Util.m
The two features that were added will only be accessible with a flag.
Broker change to pass in experiment_bag:
https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/1486
=> IdentityCore change: Optimize acquire_token_silently in broker. 

IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDNTLMHandler.m
This PR adds a credential options helper method in MSIDNTLMHandler. It can be overridden if needed.
=> Added credential persistence option method for NTLM

IdentityCore/src/MSIDBrokerConstants.h, IdentityCore/src/MSIDBrokerConstants.m, IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.m, IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h, IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m, IdentityCore/src/parameters/MSIDRequestParameters.h, IdentityCore/src/parameters/MSIDRequestParameters.m, IdentityCore/src/requests/broker/MSIDBrokerTokenRequest.m, IdentityCore/tests/MSIDBrokerOperationInteractiveTokenRequestTests.m, IdentityCore/tests/MSIDBrokerOperationSilentTokenRequestTests.m, IdentityCore/tests/MSIDBrokerOperationTokenRequestTests.m, IdentityCore/tests/integration/ios/MSIDBrokerTokenRequestTests.m, IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m, IdentityCore/tests/integration/ios/MSIDLegacyBrokerRequestTests.m
Skip Account Validation based on request parameters.
=> Skip Account Validation based on request parameters.

IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetTokenRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageRequest.m
=> Fix constants prefix

azure_pipelines/pr-validation.yml, build.py
=> revert ios version for release

IdentityCore/tests/automation/ui_app_lib/MSIDClearCookiesTestAction.m, IdentityCore/tests/automation/ui_tests_lib/MSIDBaseUITest.m
Added a few minor automation stability improvements.
=> Minor automation stability tweaks

IdentityCore/src/oauth2/MSIDExternalSSOContext.m, changelog.txt
fix pkey auth in server side removal case
=> fix pkey auth in server side removal case

changelog.txt
update changelog version to not use 4 digits
=> update changelog version

IdentityCore/src/oauth2/MSIDExternalSSOContext.h, IdentityCore/src/oauth2/MSIDExternalSSOContext.m, changelog.txt
Fix PSSO multi user and bug during initial registration- patch step-> pkey auth
- [ x] Bug fix
=> Veena/fix 1.7.32.2

IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDCertificateChooser.m
"endSheet: returnCode:" was called not on the main thread.
=> Fix crash in cert chooser

changelog.txt
=> Antonioalwan/merge release 1.7.34 into dev

IdentityCore/tests/automation/ui_tests_lib/KeyvaultAuthentication.swift, IdentityCore/tests/automation/ui_tests_lib/MSIDTestConfigurationProvider.m, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationOperationAPIRequestHandler.h, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationOperationAPIRequestHandler.m
1. Removed the dependency from ADAL keyvault app
2. Removed the dependency of using client secret from Lab apps
=> Automation code change to handle recent security changes requirements

IdentityCore/src/MSIDConstants.h, IdentityCore/src/util/NSString+MSIDTelemetryExtensions.h, IdentityCore/src/util/NSString+MSIDTelemetryExtensions.m, IdentityCore/tests/MSIDTelemetryExtensionsTests.m
=> Update x-client-xtra-sku format

azure_pipelines/verify_msalcpp_per_pr_ios.yml, azure_pipelines/verify_msalcpp_per_pr_mac.yml
MSAL CPP needs specific arguments for tests when building.
=> Update verify_msalcpp_per_pr_mac.yml for Azure Pipelines

IdentityCore/src/MSIDConstants.h, IdentityCore/src/util/NSString+MSIDTelemetryExtensions.h, IdentityCore/src/util/NSString+MSIDTelemetryExtensions.m, IdentityCore/tests/MSIDTelemetryExtensionsTests.m, azure_pipelines/verify_msalcpp_per_pr_mac.yml, changelog.txt
=> Merge release 1.7.36 into dev

IdentityCore/tests/automation/ui_tests_lib/KeyvaultAuthentication.swift, IdentityCore/tests/automation/ui_tests_lib/MSIDBaseUITest.h, IdentityCore/tests/automation/ui_tests_lib/MSIDClientCredentialHelper.m, IdentityCore/tests/automation/ui_tests_lib/MSIDTestConfigurationProvider.m, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationBaseApiRequest.h, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationBaseApiRequest.m, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationDeleteDeviceAPIRequest.m, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationOperationAPIRequestHandler.h, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationOperationAPIRequestHandler.m, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationResetAPIRequest.m, IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDAutomationTemporaryAccountRequest.m
Clean up previous workaround and add support for x5c for lab account
=> Switch to SNI cert for MSAL and Broker automation. Also remove workaround code from previous release

azure_pipelines/verify_msalcpp_per_pr_ios.yml, azure_pipelines/verify_msalcpp_per_pr_mac.yml
=> Verify MSAL-CPP: Update macOS/Xcode versions to match MSAL-CPP

IdentityCore/src/webview/response/MSIDWebUpgradeRegResponse.m, IdentityCore/tests/MSIDAADWebviewFactoryTests.m
Fix case for upgradeReg for Upgrade registration flow.
=> Fix case for upgradeReg for Upgrade registration flow

IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetTokenRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageSignOutRequest.m
=> Enable GetToken and SignOut apis

IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetTokenRequest.h, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetTokenRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageSignOutRequest.m, IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m, IdentityCore/src/util/NSString+MSIDTelemetryExtensions.m, IdentityCore/tests/MSIDTelemetryExtensionsTests.m
=> Report browser core version

IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h, IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
Post new notification to auth app when no cert auth in progress
- [ x] Bug fix
=> Fix Cert Auth for Auth app

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetSupportedContractsRequest.h, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetSupportedContractsRequest.m, IdentityCore/src/broker_operation/response/browser_native_message_response/MSIDBrowserNativeMessageGetSupportedContractsResponse.h, IdentityCore/src/broker_operation/response/browser_native_message_response/MSIDBrowserNativeMessageGetSupportedContractsResponse.m
=> Support GetSupportedContracts api.

IdentityCore/tests/MSIDLRUCacheTest.m, IdentityCore/tests/MSIDThrottlingServiceIntegrationTests.m, IdentityCore/tests/integration/MSIDInteractiveControllerIntegrationTests.m, IdentityCore/tests/integration/ios/MSIDBrokerInteractiveControllerIntegrationTests.m, IdentityCore/tests/integration/ios/MSIDBrokerOptionsTests.m, IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
=> short term flakiness UT fix

IdentityCore/src/broker_operation/request/MSIDBaseBrokerOperationRequest.h, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrokerOperationBrowserNativeMessageRequest.h, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrokerOperationBrowserNativeMessageRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetTokenRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageRequest.h, IdentityCore/tests/MSIDBrokerOperationBrowserNativeMessageRequestTests.m, IdentityCore/tests/MSIDBrowserNativeMessageGetTokenRequestTests.m, changelog.txt
Modify SSO ext UI caller info for browser SSO flows. Format:
Team ID - browser team id
Bundle ID - browser bundle id
Application - “Client ID: <app client id> Redirect URI: <redirect URI>”
Provide new public APIs for CP team. Related work item: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/3036432
=> Support caller app info for browser SSO flows 

changelog.txt
Refresh dev with release 1.7.42
=> Merge release/17.42 back into dev

IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.m, IdentityCore/src/requests/broker/MSIDSSOExtensionGetDeviceInfoRequest.m, IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m, IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.m, IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
Assign completion block before perform request and fix potential threading issue.
=> Assign completion block before perform request

IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m
Add new key for sub error description.
=> Save error received from ESTS, and use it to return to the client its description on silent broker calls [CommonCore]

IdentityCore/src/MSIDBrokerConstants.h, IdentityCore/src/MSIDBrokerConstants.m, IdentityCore/src/broker_operation/request/MSIDBaseBrokerOperationRequest.h, scripts/update_xcode_config_cpp_checks.py
1. Add a new requestType later to be used to distinguish if the request is within XPC or SsoExt context
2. new MSID_BROKER_SDK_BROKER_XPC_CAPABILITY constant
=> XPC CommonCore Minor change to support broker XPC changes

IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h, IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m, IdentityCore/src/parameters/MSIDRequestParameters.h
For more details see broker pr: https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/1735
=> Support web_page_uri

IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.h, IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.m, IdentityCore/tests/automation/shared/MSIDAutomationUserInformation.h, IdentityCore/tests/automation/shared/MSIDAutomationUserInformation.m
Support automation for MSA accounts
=> MSA Automation support

IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h, IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m, IdentityCore/src/broker_operation/response/browser_native_message_response/MSIDBrowserNativeMessageGetTokenResponse.m, IdentityCore/src/oauth2/MSIDOauth2Factory.m, IdentityCore/src/oauth2/MSIDTokenResponse.h, IdentityCore/src/oauth2/MSIDTokenResponse.m, IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.h, IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.m, IdentityCore/src/parameters/MSIDRequestParameters.h, IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.h, IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m, IdentityCore/src/requests/sdk/adal/MSIDLegacyTokenResponseValidator.m, IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenResponseValidator.m, IdentityCore/tests/MSIDDefaultTokenResponseValidatorTests.m, IdentityCore/tests/MSIDLegacyTokenResponseValidatorTests.m, changelog.txt
=> Add support of "lookup" mode in broker

azure_pipelines/broker_submodule_check.yml, azure_pipelines/msal_submodule_check.yaml
This PR adds a yaml file to replace the [Broker] Common core submodule check pipeline. This yaml pipeline uses the ADO built-in checkout function to checkout broker.
=> Broker submodule check yaml pipeline

IdentityCore/src/MSIDError.h, IdentityCore/src/MSIDError.m
=> Add new psso error

IdentityCore/tests/MSIDTokenResponseTests.m
Split dummy test id token to avoid getting it flagged as a secret
=> Split dummy test id token to avoid getting it flagged as a secret

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/MSIDConstants.m, IdentityCore/src/webview/operations/ios/MSIDSwitchBrowserOperation.m, IdentityCore/src/webview/operations/ios/MSIDSwitchBrowserResumeOperation.m, IdentityCore/src/webview/response/MSIDSwitchBrowserResponse.h, IdentityCore/src/webview/response/MSIDSwitchBrowserResponse.m, IdentityCore/src/webview/response/MSIDWebviewResponse.h, IdentityCore/tests/MSIDSwitchBrowserResumeOperationTest.swift, IdentityCore/tests/mocks/MSIDFlightManagerMockProvider.h, IdentityCore/tests/mocks/MSIDFlightManagerMockProvider.m, changelog.txt
Original PR: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1493
=> Cherry pick DUNA "resume" action fix

IdentityCore/IdentityCore.xcodeproj/project.pbxproj, IdentityCore/src/MSIDConstants.m, IdentityCore/src/webview/operations/ios/MSIDSwitchBrowserOperation.m, IdentityCore/src/webview/operations/ios/MSIDSwitchBrowserResumeOperation.m, IdentityCore/src/webview/response/MSIDSwitchBrowserResponse.h, IdentityCore/src/webview/response/MSIDSwitchBrowserResponse.m, IdentityCore/src/webview/response/MSIDWebviewResponse.h, IdentityCore/tests/MSIDSwitchBrowserResumeOperationTest.swift, IdentityCore/tests/mocks/MSIDFlightManagerMockProvider.h, IdentityCore/tests/mocks/MSIDFlightManagerMockProvider.m, changelog.txt
=> Merge hotfix/1.9.1 in main

IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrokerOperationBrowserNativeMessageRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetCookiesRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageGetTokenRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageRequest.m, IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrowserNativeMessageSignOutRequest.m, IdentityCore/src/broker_operation/response/browser_native_message_response/MSIDBrowserNativeMessageGetCookiesResponse.m, IdentityCore/tests/MSIDBrokerOperationBrowserNativeMessageRequestTests.m, changelog.txt
=> Improve browser core logs

IdentityCore/src/util/MSIDRedirectUri.m
Refactor redirect uri verifier
=> [MSAL2.x]Refactor redirect uri verifier

IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
These other prompt types shouldn't need to receive existing RT:
- Select account 
- Create
=> Add extra cases that don't need to pass existing RT

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
Fix issue with integration with other project.
=> Exclude telemetry from MSAL C++

IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m, IdentityCore/src/requests/MSIDInteractiveTokenRequest.m, changelog.txt
Merging release 1.11.0 version back into dev
=> Fidelianawar/merge release 1.11.0 into dev

IdentityCore/src/MSIDConstants.h, IdentityCore/src/controllers/MSIDRequestControllerFactory.m, IdentityCore/tests/MSIDRequestControllerFactoryTests.m
Update the xpc mode enum names
=> Update enums for xpc mode naming

IdentityCore/tests/automation/ui_tests_lib/MSIDBaseUITest.m
Fix MSAL automation by handling the new UI.
=> Fix MSAL Automation

IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
Recently we found some crashes happened on iOS 26. After investigation we found that it is related to some code was not guranteed to be executed on main thread. Now fix the crash by gurantee main thread execution.
=> Execute loadRequest on Main Thread

IdentityCore/tests/automation/ui_tests_lib/MSIDBaseUITest.m
=> Address new UI for MSAL Automation

IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/webview/operations/ios/MSIDSwitchBrowserOperation.m, IdentityCore/src/webview/operations/ios/MSIDSwitchBrowserResumeOperation.m, IdentityCore/src/webview/response/MSIDSwitchBrowserResponse.m, IdentityCore/tests/IdentityCoreTests-Bridging-Header.h, IdentityCore/tests/MSIDSwitchBrowserOperationTest.swift, IdentityCore/tests/MSIDSwitchBrowserResponseTest.swift, IdentityCore/tests/MSIDSwitchBrowserResumeResponseTest.swift
Added MSID flight flag to state validation code, and fixed bug with state validation. State passed from url parameter is encoded so needed to decode it
=> Added flag for duna state validation

changelog.txt
Merge Release 1.14.0 back to dev
=> Merge Release 1.14.0 back to dev 

IdentityCore/src/broker_operation/request/browser_native_message_request/MSIDBrokerOperationBrowserNativeMessageRequest.m, IdentityCore/tests/MSIDBrokerOperationBrowserNativeMessageRequestTests.m
Fix AppInfo for Edge Native MSALJS Native Bridge Brower SSO Flow
=> Fix AppInfo for Edge Native MSALJS Native Bridge Brower SSO Flow

changelog.txt
=> change log updates

IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/webview/operations/ios/MSIDSwitchBrowserResumeOperation.m, changelog.txt
Cherry Pick Duna Fix and Update Changelog
Hotfix 1.15.1
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1574/files
=> Cherry Pick Duna Fix and Update Changelog

IdentityCore/src/MSIDConstants.h, IdentityCore/src/MSIDConstants.m, IdentityCore/src/webview/operations/ios/MSIDSwitchBrowserResumeOperation.m, changelog.txt
=> Merge Hotfix/1.15.1 to main

IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h, IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m, IdentityCore/src/parameters/MSIDRequestParameters.h
=> Add forceUI to MSIDRequestParameters
